### ISSUE TITLE
fail to export minute data as a csv

### ISSUE THREAD

**Issue by apastore** [enigmampc/catalyst#101]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System:
Darwin lski2446 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
* Python Version: Python 2.7.13 :: Continuum Analytics, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
catalyst, version 0.4.0
* Python packages:
#
alembic                   0.9.6                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.5.0                     <pip>
botocore                  1.8.14                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
ccxt                      1.10.319                  <pip>
certifi                   2016.2.28                py27_0  
certifi                   2017.11.5                 <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.0                     <pip>
futures                   3.2.0                     <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
jmespath                  0.9.3                     <pip>
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2017.0.3                      0  
multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0  
openssl                   1.0.2l               h492a243_5  
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1  
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.2                    <pip>
readline                  6.2                           2  
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     0.19.1              np113py27_0  
setuptools                36.4.0                   py27_1  
six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0  
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
wheel                     0.29.0                   py27_0  
zlib                      1.2.11               hf3cbc9b_2  

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
unable to export minute csv file

* What did you expect to happen?
I am trying to export minute data form different export and generete a csv file. I have slightly modified the .py example in the documentation since that one have incorrect syntax. 

* What happened instead?

I got this error 

I got this [2017-12-15 16:42:38.620775] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "get.coin.py", line 50, in <module>
    capital_base=10000 )
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 563, in run_algorithm
    stats_output=stats_output
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 346, in _run
    overwrite_sim_params=False,
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 318, in run
    data, overwrite_sim_params
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 243, in transform
    self._get_minute_message(dt, algo, algo.perf_tracker)
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 303, in _get_minute_message
    dt, self.data_portal,
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/finance/performance/tracker.py", line 357, in handle_minute_close
    account.leverage)
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/finance/risk/cumulative.py", line 212, in update
    self.mean_benchmark_returns_cont[dt_loc] * 252
RuntimeWarning: overflow encountered in double_scalars

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1) catalyst ingest-exchange -x poloniex -f minute -i btc_usdt 
2) python get.coin.py poloniex btc_usdt

$cat get.coin.py

import os
import csv
import pytz
from datetime import datetime
import sys

from catalyst.api import record, symbol, symbols
from catalyst.utils.run_algo import run_algorithm

print sys.argv[1]
print sys.argv[2]
pair = sys.argv[2]
exchange_ID = sys.argv[1]
def initialize(context):
# Portfolio assets list
  context.asset = symbol(pair) # Bitcoin on Poloniex
  context.csvfile   = open(os.path.splitext(
			  os.path.basename(pair))[0]+'_'+exchange_ID+'.csv', 'w+')
  context.csvwriter = csv.writer(context.csvfile)

def handle_data(context, data):
# Variables to record for a given asset: price and volume
# Other options include 'open', 'high', 'open', 'close'
# Please note that 'price' equals 'close'
  date   = context.blotter.current_dt     # current time in each iteration
  price  = data.current(context.asset, 'price')
  volume = data.current(context.asset, 'volume')
  context.csvwriter.writerow([date,price,volume])
# Writes one line to CSV on each iteration with the chosen variables

def analyze(context=None, results=None):
# Close open file properly at the end
  context.csvfile.close()

# Bitcoin data is available from 2015-3-2. Dates vary for other tokens.
start = datetime(2017, 12, 1, 0, 0, 0, 0, pytz.utc)
end = datetime.now(pytz.utc)
print start
print end
results = run_algorithm(initialize=initialize,
                        handle_data=handle_data,
                        analyze=analyze,
                        start=start,
                        end=end,
                        exchange_name=exchange_ID,
                        data_frequency='minute',
                        base_currency ='usdt',
                        capital_base=10000 )

Thanks a lot for your help,
alessandro 

Error message 

[2017-12-15 16:42:37.395114] INFO: run_algo: running algo in paper-trading mode
[2017-12-15 16:42:38.619044] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2017-12-15 16:39:31+00:00.
[2017-12-15 16:42:38.620775] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "get.coin.py", line 50, in <module>
    capital_base=10000 )
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 563, in run_algorithm
    stats_output=stats_output
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 346, in _run
    overwrite_sim_params=False,
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 318, in run
    data, overwrite_sim_params
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 243, in transform
    self._get_minute_message(dt, algo, algo.perf_tracker)
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 303, in _get_minute_message
    dt, self.data_portal,
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/finance/performance/tracker.py", line 357, in handle_minute_close
    account.leverage)
  File "/Users/pastorea/miniconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/finance/risk/cumulative.py", line 212, in update
    self.mean_benchmark_returns_cont[dt_loc] * 252
RuntimeWarning: overflow encountered in double_scalars

**Comment by fredfortier** [comment]
It's having issue with benchmark data. We will review further shortly.

**Comment by arthrfrnco** [comment]
@fredfortier I'm getting the same error while running a mean_reversion_simple.py backtest, always when it gets to 2017-12-12. When I try to run it before that day, it works.

**Comment by andresespinosapc** [comment]
How is the fix of this issue going? I can't use the library because of this :(

**Comment by jonathan-s** [comment]
Also having this issue.

**Comment by fredfortier** [comment]
It looks like one of those issues with empyrical. I thought that we've
worked around most of them, but it's not clean. We'll need to rebase to the
latest zipline which includes a more recent version of the empyrical
library. Can you better explain what you are trying to accomplish though.
I'm not familiar with `csvexport`. Do you get this issue when running a
regular algo or when exporting something?

**Comment by jonathan-s** [comment]
```
import os
import csv
import pytz
from datetime import datetime

from catalyst.api import record, symbol, symbols
from catalyst.utils.run_algo import run_algorithm


def initialize(context):
    # Portfolio assets list
    context.asset = symbol('btc_usdt') # Bitcoin on Poloniex

    # Creates a .CSV file with the same name as this script to store results
    context.csvfile = open(os.path.splitext(os.path.basename('btc_usdt_error'))[0]+'.csv', 'w+')
    context.csvwriter = csv.writer(context.csvfile)
    context.csvwriter.writerow(['date', 'open', 'close', 'high', 'low', 'volume'])

def handle_data(context, data):
    # Variables to record for a given asset: price and volume
    # Other options include 'open', 'high', 'open', 'close'
    # Please note that 'price' equals 'close'
    date   = context.blotter.current_dt     # current time in each iteration
    opened = data.current(context.asset, 'open')
    close = data.current(context.asset, 'close')
    high = data.current(context.asset, 'high')
    low = data.current(context.asset, 'low')
    volume = data.current(context.asset, 'volume')

    # Writes one line to CSV on each iteration with the chosen variables
    context.csvwriter.writerow([date, opened, close, high, low, volume])

def analyze(context=None, results=None):
    # Close open file properly at the end
    context.csvfile.close()


# Bitcoin data is available from 2015-3-2. Dates vary for other tokens.
start = datetime(2017, 12, 6, 0, 0, 0, 0, pytz.utc)
end = datetime(2017, 12, 8, 0, 0, 0, 0, pytz.utc)
results = run_algorithm(
    initialize=initialize,
    handle_data=handle_data,
    analyze=analyze,
    start=start,
    end=end,
    exchange_name='poloniex',
    data_frequency='minute',
    base_currency ='usdt',
    capital_base=10000
)
```

You can run the above script and that will throw the error. I don't really know what happens in cumulative.py or what `mean_benchmark_returns` does. But suffice to say, it generates a very big number during the above script; 1.5 * 10^305 and when you multiply that with 252 you get the overflow.

**Comment by fredfortier** [comment]
Ok thanks. This helps troubleshooting further. We'll get back to you.

**Comment by zackgow** [comment]
I had the same error earlier today while running a different script. When I changed my `start_date`, the issue was resolved. My theory was that the start date had some missing data, and that led to a divide by zero error in a `pct_change` calculation or something similar.

**Comment by andresespinosapc** [comment]
@zackgow Is not due to missing data. I do not get the error from 2017-12-02 to 2017-12-04 neither from 2017-12-03 to 2017-12-05, but I do get it from 2017-12-01 to 2017-12-05.

**Comment by zackgow** [comment]
@andresespinosapc 2017-12-01 was the date that gave me the error too. Changing that fixed my issues.

**Comment by fredfortier** [comment]
Thanks guys, this helps narrow down the root cause. Looking into it at the
moment.

**Comment by salihkilic** [comment]
Not sure if this issue is still open, but I'm getting the same problem @ 2017-12-08 07:45, when I do a backtest from 2017-12-3 to 2017-12-9. Hope this helps.

**Comment by yeshymanoharan** [comment]
I am also getting a similar error which doesnt seemed connected to a specific date, and I have other strategies that work with that date range, and the error always pops up 3 days after the startdate. Is there a solution to this, maybe an ability to prevent any calculations from being like mean_benchmark_returns_cont made that would cause that overflow issue?
