### ISSUE TITLE
Papermode failing on get_open_orders (ccxt)

### ISSUE THREAD

**Issue by vonpupp** [enigmampc/catalyst#110]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `Linux <hostname removed> 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux`)
* Python Version: `2.7.14`
* Python Bitness: `64`
* How did you install Catalyst: pip
* Python packages: `$ pip freeze`:
```
agate==1.6.0
agate-dbf==0.2.0
agate-excel==0.2.1
agate-sql==0.5.2
alembic==0.9.6
Babel==2.5.1
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
bleach==2.1.2
boto3==1.5.1
botocore==1.8.15
Bottleneck==1.2.1
ccxt==1.10.408
certifi==2017.11.5
chardet==3.0.4
click==6.7
configparser==3.5.0
contextlib2==0.5.5
csvkit==1.0.2
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
dbfread==2.0.7
decorator==4.1.2
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.4.0+1.g94583c2
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
haikunator==2.1.0
html5lib==1.0.1
idna==2.6
intervaltree==2.1.0
ipdb==0.10.3
ipykernel==4.7.0
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.0.5
isodate==0.6.0
jdcal==1.3
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
leather==0.3.3
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
mistune==0.8.3
multipledispatch==0.4.9
names==0.3.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
notebook==5.2.2
numexpr==2.6.4
numpy==1.13.3
openpyxl==2.4.9
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
parsedatetime==2.4
pathlib2==2.3.0
patsy==0.4.1
petname==2.2
pexpect==4.3.0
pickleshare==0.7.4
pkg-resources==0.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
python-slugify==1.2.4
pytimeparse==1.1.7
pytz==2017.3
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
s3transfer==0.1.12
scandir==1.6
scipy==1.0.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.1.15
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.10
tables==3.4.2
terminado==0.8.1
testpath==0.3.1
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
transitions==0.6.2
Unidecode==0.4.21
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.0.8
xlrd==1.1.0
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Error using paper mode trading

* When I run on paper mode trading, I expect to see the same behaviour as on backtesting but live on slow motion.
* Instead I get crashes as soon as Catalyst tries to communicate with the exchange.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Use a strategy on paper mode
2. Use bitfinex
3. Do not use API keys

You will get the following error:
```
(.envc-unstable) > $ python d_abba_papermode.py
[2017-12-20 02:54:28.019734] INFO: run_algo: running algo in paper-trading mode
[2017-12-20 02:54:29.212381] INFO: exchange_bundle: pricing data for [u'btc_usdt'] not found in range 2015-03-01 00:00:00+00:00 to 2017-12-19 00:00:00+00:00, updating the bundles.
    [====================================]  Ingesting daily price data for btc_usdt on poloniex:  100%
[2017-12-20 02:54:29.701350] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2017-12-20 02:50:21.998121+00:00.
[2017-12-20 02:54:29.707234] INFO: exchange_algorithm: initialized trading algorithm in live mode
[2017-12-20 02:54:29.737373] INFO: abba_test: 
STARTING SIMULATION.
Candles sample rate: 30
Candles frequency: 30T
Candles buffer size: 48
             
[2017-12-20 02:54:29.749396] INFO: exchange_algorithm: got totals from exchanges, cash: 1000.0 positions: 0.0
[2017-12-20 02:54:32.276275] INFO: abba_test: 
Index: 0
Date: 2017-12-20 02:54:00+00:00

Candle:
O: 16416.0
H: 16923.0
L: 16414.0
C: 16853.0
V: 1513.57806641

Portfolio:
Base price: 16853.0
Base coin (coin2/usd): 1000.0
Amount (coin1/btc): 0

Traceback (most recent call last):
  File "d_abba_papermode.py", line 225, in <module>
    live_graph=False
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 563, in run_algorithm
    stats_output=stats_output
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 346, in _run
    overwrite_sim_params=False,
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 648, in handle_data
    self._handle_data(self, data)
  File "/home/av/repos/example/strategies/family/abba.py", line 298, in default_handle_data
    orders = get_open_orders()
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/utils/api_support.py", line 57, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/utils/input_validation.py", line 831, in assert_keywords_and_call
    return func(*args, **kwargs)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 802, in get_open_orders
    return self._get_open_orders(asset)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 764, in _get_open_orders
    exchange_orders = exchange.get_open_orders()
TypeError: get_open_orders() takes exactly 2 arguments (1 given)
```

## What steps have you taken to resolve this already?

Some minor debugging and it seems to be related with the ccxt interface.

Thank you very much.

Sincerely,
V

**Comment by vonpupp** [comment]
I could make it work by removing a line that I had in the code during backtesting:
```
orders = get_open_orders
```

I will be closing the issue, feel free to reopen it again if `get_open_orders` applies also on paper/live mode.
