### ISSUE TITLE
Poloniex live trading not working

### ISSUE THREAD

**Issue by caioaao** [enigmampc/catalyst#119]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: `Linux [redacted] 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux`

* Python Version: `Python 2.7.13 :: Continuum Analytics, Inc.`
* Python Bitness: `64`
* How did you install Catalyst: `conda`
* Python packages: `$ pip freeze` or `$ conda list`
```
alembic                   0.9.6                     <pip>
backports-abc             0.5                       <pip>
backports.functools-lru-cache 1.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
bcolz                     0.12.1                    <pip>
bleach                    2.1.2                     <pip>
boto3                     1.5.6                     <pip>
botocore                  1.8.20                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h1d4fec5_0  
ccxt                      1.10.477                  <pip>
certifi                   2016.2.28                py27_0  
certifi                   2017.11.5                 <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
configparser              3.5.0                     <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.0+41.g869ef8ec           <pip>
entrypoints               0.2.3                     <pip>
enum34                    1.1.6                     <pip>
funcsigs                  1.0.2                     <pip>
functools32               3.2.3.post2               <pip>
futures                   3.2.0                     <pip>
html5lib                  1.0.1                     <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
ipykernel                 4.7.0                     <pip>
ipython                   5.5.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.0.5                     <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.0                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mistune                   0.8.3                     <pip>
mkl                       2017.0.3                      0  
mock                      2.0.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
networkx                  2.0                       <pip>
nose                      1.3.7                     <pip>
nose-ignore-docstring     0.2                       <pip>
nose-parameterized        0.6.0                     <pip>
notebook                  5.2.2                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0  
numpy                     1.13.3                    <pip>
openssl                   1.0.2l               h077ae2c_5  
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
pandocfilters             1.4.2                     <pip>
pathlib2                  2.3.0                     <pip>
patsy                     0.4.1                     <pip>
pbr                       3.1.1                     <pip>
pexpect                   4.3.1                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py27_1  
prompt-toolkit            1.0.15                    <pip>
ptyprocess                0.5.2                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.3                    <pip>
pyzmq                     16.0.3                    <pip>
qtconsole                 4.3.1                     <pip>
readline                  6.2                           2  
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scandir                   1.6                       <pip>
scipy                     1.0.0                     <pip>
scipy                     0.19.1              np113py27_0  
setuptools                38.2.5                    <pip>
setuptools                36.4.0                   py27_1  
simplegeneric             0.8.1                     <pip>
singledispatch            3.4.0.3                   <pip>
six                       1.11.0                    <pip>
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.1.15                    <pip>
sqlite                    3.13.0                        0  
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.5.18                        0  
toolz                     0.9.0                     <pip>
tornado                   4.5.2                     <pip>
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py27_0  
widgetsnbextension        3.0.8                     <pip>
zlib                      1.2.11               ha838bed_2  
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
Run algorithm on Poloniex live with no issues, with and without paper trading.
* What happened instead?
```
[2017-12-25 16:10:49.005036] INFO: run_algo: running algo in paper-trading mode
[2017-12-25 16:10:53.144093] INFO: exchange_algorithm: initialized trading algorithm in live mode
[2017-12-25 16:10:53.154051] INFO: exchange_algorithm: got totals from exchanges, cash: 100.0 positions: 0.0
Traceback (most recent call last):
  File ".../strategy.py", line 196, in <module>
    simulate_orders=True)
  File ".../site-packages/catalyst/utils/run_algo.py", line 563, in run_algorithm
    stats_output=stats_output
  File ".../site-packages/catalyst/utils/run_algo.py", line 346, in _run
    overwrite_sim_params=False,
  File ".../site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File ".../site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File ".../site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File ".../site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File ".../site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File ".../site-packages/catalyst/exchange/exchange_algorithm.py", line 648, in handle_data
    self._handle_data(self, data)
  File ".../strategy.py", line 166, in handle_data
    for asset in candidate_buys]
  File "catalyst/_protocol.pyx", line 120, in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call
  File "catalyst/_protocol.pyx", line 646, in catalyst._protocol.BarData.history
  File ".../site-packages/catalyst/exchange/exchange_data_portal.py", line 114, in get_history_window
    ffill)
  File ".../site-packages/catalyst/exchange/exchange_data_portal.py", line 73, in _get_history_window
    ffill)
  File ".../site-packages/catalyst/exchange/exchange_data_portal.py", line 248, in get_exchange_history_window
    False)
  File ".../site-packages/catalyst/exchange/exchange.py", line 493, in get_history_window
    last_traded = asset_series.index[-1]
  File ".../site-packages/pandas/tseries/base.py", line 251, in __getitem__
    val = getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
```
Here is how you can reproduce this issue on your machine:
## Reproduction Steps

1. Run:
```python
run_algorithm(
            capital_base=100,
            initialize=initialize,
            handle_data=handle_data,
            data_frequency='minute',
            analyze=analyze,
            exchange_name='poloniex',
            live=True,
            algo_namespace=ALGORITHM_NAMESPACE,
            base_currency='usdt',
            simulate_orders=True)
```
2. Inside the algorithm, call `data.history(asset, ['close'], bar_count=100, frequency='5m')`;

## What steps have you taken to resolve this already?

Tried looking at the code and found one interesting bit: on a commit that only says "PEP8 MAINT", some tests were commented out and they seem to be related (though it only tests the bitfinex exchange (running it once already yields a ratelimit, so maybe that's why it's commented?): https://github.com/enigmampc/catalyst/blob/94583c2684ca5e43b3a21296789dd21378be66aa/tests/exchange/test_data_portal.py#L39

After some tweaks to run the tests against poloniex, this is what I get (using master branch):

```
======================================================================
ERROR: test_data_portal.TestExchangeDataPortal.test_get_history_window_live
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caio/anaconda3/envs/catalyst-dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/caio/reps/catalyst/tests/exchange/test_data_portal.py", line 52, in test_get_history_window_live
    'price')
  File "/home/caio/reps/catalyst/catalyst/exchange/exchange_data_portal.py", line 114, in get_history_window
    ffill)
  File "/home/caio/reps/catalyst/catalyst/exchange/exchange_data_portal.py", line 73, in _get_history_window
    ffill)
  File "/home/caio/reps/catalyst/catalyst/exchange/exchange_data_portal.py", line 248, in get_exchange_history_window
    False)
  File "/home/caio/reps/catalyst/catalyst/exchange/exchange.py", line 499, in get_history_window
    exchange=self.name,
LastCandleTooEarlyError: The trade date of the last candle 2017-11-30 13:08:28.741013+00:00 is before the specified end date minus one candle 2017-12-21 13:08:28.741013+00:00. Please verify how poloniex calculates the start date of OHLCV candles.
```

**Comment by caioaao** [comment]
I reproduced it with bittrex as well. Here's the code:
```python
from catalyst.api import symbol
from catalyst.utils.run_algo import run_algorithm


def initialize(context):
    context.asset = symbol('btc_usdt')


def handle_data(context, data):
    data.history(context.asset, ['close'], bar_count=100, frequency='5m')


def analyze(context=None, results=None):
    pass


if __name__ == '__main__':
    run_algorithm(
        capital_base=100,
        initialize=initialize,
        handle_data=handle_data,
        analyze=analyze,
        exchange_name='bittrex',
        algo_namespace="bittrex_is_broken",
        base_currency='usdt',
        data_frequency='minute',
        simulate_orders=True,
        live=True)
```

And here's the error again:
```
$ python project/broken.py                                                                                                                                          *[master] 
[2017-12-26 15:11:10.009452] INFO: run_algo: running algo in paper-trading mode
[2017-12-26 15:11:10.411245] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2017-12-26 14:27:20.799999+00:00.
[2017-12-26 15:11:10.414022] INFO: exchange_algorithm: initialized trading algorithm in live mode
[2017-12-26 15:11:10.518423] INFO: exchange_algorithm: got totals from exchanges, cash: 100.0 positions: 0.0
Traceback (most recent call last):
  File "project/broken.py", line 28, in <module>
    live=True)
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 573, in run_algorithm
    stats_output=stats_output
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 356, in _run
    overwrite_sim_params=False,
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 666, in handle_data
    self._handle_data(self, data)
  File "project/broken.py", line 10, in handle_data
    data.history(context.asset, ['close'], bar_count=100, frequency='5m')
  File "catalyst/_protocol.pyx", line 120, in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call
  File "catalyst/_protocol.pyx", line 679, in catalyst._protocol.BarData.history
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_data_portal.py", line 114, in get_history_window
    ffill)
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_data_portal.py", line 73, in _get_history_window
    ffill)
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_data_portal.py", line 248, in get_exchange_history_window
    False)
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange.py", line 526, in get_history_window
    last_traded = asset_series.index[-1]
  File "/home/anaconda3/envs/catalyst/lib/python2.7/site-packages/pandas/tseries/base.py", line 251, in __getitem__
    val = getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by fredfortier** [comment]
Will take a look. Im the meanwhile, try 5T instead of 5m, we’re using
Pandas offset alias to designate frequency. Try passing ‘close’ as a string
instead of a list.

**Comment by caioaao** [comment]
@fredfortier tried both suggestions and got the same error.

**Comment by fredfortier** [comment]
Ok thanks. We will resolve ASAP.

**Comment by caioaao** [comment]
From my debug, after instantiating the `CCXT` class, this is what I get with `get_candles.get_candles('5m', ["btc_usdt"], bar_count=10)`:
```
{'btc_usdt': [{'high': 0, 'volume': 0, 'low': 0, 'close': 0, 'open': 0, 'last_traded': Timestamp('1970-01-01 00:00:00+0000', tz='UTC')}]}
```

running `ccxt.api.get_ohlcv(symbol="BTC/USDT", timeframe='5m', limit=10)` returns this:
```
[[0, 0, 0, 0, 0, 0]]
```

maybe a bug/misuse of ccxt api?

**Comment by caioaao** [comment]
@fredfortier I'm sorry, changing to `5T` worked. there was a place I was calling it and missed.
