### ISSUE TITLE
Can't run paper trading mode on develop branch

### ISSUE THREAD

**Issue by caioaao** [enigmampc/catalyst#124]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

Dockerized env (based on [this Dockerfile](https://gist.github.com/caioaao/8f091b5a9050216577e80900916bdefe)) with develop branch installed.

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Here's the stacktrace:
```
[2017-12-31 06:46:49.535618] INFO: run_algo: running algo in paper-trading mode
Exception in thread Thread-1:
Traceback (most recent call last):
  File "bot.py", line 59, in _run
    self.last_perf = run_algorithm(**run_args)
  File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/run_algo.py", line 577, in run_algorithm
    stats_output=stats_output
  File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/run_algo.py", line 177, in _run
    asset_db_path=None  # We don't need an asset db, we have exchanges
  File "/usr/local/lib/python2.7/dist-packages/catalyst/finance/trading.py", line 101, in __init__
    self.bm_symbol,
  File "/usr/local/lib/python2.7/dist-packages/catalyst/data/loader.py", line 150, in load_crypto_market_data
    benchmark_asset = exchange.get_asset(bm_symbol)
  File "/usr/local/lib/python2.7/dist-packages/catalyst/exchange/exchange.py", line 242, in get_asset
    for a in self.assets:
AttributeError: 'CCXT' object has no attribute 'assets'
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

Run any algorithm in paper-trading mode.

## What steps have you taken to resolve this already?

From looking at the code, this is because `CCXT.init()` wasn't called. I didn't get when it should be called, though.

**Comment by fredfortier** [comment]
Will look into it tomorrow. We’re in the process of making changes in this
area. Sorry for the inconvenience.

**Comment by caioaao** [comment]
e9714cfb32aac087ffbead47ae6b353d2b8f0653 this looks like the commit that broke it.
