### ISSUE TITLE
Matplotlib is insisting on a python "framework", which conda doesn't satisfy

### ISSUE THREAD

**Issue by blackwatertepes** [enigmampc/catalyst#135]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Mac OS X 10.13.2
* Python Version: Python 2.7.13
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: `$ conda list`
```
# packages in environment at /usr/local/anaconda3/envs/catalyst:
#
alembic                   0.9.6                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.5.8                     <pip>
botocore                  1.8.22                    <pip>
Bottleneck                1.2.1                     <pip>
ccxt                      1.10.319                  <pip>
certifi                   2017.11.5                 <pip>
certifi                   2016.2.28                py27_0  
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.0                     <pip>
futures                   3.2.0                     <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
jmespath                  0.9.3                     <pip>
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2017.0.3                      0  
multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0  
openssl                   1.0.2l                        0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1  
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
python.app                1.2                      py27_4  
pytz                      2017.2                    <pip>
readline                  6.2                           2  
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     0.19.1              np113py27_0  
setuptools                36.4.0                   py27_1  
six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0  
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
wheel                     0.29.0                   py27_0  
zlib                      1.2.11                        0  
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I was trying to run an example from the examples directory.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

```
$ catalyst run -f ./examples/buy_and_hodl.py -x bitfinex --start 2017-1-1 --end 2017-12-31 -c usd --capital-base 1000 -o buy_btc_simple_out.pickle
Running in backtesting mode.
[2018-01-03 21:21:05.860167] INFO: run_algo: running algo in paper-trading mode
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/catalyst/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/__main__.py", line 102, in _
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/__main__.py", line 287, in run
    stats_output=None,
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 342, in _run
    'script': algotext,
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 282, in __init__
    super(ExchangeTradingAlgorithmBacktest, self).__init__(*args, **kwargs)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 65, in __init__
    super(ExchangeTradingAlgorithmBase, self).__init__(*args, **kwargs)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 376, in __init__
    exec_(code, self.namespace)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "./examples/buy_and_hodl.py", line 18, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/usr/local/anaconda3/envs/catalyst/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 19, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

## What steps have you taken to resolve this already?

I've tried installing the python.app library, as suggested by Matplotlib, and replace instance of python in the example, with pythonw. However, the issue seems to run a bit deeper.

Sincerely,
blackwatertepes

**Comment by lacabra** [comment]
Hi @blackwatertepes, I believe the issue you are experiencing is documented here: https://enigmampc.github.io/catalyst/install.html#macos-virtualenv-matplotlib
Try the solution above, and let us know if it solves your issue.

**Comment by blackwatertepes** [comment]
Thanks, lacabra. That solved it.

**Comment by lacabra** [comment]
The corresponding section of the documentation https://enigmampc.github.io/catalyst/install.html#macos-virtualenv-conda-matplotlib has been improved with the explicit mention of the actual error, so that it may come up in future searches on this particular error.
