### ISSUE TITLE
Receive an error when placing a live buy order on Binance.

### ISSUE THREAD

**Issue by brinew27** [enigmampc/catalyst#172]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: Python 2.7.13 :: Anaconda, Inc.
* Python Bitness: (Received an error while executing this command.
* How did you install Catalyst: Conda
* Python packages: `$ pip freeze` or `$ conda list`

alembic                   0.9.6                     <pip>
appdirs                   1.4.3                     <pip>
attrs                     17.4.0                    <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.5.9                     <pip>
botocore                  1.8.23                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h94faf87_0
ccxt                      1.10.774                  <pip>
certifi                   2016.2.28                py27_0
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
colorama                  0.3.9                     <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
dsltools                  0.2.6                     <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.6                     <pip>
funcsigs                  1.0.2                     <pip>
futures                   3.2.0                     <pip>
icc_rt                    2017.0.4             h97af966_0
idna                      2.6                       <pip>
intel-openmp              2018.0.0             hd92c6cd_8
intervaltree              2.1.0                     <pip>
jmespath                  0.9.3                     <pip>
Logbook                   0.12.5                    <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2018.0.1             h2108138_4
multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
nose                      1.3.7                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0           py27hfef472a_0
openssl                   1.0.2l            vc9hb274bc6_5  [vc9]
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
parakeet                  0.23.2                    <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1
pluggy                    0.6.0                     <pip>
py                        1.5.2                     <pip>
pyparsing                 2.2.0                     <pip>
pytest                    3.3.2                     <pip>
python                    2.7.13              h1b6d89f_16
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytools                   2017.6                    <pip>
pytz                      2016.4                    <pip>
redo                      1.6                       <pip>
requests                  2.9.1                     <pip>
requests-file             1.4.1                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scikit-learn              0.19.1           py27he00e316_0
scipy                     1.0.0            py27h7cd1477_0
setuptools                36.4.0                   py27_1
six                       1.10.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                    vc9_1  [vc9]
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
TA-Lib                    0.4.14                    <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wheel                     0.29.0                   py27_0
wincertstore              0.2              py27hf04cefb_0
zlib                      1.2.11               hbc2faf4_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I am attempting to live trade on Binance using the USDT_ETH pair. I've been informed that the symbol in catalyst is "eth_usdt", so I am using "context.market = symbol('eth_usdt')". My intention with my code is to place a buy order for 95% of my capital base (100 USDT) for ETH, and to place it at a limit order of the price * 1.001. Here is my configuration:

```if __name__ == '__main__':
    # The execution mode: backtest or live
    live = True

    if live:
        run_algorithm(
            capital_base=100,
            initialize=initialize,
            handle_data=handle_data,
            analyze=analyze,
            exchange_name='binance',
            live=True,
            algo_namespace=NAMESPACE,
            base_currency='usdt',
            live_graph=False,
            simulate_orders=False,
            stats_output=None,
        )
```

I am running this function to place a buy order:

```order_target_percent(
                context.market, .95, limit_price = (price * 1.01)
            )
```

Here is my stacktrace:

```[2018-01-19 05:14:49.210000] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-01-19 05:14:52.211000] INFO: run_algo: running algo in live-trading mode
[2018-01-19 05:14:52.607000] INFO: exchange_bundle: pricing data for [u'btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-01-18 00:00:00+00:00, updating the bundles.
Ingesting daily price data for btc_usd on bitfinex
[2018-01-19 05:14:54.444000] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2018-01-19 04:17:07.375221+00:00.
[2018-01-19 05:14:54.450000] INFO: exchange_algorithm: initialized trading algorithm in live mode
[2018-01-19 05:14:55.268000] INFO: exchange_algorithm: portfolio balances, cash: 101.9508, positions: 0.0
C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[2018-01-19 05:14:59.760000] INFO: mean_reversion_simple: Pricerise: False, pos_amount: 0, Minute Count: 1, Price: 999.99
[2018-01-19 05:15:00.276000] INFO: mean_reversion_simple: 2018-01-19 05:14:00+00:00: buying - price: 999.99, rsi: 51.9578925264, reason: None
[2018-01-19 05:15:00.770000] INFO: CCXT: adjusted order amount 9.50009500095e-06 to 0.0 based on lot size
Traceback (most recent call last):
  File "Z:/Users/Brian/Google Drive/Catalyst/mean_reversion_simple.py", line 612, in <module>
    stats_output=None,
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 537, in run_algorithm
    stats_output=stats_output
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 316, in _run
    overwrite_sim_params=False,
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 297, in run
    data, overwrite_sim_params
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\events.py", line 216, in handle_data
    dt,
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\events.py", line 235, in handle_data
    self.callback(context, data)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 751, in handle_data
    self._handle_data(self, data)
  File "Z:/Users/Brian/Google Drive/Catalyst/mean_reversion_simple.py", line 243, in handle_data
    context.market, .95, limit_price = (price * 1.01)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\api_support.py", line 57, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\api_support.py", line 126, in wrapped_method
    return method(self, *args, **kwargs)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 2055, in order_target_percent
    style=style)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\api_support.py", line 126, in wrapped_method
    return method(self, *args, **kwargs)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 1462, in order
    return self.blotter.order(asset, amount, style)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_blotter.py", line 169, in order
    if amount == 0:
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_blotter.py", line 185, in order
    args=(asset, amount, style),
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\redo\__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_blotter.py", line 163, in exchange_order
    asset, amount, style
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange.py", line 822, in order
    return self.create_order(asset, amount, is_buy, style)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\ccxt\ccxt_exchange.py", line 779, in create_order
    e='order amount lower than the smallest lot: {}'.format(amount)
catalyst.exchange.exchange_errors.CreateOrderError: <exception str() failed>

Process finished with exit code 1
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Use the configuration above and place an order using my code.
2. I am able to submit my full code file if needed.
...

## What steps have you taken to resolve this already?

I was also having issues submitting this order with this currency pair on Poloniex, but that was because I was getting CCXT error when setting the base currency to usdt, it would only run with eth, but Poloniex would reject eth as the pair is USDT_ETH. With Binance I was getting the same error with version 0.4.3 of Catalyst, but a different stack trace, though same reported behavior of trying to buy an incredibly small amount and it converting to 0. I thought it was related to the reported issue of Binance reporting wrong price values for orders. I have since upgraded to 0.4.6 and am still having the issue.
...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by fredfortier** [comment]
I think that you may need to clear the state of your algorithm: ‘catalyst
clean-algo -n algo_namespace’. The state does keep info about your
currency. Then make sure that the ´base_currency’ is correct on restart.

**Comment by brinew27** [comment]
This (or something in the interim) seems to have resolved the issue, so it seems this diagnosis made sense (that currency info from something previous was bleeding over. Thank you.
