### ISSUE TITLE
buy_btc_simple.py  - syntax error

### ISSUE THREAD

**Issue by garichd** [enigmampc/catalyst#193]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

Miniconda on windows 2008 server

* Operating System: windows 2008 r2
* Python Version: `2.7`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`used manual install as per the guide ( troubleshooting install) )`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
Trying to run backtest for the forst time, Ingested minute data and followed the beginners tutorial.
* What happened instead?
buy_btc_simple.py  - syntax error

(catalyst) C:\xxxxxxxxxxx>catalyst run -f buy_btc_simple.py -x bitfinex --start 2017-8-1 --end 2017-9-30 -c usd --capital-base 100000 -o buy_btc_simple_out.pickle
Running in backtesting mode.
[2018-01-27 14:31:07.212000] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-01-27 14:31:10.213000] INFO: run_algo: running algo in backtest mode
Traceback (most recent call last):
  File "c:\programdata\miniconda2\envs\catalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\programdata\miniconda2\envs\catalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Miniconda2\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 102, in _
    return f(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 289, in run
    stats_output=None,
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 326, in _run
    'script': algotext,
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 303, in __init__
    super(ExchangeTradingAlgorithmBacktest, self).__init__(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 65, in __init__
    super(ExchangeTradingAlgorithmBase, self).__init__(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 375, in __init__
    code = compile(self.algoscript, filename, 'exec')
  File "buy_btc_simple.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by lacabra** [comment]
Hi @garichd, can you please copy/paste the actual code you're trying to run? It's hard to troubleshoot without seeing the actual code, when the error above throws an error on an empty line.
Is it possible that you have modified a line? or missing a close parenthesis in the previous line?

**Comment by garichd** [comment]
it seems there is error in code from example folder . 
https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/buy_btc_simple.py

I copied the code from tutorial and it worked .

**Comment by garichd** [comment]
actual code : 
from catalyst import run_algorithm 
25 from catalyst.api import order, record, symbol 
26 import pandas as pd 
27 
28 
29 def initialize(context): 
30     context.asset = symbol('btc_usd') 
31 
32 
33 def handle_data(context, data): 
34     order(context.asset, 1) 
35     record(btc=data.current(context.asset, 'price')) 
36 
37 
38 if __name__ == '__main__': 
39     run_algorithm( 
40         capital_base=10000, 
41         data_frequency='daily', 
42         initialize=initialize, 
43         handle_data=handle_data, 
44         exchange_name='bitfinex ', 
45         algo_namespace='buy_and_hodl', 
46         base_currency='usd', 
47         start=pd.to_datetime('2015-03-01', utc=True), 
48         end=pd.to_datetime('2017-10-31', utc=True), 
49     )

**Comment by garichd** [comment]
Ok, Sorted , This is probably copy paste error in chrome.

When I copied the code from git, it copied the line numbers for some reason, so code was invalid.

However on another computer , When I copied the same code from git ( using chrome) , line numbers were not selected or copied across.!
