### ISSUE TITLE
Running multiple live coins

### ISSUE THREAD

**Issue by Ericxgao** [enigmampc/catalyst#196]
I'm running multiple live trading sessions and wanted to know when the pricing data for btc_usd needed to be pulled.

If I have 40 coins trading and all of them try to ingest that daily data, I run into an ccxt.base.errors.DDoSProtection: bitfinex ERR_RATE_LIMIT error - how can I work around this?

I am staggering the initialization of each algorithm, but I'm worried that after midnight they will all trigger this call again and kill the algo.

**Comment by fredfortier** [comment]
We're pulling the benchmark data from Bitfinex as a temporary solution.
While it seem innocuous at first, several people reported issues like this
one. We'll fix this shortly to replace by a solution which executes without
querying an exchange. We will have this ready in a few days which should
allow you to drop your workaround.

**Comment by fredfortier** [comment]
Included this in our next milestone.

**Comment by salihkilic** [comment]
Pulling live data from the "Simple Universe" example in the docs also results in the following error:

```
Traceback (most recent call last):
  File "C:\Users\[my_username]\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 356, in fetch
    response.raise_for_status()
  File "C:\Users\[my_username]\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.bitfinex.com/v2/candles/trade:15m:tSNGETH/hist?sort=1&limit=202&start=1521477780000
```

**Comment by lenak25** [comment]
@Ericxgao , just to make sure I understand you correctly: you reach the rate limit due to the downloaded benchmark data or because you are trading many coins live in Bitfinex?
@salihkilic , thanks for this update, we are aware that currently there is a problem in running the "simple universe" example in live mode in Bitfinex, due to their low rate limit. We plan to introduce some improvements to the way data is retrieved to better handle this. In the meantime, you can use the other exchanges for this purpose.

**Comment by salihkilic** [comment]
@lenak25 I haven't been able to make it work even though I saw other people being able to and I found out what my problem is.

You can feed data.history() a list of coins. So when I do the following:

```
data.history(context.coins,
                                             ['open', 'high', 'low', 'price', 'volume'],
                                             bar_count=lookback,
                                             frequency=str(minutes) + 'T')
```
I hit the rate limit automatically, while retrieving the same data in a for loop doesn't. Like the following:

```
for coin in context.coins:
    data.history(context.coins,
                                                 ['open', 'high', 'low', 'price', 'volume'],
                                                 bar_count=lookback,
                                                 frequency=str(minutes) + 'T')
```
Example one is much easier and works perfectly fine in backtesting, just not live.

**Comment by lenak25** [comment]
Thanks for the feedback @salihkilic , we will check this.
Regarding the declaration of the history function, it is located at the Cython `_protocol.pyx` file, which in turn calls the `get_history_window` function of the `DataPortalExchange` class (exchange_data_portal.py) .

**Comment by salihkilic** [comment]
I've been trying a couple of things the last two hours and it makes even less sense to me now. Right now bitfinex is giving me DDoS alerts when I download requests 4 bars long @ 15T for 4 assets. I have absolutely no clue what is happening anymore. Does anyone have an example using multiple assets that works?

```
['agi_usd', 'aid_usd', 'aio_usd', 'ant_usd', 'avt_usd', 'bat_usd', 'bch_usd', 'bci_usd', 'bft_usd', 'btc_usd', 'btg_usd', 'cfi_usd', 'dai_usd', 'dat_usd', 'dsh_usd', 'dth_usd', 'edo_usd']

data.history(a_list_of_coins,
                                     ['open', 'high', 'low', 'price', 'volume'],
                                     bar_count=10,
                                     frequency='15T')
```

^ How do I get this to work?

**Comment by lenak25** [comment]
@salihkilic , as mentioned, Bitfinex has a very low rate limit, meaning it can be challenging to perform many requests to this exchange each frame. 
When trying to assess the number of requests performed, you should take into consideration the following: 
1. A different request is sent per each asset
2. At the current implementation: a different request is sent per each field - we plan to fix it ASAP. 
If you need more help in trying to understand the behavior of your algorithm, you can attach the code implementing the candles fetch.

**Comment by salihkilic** [comment]
@lenak25 Oh wow! That second point shines some light on what's happening! Thanks for the reply! I'll take a look if I can use CCXT directly for candle requests in a smarter/lightweight manner in the meantime.

**Comment by kooomix** [comment]
Can you tell what is the requests frequency allowed for an asset per field?
