### ISSUE TITLE
How does Catalyst calculate the capital_base? capital_base = 1000, it becomes 511.94378394

### ISSUE THREAD

**Issue by Hooker41** [enigmampc/catalyst#198]
Hello Catalyst Maintainers.

I'm running BuyLowandSellHigh algorithm in live mode

**# Capital_base is 1000**

[2018-01-31 02:24:52.166202] INFO: Loader: Cache at /home/ubuntu/.catalyst/data/treasury_curves.csv does not have data from 1990-01-02 00:00:00+00:00 to 2018-01-30 00:00:00+00:00.
[2018-01-31 02:24:52.166500] INFO: Loader: Downloading treasury data for 'btc_usd'.
[2018-01-31 02:24:52.914407] WARNING: Loader: Still don't have expected data after redownload!
[2018-01-31 02:24:52.917983] INFO: exchange_algorithm: initialized trading algorithm in live mode
[2018-01-31 02:24:53.959906] INFO: buy low sell high: initializing algo
[2018-01-31 02:24:54.307489] INFO: exchange_algorithm: portfolio balances, cash: 1047.80503462, positions: 0.0
[2018-01-31 02:24:54.307758] INFO: buy low sell high: handling bar 2018-01-31 02:24:00+00:00
[2018-01-31 02:24:54.774680] INFO: buy low sell high: got price 10044.61
[2018-01-31 02:24:55.303092] INFO: buy low sell high: got rsi: 54.2118128242
[2018-01-31 02:24:55.303361] INFO: buy low sell high: base currency available: 1000.0
[2018-01-31 02:24:55.303608] INFO: buy low sell high: current orders1: defaultdict(<type 'list'>, {})
[2018-01-31 02:24:55.303773] INFO: buy low sell high: current orders len: 0
[2018-01-31 02:24:55.303937] INFO: buy low sell high: buying position cheaper than cost basis 10044.61 < None
[2018-01-31 02:24:55.304207] INFO: buy low sell high: buy_increment: 0.2
[2018-01-31 02:24:55.304456] INFO: CCXT: adjusted order amount 0.0199111762428 to 0.01991 based on lot size
[2018-01-31 02:24:55.787551] INFO: buy low sell high: current orders2: defaultdict(<type 'list'>, {Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None: [Order({'status': 0, 'created': Timestamp('2018-01-31 02:24:55.787192+0000', tz='UTC'), 'limit_reached': False, 'stop': None, 'amount': 0.01991, 'stop_reached': False, 'commission': 0, 'reason': None, 'limit': 10064.69922, 'sid': Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None, 'dt': Timestamp('2018-01-31 02:24:55.787192+0000', tz='UTC'), 'id': '32009084', 'filled': 0})]})
[2018-01-31 02:24:55.787786] INFO: buy low sell high: current orders len: 1
[2018-01-31 02:24:55.787970] INFO: buy low sell high: base currency after order: 1000.0
[2018-01-31 02:24:55.788136] INFO: buy low sell high: completed bar 2018-01-31 02:24:00+00:00, total execution errors 0
[2018-01-31 02:24:55.808052] INFO: exchange_algorithm: statistics for the last 1 minutes:
                           starting_cash  ending_cash  portfolio_value  pnl  long_exposure  short_exposure  orders  transactions     price          rsi
period_close
2018-01-31 02:25:00+00:00           1000       **# 1000.0**           1000.0  0.0              0               0       0             0  10044.61  54.21181282
[2018-01-31 02:25:01.004724] INFO: exchange_blotter: filled order 32009084 / btc_usdt: 0.01991, avg price: 10044.45
[2018-01-31 02:25:01.995942] INFO: exchange_algorithm: portfolio balances, cash: 847.82003512, positions: 199.5629075
[2018-01-31 02:25:01.996193] INFO: buy low sell high: handling bar 2018-01-31 02:25:00+00:00
[2018-01-31 02:25:02.496764] INFO: buy low sell high: got price 10023.25
[2018-01-31 02:25:03.032974] INFO: buy low sell high: got rsi: 54.2116255514
[2018-01-31 02:25:03.033266] INFO: buy low sell high: base currency available: 800.0150005
[2018-01-31 02:25:03.033452] INFO: buy low sell high: current orders1: defaultdict(<type 'list'>, {})
[2018-01-31 02:25:03.033607] INFO: buy low sell high: current orders len: 0
[2018-01-31 02:25:03.033901] INFO: buy low sell high: got position: Position({'last_sale_date': Timestamp('2018-01-31 02:25:01.878000+0000', tz='UTC'), 'amount': 0.01991, 'last_sale_price': 10023.25, 'asset': Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None, 'cost_basis': 10044.45})
[2018-01-31 02:25:03.034088] INFO: buy low sell high: found 0.01991 positions with cost basis 10044.45
[2018-01-31 02:25:03.034218] INFO: buy low sell high: buying position cheaper than cost basis 10023.25 < 10044.45
[2018-01-31 02:25:03.034461] INFO: buy low sell high: buy_increment: 0.2
[2018-01-31 02:25:03.034705] INFO: CCXT: adjusted order amount 0.0159631856035 to 0.015962 based on lot size
[2018-01-31 02:25:03.501452] INFO: buy low sell high: current orders2: defaultdict(<type 'list'>, {Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None: [Order({'status': 0, 'created': Timestamp('2018-01-31 02:25:03.501117+0000', tz='UTC'), 'limit_reached': False, 'stop': None, 'amount': 0.015962, 'stop_reached': False, 'commission': 0, 'reason': None, 'limit': 10043.2965, 'sid': Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None, 'dt': Timestamp('2018-01-31 02:25:03.501117+0000', tz='UTC'), 'id': '32009180', 'filled': 0})]})
[2018-01-31 02:25:03.501693] INFO: buy low sell high: current orders len: 1
[2018-01-31 02:25:03.501894] INFO: buy low sell high: base currency after order: 800.0150005
[2018-01-31 02:25:03.502097] INFO: buy low sell high: completed bar 2018-01-31 02:25:00+00:00, total execution errors 0
[2018-01-31 02:25:03.530645] INFO: exchange_algorithm: statistics for the last 1 minutes:
                                                                                                                                                       symbol   amount  cost_basis  last_sale_price
period_close              starting_cash ending_cash portfolio_value pnl       long_exposure short_exposure orders transactions price    rsi
2018-01-31 02:26:00+00:00 1000          **# 800.0150005** 999.577908      -0.422092 199.5629075   0              1      1            10023.25 54.21162555  btc_usdt  0.01991    10044.45         10023.25
[2018-01-31 02:26:00.823251] INFO: exchange_blotter: filled order 32009180 / btc_usdt: 0.015962, avg price: 10039.612843
[2018-01-31 02:26:01.807219] INFO: exchange_algorithm: portfolio balances, cash: 687.56773492, positions: 360.190752
[2018-01-31 02:26:01.807467] INFO: buy low sell high: handling bar 2018-01-31 02:26:00+00:00
[2018-01-31 02:26:02.307324] INFO: buy low sell high: got price 10041.0
[2018-01-31 02:26:02.840640] INFO: buy low sell high: got rsi: 54.2087400109
[2018-01-31 02:26:02.840954] INFO: buy low sell high: base currency available: 639.7627003
[2018-01-31 02:26:02.841133] INFO: buy low sell high: current orders1: defaultdict(<type 'list'>, {})
[2018-01-31 02:26:02.841283] INFO: buy low sell high: current orders len: 0
[2018-01-31 02:26:02.841564] INFO: buy low sell high: got position: Position({'last_sale_date': Timestamp('2018-01-31 02:26:00.416000+0000', tz='UTC'), 'amount': 0.035872, 'last_sale_price': 10041.0, 'asset': Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None, 'cost_basis': 10042.297605374664})
[2018-01-31 02:26:02.841726] INFO: buy low sell high: found 0.035872 positions with cost basis 10042.2976054
[2018-01-31 02:26:02.841855] INFO: buy low sell high: buying position cheaper than cost basis 10041.0 < 10042.2976054
[2018-01-31 02:26:02.842102] INFO: buy low sell high: buy_increment: 0.2
[2018-01-31 02:26:02.842348] INFO: CCXT: adjusted order amount 0.0127430076745 to 0.012743 based on lot size
[2018-01-31 02:26:13.148346] WARNING: CCXT: unable to create order binance / BTC/USDT: binance POST https://api.binance.com/api/v3/order request timeout
[2018-01-31 02:26:13.148881] WARNING: exchange_blotter: Ordering again.
[2018-01-31 02:26:18.154329] INFO: CCXT: adjusted order amount 0.0127430076745 to 0.012743 based on lot size
[2018-01-31 02:26:18.865707] INFO: buy low sell high: current orders2: defaultdict(<type 'list'>, {Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None: [Order({'status': 0, 'created': Timestamp('2018-01-31 02:26:18.865374+0000', tz='UTC'), 'limit_reached': False, 'stop': None, 'amount': 0.012743, 'stop_reached': False, 'commission': 0, 'reason': None, 'limit': 10061.082, 'sid': Trading Pair btc_usdt(374465) Exchange: binance, Introduced On: 2009-01-01 00:00:00+00:00, Base Currency: btc, Quote Currency: usdt, Exchange Leverage: 1.0, Minimum Trade Size: 9.99999997475e-07 Last daily ingestion: None Last minutely ingestion: None, 'dt': Timestamp('2018-01-31 02:26:18.865374+0000', tz='UTC'), 'id': '32009663', 'filled': 0})]})
[2018-01-31 02:26:18.865930] INFO: buy low sell high: current orders len: 1
[2018-01-31 02:26:18.866210] INFO: buy low sell high: base currency after order: 639.7627003
[2018-01-31 02:26:18.866391] INFO: buy low sell high: completed bar 2018-01-31 02:26:00+00:00, total execution errors 0
[2018-01-31 02:26:18.894231] INFO: exchange_algorithm: statistics for the last 1 minutes:
                                                                                                                                                       symbol    amount      cost_basis  last_sale_price
period_close              starting_cash ending_cash portfolio_value pnl        long_exposure short_exposure orders transactions price   rsi
2018-01-31 02:27:00+00:00 1000          **# 639.7627003** 999.9534523     -0.0465477 360.190752    0              1      3            10041.0 54.20874001  btc_usdt  0.035872  10042.29760537          10041.0
[2018-01-31 02:27:04.197090] INFO: exchange_blotter: filled order 32009663 / btc_usdt: 0.012743, avg price: 10030.52
Traceback (most recent call last):
  File "blash.py", line 185, in <module>
    simulate_orders=False,
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 551, in run_algorithm
    stats_output=stats_output
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 330, in _run
    overwrite_sim_params=False,
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 297, in run
    data, overwrite_sim_params
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 741, in handle_data
    cleanup=lambda: log.warn('Ordering again.')
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/redo/__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 606, in synchronize_portfolio
    cash=required_cash,
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange.py", line 700, in sync_positions
    cash=cash,
catalyst.exchange.exchange_errors.NotEnoughCashError: **# Total usdt amount on binance is lower than the cash reserved for this algo: 431.79635556 < 511.94378394.** While trades can be made on the exchange accounts outside of the algo, exchange must have enough free usdt to cover the algo cash.
(catalyst) ubuntu@ip-172-31-41-166:~/binance$ python blash.py
Traceback (most recent call last):
  File "blash.py", line 184, in <module>
    simulate_orders=False,
  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 494, in run_algorithm
    'Please specify a `capital_base` parameter which is the maximum '
ValueError: Please specify a `capital_base` parameter which is the maximum amount of base currency available for trading. For example, if the `capital_base` is 5ETH, the `order_target_percent(asset, 1)` command will order 5ETH worth of the specified asset.
(catalyst) ubuntu@ip-172-31-41-166:~/binance$ Connection reset by 18.219.18.255 port 22

**Comment by Hooker41** [comment]
I set capital_base = 1000

My USD balance on Binance is 1047.
So my bot placed 3 orders.

After that, this issue occurred.
I want to avoid this issue with python code

# **Total usdt amount on binance is lower than the cash reserved for this algo: 431.79635556 < 511.94378394**

**Comment by fredfortier** [comment]
Did you place any orders outside of the algo? The algo tries to ensure that
the cash available on the exchange is always higher or equal to the cash
balance tracked by the algorithm.

**Comment by Hooker41** [comment]
Thanks for your reply.

order(
            asset=context.asset,
            amount=buy_increment * (cash / price),
            limit_price=price * (1 + context.SLIPPAGE_ALLOWED)
        )

This is my order script in buylowandsellhigh.py

This script place cash worth of btc on Binance btc_usdt market.

I only placed orders via this script.

**Comment by Hooker41** [comment]
How does the algo track cash balance?

**Comment by fredfortier** [comment]
It keeps track of cash by subtracting the executed price of each buy order
to the capital base, and adding up the sell orders. We'll try to place some
btc_usdt orders on Binance to see if we can replicate this. Issue #178
relates to usdt markets on Binance and might contribute to this imbalance.

**Comment by Hooker41** [comment]
Thanks, Fred.

Is there a variable to check the current capital_base(511.9437)?

**Comment by fredfortier** [comment]
`capital_base` is a static value. You set it when starting your algo and it never changes. What fluctuates is your cash. You can check it using `context.portfolio.cash`.

**Comment by Hooker41** [comment]
Yes.

I can check the capital_base with context.portfolio.cash.

But one problem.
I've started the cash with 1047.80503462.
and set the capital_base = 1000

then why did this happen?
## Total usdt amount on binance is lower than the cash reserved for this algo: 431.79635556 < 511.94378394.

I think the balance will be always bigger than the capital_base amount.

**Comment by fredfortier** [comment]
When you enter a position, your cash decrease as the amount of that position increases. You portfolio value and p/l are calculated by adding your cash to the total value of your positions. So I don't see anything abnormal with your cash being 511 < 1000. 

The problem that I see is that your cash was somehow miscalculated. If you only ordered through the algo, you would have executed 616 worth of orders which the algo thinks that is around 489. I speculate that this may be related to #178 but I'd like to reproduce this to know for sure. I'm currently running several live algos including one against Binance and everything seems to add up. I'll switch to trading btc_usdt shortly to match your conditions as closely as possible.

In the meantime, it it's not too inconvenient for you, posting the three orders in question might be helpful. Here is a Binance screenshot to give you an idea of what I'm looking for.
<img width="744" alt="screenshot 2018-01-31 20 20 31" src="https://user-images.githubusercontent.com/1474114/35656239-3d649b9a-06c4-11e8-972c-89f5c2b168fd.png">

Otherwise, I'll keep running transactions until I can replicate the issue or build enough confidence that fixing #178 resolve it.

**Comment by fredfortier** [comment]
After troubleshooting #178 further, I'm fairly confident that the same condition was responsible for this issue. Running more tests before pushing a release.

**Comment by fredfortier** [comment]
Here is what a clean log looks like on my side:
```
[2018-02-01 04:37:43.271458] INFO: mean_reversion_risk: 2018-02-01 04:37:00+00:00: buying - price: 0.00540021, rsi: 31.724827115
[2018-02-01 04:37:44.293394] INFO: CCXT: order amount adjusted by binance from 37.03559676 to 37.0
```
Then in the next frame:
```
[2018-02-01 04:38:00.258216] INFO: exchange_blotter: filled order 7641440 / ven_eth: 37.0, avg price: 0.00540184189189
```

I processed multiple transactions but I'll let it run overnight before releasing just to be sure that the sample is sufficient.

**Comment by Hooker41** [comment]
Looks Good.
Thanks for your hard work.

**Comment by fredfortier** [comment]
In release 0.5.2
