### ISSUE TITLE
Live client occasionally fails with IndexError

### ISSUE THREAD

**Issue by Ericxgao** [enigmampc/catalyst#208]
Currently, I will restart the algorithm if it catches an exception - but sometimes restarting it without cleaning the algorithm will cause the following error to appear:

    Traceback (most recent call last):
      File "binance_catalyst_live_limit.py", line 229, in run
        simulate_orders=False
      File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/run_algo.py", line 551, in run_algorithm
        stats_output=stats_output
      File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/run_algo.py", line 238, in _run
        data_frequency='minute'
      File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/factory.py", line 70, in create_simulation_parameters
        trading_calendar=trading_calendar,
      File "/usr/local/lib/python2.7/dist-packages/catalyst/finance/trading.py", line 178, in __init__
        self._end_session, direction="previous"
      File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/calendars/trading_calendar.py", line 742, in minute_to_session_label
        Given a minute, get the label of its containing session.
      File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/calendars/trading_calendar.py", line 771, in minute_to_session_label
        current_or_next_session = self.schedule.index[idx]
      File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/base.py", line 251, in __getitem__
        val = getitem(key)
    IndexError: index 1436 is out of bounds for axis 0 with size 1436
    index 1436 is out of bounds for axis 0 with size 1436

**Comment by fredfortier** [comment]
@Ericxgao this is a tough one. I have live algos running for several days so I don't believe that it is a systematic issue. But I know that you are using a lot of market so there must be some edge case which I did not encounter. Any additional contextual info that you could offer would be useful. Otherwise, we're working on adding a large number of markets to our tests.

**Comment by Ericxgao** [comment]
@fredfortier 

Pretty significant is that I'm multithreading it. I actually completely stopped using any of Enigma's data fetching tools in favor of CCXT or directly accessing Binance's API - there might be race conditions I'm not seeing under the hood if you are using a single CCXT exchange object.

For the time being I've completely just given up on logging performance and have made my own version of enigma disabling balance synchronization.

At this point, I think my use case might be a little ahead of what enigma is capable of - state saving doesn't seem to work either so I've written my own methods of doing so.

**Comment by Ericxgao** [comment]
Actually, it's worth noting that I was able to get this issue while running it on just one coin, on a single thread as well. I've written my own recovery code to clean the algo when it happens, which seems like the only way for it to be fixed.

**Comment by fredfortier** [comment]
Okay, it makes sense. Multithreading is something which we haven't tested yet. I can see how it could interfere with the state. Feel free to describe your use case for the multiple threads if you want, we can try to get to there relatively soon.

**Comment by Ericxgao** [comment]
Running separate processes takes up around 160 MB of RAM per process - I tried multithreading it to try to reduce that overhead since I'm cheaping out on my server - that's all. Just want to run more coins with lower RAM usage.

**Comment by fredfortier** [comment]
Okay, I see. So you are basically running the same strategy with a large
number of coin in parallel? Or, are you trying to fetch the price data and
compute TA for multiple markets in parallel, then consolidating the threads
and placing your orders where you found signals? We can try to facilitate
the latter soon as we can since it is not inherently difficult. The
challenge with the former would be to consolidate the performance stats.

**Comment by Ericxgao** [comment]
Same strategy with a large number of coins - but the latter case would have the same results if I understand correctly.

**Comment by fredfortier** [comment]
Yes, I'll try creating a sample strategy with the second method and see how it goes. We'll get back to you when we have something fully tested.

**Comment by lacabra** [comment]
@Ericxgao to one of your points above, we recently included the functionality to save whatever you need to preserve from the state (a dict that can hold anything) under `context.state` between runs. Documentation needs to catch up with it as per #224.
