### ISSUE TITLE
v0.4.7 Algo paper trading initiation error

### ISSUE THREAD

**Issue by frisitano** [enigmampc/catalyst#213]
Hi,

I have just updated to v0.4.7 and am now experiencing an issue when initiating my paper trading algo.  The algo is initiated with the following code:

if __name__ == '__main__':
    start_date = pd.to_datetime('2017-01-01', utc=True)
    end_date = pd.to_datetime('2017-12-31', utc=True)

    performance = run_algorithm(start=start_date, end=end_date,
                                capital_base=10000.0,  # amount of base_currency
                                initialize=initialize,
                                handle_data=handle_data,
                                analyze=analyze,
                                exchange_name='binance',
                                data_frequency='minute',
                                base_currency='eth',
                                live=True,
                                simulate_orders=True,
                                live_graph=False,
                                algo_namespace=NAMESPACE)  

The traceback is:
Traceback (most recent call last):
  File "simple_universe.py", line 306, in <module>
    algo_namespace=NAMESPACE)
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 551, in run_algorithm
    stats_output=stats_output
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 238, in _run
    data_frequency='minute'
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/factory.py", line 70, in create_simulation_parameters
    trading_calendar=trading_calendar,
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/finance/trading.py", line 145, in __init__
    "Period start falls after period end."
AssertionError: Period start falls after period end.

The algo works fine in v0.4.4.

Regards,
Francesco

**Comment by frisitano** [comment]
Changing start and end arguments, in the run_algorithm() call, to None such that we have:
run_algorithm(start=None, end=None, ...) fixes the issue.

**Comment by AvishaiW** [comment]
Hi, both live & paper trading handle live data, therefore, you are not suppose to enter a start_date because it gets the current date and starts simulating from there. if you are intrested in backtesting your algorithm between those dates, you need to change to backtest mode (live=False).

**Comment by frisitano** [comment]
I understand. It may be more user friendly if you avoided the evaluation of the start and end date when live=True.  That way switching from backtest mode to live mode can be done by simply changing live=False to live=True.

**Comment by AvishaiW** [comment]
thanks for noting it out. we will make the change ASAP.

**Comment by lacabra** [comment]
@frisitano this is by design, as at least end_date currently has a purpose in live trading, in that one can start a live algo now, and schedule it to finish gracefully in the future at a predefined time set in end_date. Similarly (and this is not implemented yet), one could set a start_date in the future in live mode and the algo would essentially sleep until that time comes, and start executing the algo in live mode. The parameters used in backtesting vs. live trading is covered in the documentation, and we feel there is a good reason to keep it this way. Thanks for the suggestion

**Comment by frisitano** [comment]
@lacabra yes makes sense to keep it. I didn't realise Catalyst had that functionality, good to know.
