### ISSUE TITLE
Error placing order after resuming state of algorithm

### ISSUE THREAD

**Issue by frisitano** [enigmampc/catalyst#214]
When placing an order after resuming the state of an algo, I receive the following error:

Traceback (most recent call last):
  File "simple_universe.py", line 306, in <module>
    algo_namespace=NAMESPACE)
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 551, in run_algorithm
    stats_output=stats_output
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 330, in _run
    overwrite_sim_params=False,
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 297, in run
    data, overwrite_sim_params
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 751, in handle_data
    self._handle_data(self, data)
  File "simple_universe.py", line 214, in handle_data
    place_orders(context, orders_df, context.filtered_coins, now)
  File "simple_universe.py", line 126, in place_orders
    order_target_percent(coin, 0)
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/api_support.py", line 57, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/api_support.py", line 126, in wrapped_method
    return method(self, *args, **kwargs)
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 2049, in order_target_percent
    if not self._can_order_asset(asset):
  File "/home/ubuntu/anaconda/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 1397, in _can_order_asset
    if day > min(asset.end_date, asset.auto_close_date):
  File "pandas/tslib.pyx", line 1103, in pandas.tslib._Timestamp.__richcmp__ (pandas/tslib.c:20491)
TypeError: Cannot compare type 'Timestamp' with type 'float'

The variable asset.auto_close_date is only set when resuming an algo and reloading its state.  It appears that asset.auto_close_date is a float which is causing the error.

**Comment by fredfortier** [comment]
We'll try to replicate this.

**Comment by AvishaiW** [comment]
Hi @frisitano, can you please add your list of packages? thanks.

**Comment by frisitano** [comment]
Hi @AvishaiW,

Sure here's my package list:

alembic (0.9.7)
backports.functools-lru-cache (1.4)
bcolz (0.12.1)
boto3 (1.5.24)
botocore (1.8.38)
Bottleneck (1.2.1)
ccxt (1.10.1027)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
contextlib2 (0.5.5)
cycler (0.10.0)
cyordereddict (1.0.0)
Cython (0.27.3)
decorator (4.2.1)
docutils (0.14)
empyrical (0.2.1)
enigma-catalyst (0.4.7)
futures (3.2.0)
idna (2.6)
intervaltree (2.1.0)
jmespath (0.9.3)
Logbook (1.1.0)
lru-dict (1.1.6)
lxml (4.1.1)
Mako (1.0.7)
MarkupSafe (1.0)
matplotlib (2.1.2)
multipledispatch (0.4.9)
networkx (2.1)
numexpr (2.6.4)
numpy (1.14.0)
pandas (0.19.2)
pandas-datareader (0.6.0)
patsy (0.5.0)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
python-editor (1.0.3)
pytz (2017.3)
redo (1.6)
requests (2.18.4)
requests-file (1.4.3)
requests-ftp (0.3.1)
s3transfer (0.1.12)
scipy (1.0.0)
setuptools (38.5.1)
six (1.11.0)
sortedcontainers (1.5.9)
SQLAlchemy (1.2.2)
statsmodels (0.8.0)
subprocess32 (3.2.7)
tables (3.4.2)
toolz (0.9.0)
urllib3 (1.22)
wheel (0.30.0)
wrapt (1.10.11)

**Comment by manelrovira** [comment]
This commit don't resolve de problem in my case.
It seems that when the context.positions array is initialized the created TradingPairs doesn't have correctly informed the end_date property. In my case it is initialized with the value 0.0025 and not whith a date.

**Comment by frisitano** [comment]
@manelrovira What version of Catalyst are you running? I'm running the latest version and the commit solves the problem.  I've just taken a look and the asset.end_date property is set to a year in the future of the current time.

**Comment by camanio** [comment]
I have the same bug too (catalyst 0.5.3). Now I totaly switching off this check and deals exucutes as usual (live mode at Bittrex).

**Comment by lenak25** [comment]
Hi everyone, could you please specify the exact procedure you are following so we can try to reproduce it? Thanks!

**Comment by AvishaiW** [comment]
@frisitano, @manelrovira & @camanio we are interested in fixing and closing this issue. are you still experiencing this error without the #215 commit (it modifies code that at the moment we prefer not to change)? if so, can you please add a bit more information on the issue, that we will be able to reproduce it? Thanks!

**Comment by camanio** [comment]
Hi, @AvishaiW ! I fixed this issue by switching off all checkings at file catalyst/algorithm.py (method _can_order_asset). Workaround looks like:

```
def _can_order_asset(self, asset):
         if not isinstance(asset, Asset):
             raise UnsupportedOrderParameters(
                 msg="Passing non-Asset argument to 'order()' is not supported."
                     " Use 'sid()' or 'symbol()' methods to look up an Asset."
              )
        return True
```
It's a hack, but it works for me.

**Comment by AvishaiW** [comment]
Hi, finally, I was able to fix this error. The state wasn't saved properly and therefore, `auto_close_date` got a `float` instead of `Timestamp/None`. pushed it into the develop branch. Please update if this works/doesn't work for you.
