### ISSUE TITLE
RuntimeWarning: overflow encountered in double_scalars

### ISSUE THREAD

**Issue by lacabra** [enigmampc/catalyst#223]
As reported by @brinew27 on issue #197:

@lacabra Thanks Victor! It does seem like it generated data for the missing days. I'm getting a weird error however at a certain part of the data for eth_usdt minute on poloniex it looks like on 12-07-2017. I was able to export 1-15-18 through 1-31-18 without issue. For right now I'll just skip this day, but wanted to report it in case there's an issue with the data at that point (and ideally I'd like my training data to extend back to there.

```
[2018-02-09 07:53:37.884000] INFO: symbol_export: 2017-12-07 20:56:00+00:00
Traceback (most recent call last):
  File "Z:/Users/Brian/Google Drive/Catalyst/symbol_export.py", line 185, in <module>
    capital_base=100
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 551, in run_algorithm
    stats_output=stats_output
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 330, in _run
    overwrite_sim_params=False,
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 352, in run
    data, overwrite_sim_params
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 309, in run
    data, overwrite_sim_params
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 243, in transform
    self._get_minute_message(dt, algo, algo.perf_tracker)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 303, in _get_minute_message
    dt, self.data_portal,
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\finance\performance\tracker.py", line 357, in handle_minute_close
    account.leverage)
  File "C:\Users\brian\Anaconda2\envs\catalyst\lib\site-packages\catalyst\finance\risk\cumulative.py", line 219, in update
    self.mean_benchmark_returns_cont[dt_loc] * 252
RuntimeWarning: overflow encountered in double_scalars
```

**Comment by lenak25** [comment]
@brinew27, are you still experiencing this issue?
