### ISSUE TITLE
Frequent timeouts

### ISSUE THREAD

**Issue by vonpupp** [enigmampc/catalyst#248]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (`Linux <hostname removed> 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux`)
* Python Version: `2.7.14`
* Python Bitness: `64`
* How did you install Catalyst: pip
* Python packages: `$ pip freeze`:
```
agate==1.6.0
agate-dbf==0.2.0
agate-excel==0.2.2
agate-sql==0.5.3
alembic==0.9.7
attrdict==2.0.0
Babel==2.5.3
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
bleach==2.1.2
boto3==1.5.30
botocore==1.8.44
Bottleneck==1.2.1
ccxt==1.10.1124
certifi==2018.1.18
chardet==3.0.4
click==6.7
configparser==3.5.0
contextlib2==0.5.5
csvkit==1.0.2
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0
dbfread==2.0.7
decorator==4.2.1
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.1+48.ga61857b3
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
eth-abi==1.0.0b0
eth-account==0.1.0a2
eth-keyfile==0.5.1
eth-keys==0.2.0b1
eth-rlp==0.1.0a2
eth-utils==1.0.0b1
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
haikunator==2.1.0
hexbytes==0.1.0b0
html5lib==1.0.1
idna==2.6
intervaltree==2.1.0
ipdb==0.11
ipykernel==4.8.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.2
isodate==0.6.0
jdcal==1.3
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
leather==0.3.3
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
mistune==0.8.3
multipledispatch==0.4.9
names==0.3.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
notebook==5.4.0
numexpr==2.6.4
numpy==1.14.0
openpyxl==2.5.0
pandas==0.19.2
pandas-datareader==0.6.0
pandocfilters==1.4.2
parsedatetime==2.4
pathlib2==2.3.0
patsy==0.5.0
petname==2.2
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pycryptodome==3.4.11
Pygments==2.2.0
pyparsing==2.2.0
pysha3==1.0.2
python-dateutil==2.6.1
python-editor==1.0.3
python-slugify==1.2.4
python-telegram-bot==9.0.0
pytimeparse==1.1.7
pytz==2018.3
pyzmq==17.0.0
qtconsole==4.3.1
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
s3transfer==0.1.13
scandir==1.7
scipy==1.0.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.16
tables==3.4.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==4.5.3
traitlets==4.3.2
transitions==0.6.2
Unidecode==1.0.22
urllib3==1.22
wcwidth==0.1.7
web3==4.0.0b9
webencodings==0.5.1
widgetsnbextension==3.1.4
wrapt==1.10.11
xlrd==1.1.0
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Frequent timeouts

When running in paper mode with minute data frequency, I resample the candles every 30 minutes. Quite often, when I resample the data I get the following error:

```
[2018-02-23 18:15:00.726740] WARNING: exchange_algorithm: unable save stats locally: 'plus_dm'
[2018-02-23 18:16:00.810781] INFO: exchange_algorithm: portfolio balances, cash: 1111.11, positions: 0.0
[2018-02-23 18:16:00.811479] INFO: d_papert_abba_adam: RESAMPLE 8/240: 2018-02-23 18:16:00+00:00
[2018-02-23 18:16:10.825476] INFO: d_papert_abba_adam: Exception on default_handle_data
Traceback (most recent call last):
  File "/home/av/repos/example/strategies/family/abba.py", line 209, in default_handle_data
    print_log(context, msg)
  File "catalyst/_protocol.pyx", line 120, in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call
    return func(*args, **kwargs)
  File "catalyst/_protocol.pyx", line 646, in catalyst._protocol.BarData.history
    df = self.data_portal.get_history_window(
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/exchange_data_portal.py", line 95, in get_history_window
    ffill))
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/redo/__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/exchange_data_portal.py", line 69, in _get_history_window
    ffill)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/exchange_data_portal.py", line 218, in get_exchange_history_
window
    False)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/exchange.py", line 511, in get_history_window
    end_dt=end_dt if not is_current else None,
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 456, in get_candles
    params={}
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/ccxt/binance.py", line 536, in fetch_ohlcv
    response = self.publicGetKlines(self.extend(request, params))
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/ccxt/base/exchange.py", line 310, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/ccxt/base/exchange.py", line 307, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/av/repos/example/.envc-unstable/local/lib/python2.7/site-packages/ccxt/base/exchange.py", line 365, in fetch
    raise RequestTimeout(' '.join([self.id, method, url, 'request timeout']))
RequestTimeout: binance GET https://api.binance.com/api/v1/klines?symbol=NEOUSDT&interval=30m&limit=48 request timeout
```

* I would expect that everything goes smoothly all the time
* Every now and then (quite often actually) I get a timeout error. This is not limited just to binance but also on other exchanges.

You may want to have a look at [this issue] on CCXT. You might want to allow the user to setup a timeout on Catalyst to be passed to CCXT. Perhaps even better is to export a CCXT interface to the Catalyst users so it is possible to modify internal properties/values.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Use paper mode
2. Do resample
3. Wait

I am working on a minimal example and will provide a gist link.

## What steps have you taken to resolve this already?

None. I think it is an architectural thing that I am not able to solve.

Sincerely,
V

**Comment by fredfortier** [comment]
Yes, we can include a setting which allows passes through to the exchange init options of CCXT. We'll look more specifically into timeout interval options.

For now, it looks like this issue occurs in the your `handle_data` implementation. This means that you have an opportunity to catch and retry.

We've implemented except...retry handlers in all internal components making requests to an exchange(when synchronizing balances for example). However, we have not done so for ad-hoc operations (like get_history). The rationale is that, since those calls occur in a user-defined function, users might want to control when to retry and when to abandon for the current frame.

Let us know if you think that the retry behavior should be built-in, or if you are simply looking for a way to set the timeout interval (assuming that exchanges accept such parameter).

**Comment by vonpupp** [comment]
Got it Fred, thank you very much.

I will try to catch that on my code and retry to get the history again and see how it goes, it makes sense. I think a way of setting the timeout would be nice.
