### ISSUE TITLE
ResolvePackageNotFound when trying to install catalyst in windows 10 

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#254]
Hi all,

I try to install catalyst on windows 10 following these instructions:
https://enigmampc.github.io/catalyst/install.html

I've been trying all the above options as well as directly through Anaconda Navigator, using the instructions file mentioned in the installation doc (https://github.com/enigmampc/catalyst/blob/master/etc/python3.6-environment.yml).

I keep getting an issue with ResolvePackageNotFound:

ResolvePackageNotFound: 
- readline=7.0
- libffi=3.2.1
- ncurses=6.0
- libedit=3.1
- libcxxabi=4.0.1
- libgfortran=3.0.1
- libcxx=4.0.1_

How can I overcome this issue using Anaconda Navigator?

Thanks!
Eran

**Comment by AvishaiW** [comment]
Hi @kooomix , Have you tried the troubleshooting https://enigmampc.github.io/catalyst/install.html#troubleshooting-conda-install?

**Comment by kooomix** [comment]
Yes, I have tried that and the installation part (step 4) ended up with the following error:

 Complete output from command python setup.py egg_info:
    C:\Users\username\Anaconda3\envs\catalyst\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
      warn=(impl == 'cp')):
    C:\Users\username\Anaconda3\envs\catalyst\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
      warn=(impl == 'cp')):
    C:\Users\username\Anaconda3\envs\catalyst\lib\site-packages\setuptools\pep425tags.py:99: RuntimeWarning: Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
      sys.version_info < (3, 3))) \
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__

    Installed c:\users\username\appdata\local\temp\pip-build-jmyu9h\hexbytes\.eggs\pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\username\appdata\local\temp\pip-build-jmyu9h\hexbytes\setup.py", line 67, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "C:\Users\username\Anaconda3\envs\catalyst\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\username\Anaconda3\envs\catalyst\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\username\Anaconda3\envs\catalyst\lib\site-packages\setuptools\dist.py", line 333, in __init__
        _Distribution.__init__(self, attrs)
      File "C:\Users\username\Anaconda3\envs\catalyst\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "C:\Users\username\Anaconda3\envs\catalyst\lib\site-packages\setuptools\dist.py", line 476, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\username\appdata\local\temp\pip-build-jmyu9h\hexbytes\.eggs\setuptools_markdown-0.2-py2.7.egg\setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "c:\users\username\appdata\local\temp\pip-build-jmyu9h\hexbytes\.eggs\pypandoc-1.4-py2.7.egg\pypandoc\__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\username\appdata\local\temp\pip-build-jmyu9h\hexbytes\

**Comment by AvishaiW** [comment]
I see you tried creating the environment with python 2.7, try using 3.6 with the following command: `conda create --name catalyst python=3.6 scipy zlib`. if this still doesn't work I advise you to try reinstalling anaconda (in the installation, make sure you add it to the path) and trying again.

**Comment by kooomix** [comment]
I worked! It was indeed the issue with the python version. Thanks, Avishai!
