### ISSUE TITLE
Catalyst Test Issue in Pycharm

### ISSUE THREAD

**Issue by philcourt** [enigmampc/catalyst#262]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacBook Pro macOs High Sierra 10.13.3
* Python Version: `$ python --version 3.6.4
* Python Bitness: 64
* Python packages: `$ pip freeze: appnope==0.1.0
bleach==2.1.2
cycler==0.10.0
decorator==4.2.1
entrypoints==0.2.3
html5lib==1.0.1
ipykernel==4.8.2
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.2
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
MarkupSafe==1.0
matplotlib==2.1.2
mistune==0.8.3
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.0
numpy==1.14.1
package-name==0.1
pandas==0.22.0
pandocfilters==1.4.2
parso==0.1.1
pbr==3.1.1
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2018.3
pyzmq==17.0.0
qtconsole==4.3.1
scipy==1.0.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
stevedore==1.28.0
terminado==0.8.1
testpath==0.3.1
tornado==4.5.3
traitlets==4.3.2
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.8.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.4

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Have tried to run a test on catalyst in Pycharm for the first time as per this How to: 
[https://risingblock.com/setup-guide-for-enigma-catalyst-on-pycharm/](url)

I followed the instructions perfectly setting up the new virtual environment.

* What did you expect to happen?
I expected the code to run and output the following....

1. 2 day trading simulation
2. first day open date and time
3. last day close date and time
4. Process finished with exit code 0

* What happened instead?
This is the output I get instead:

[2018-03-02 13:09:11.830644] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-03-02 13:09:14.836207] INFO: run_algo: running algo in backtest mode
[2018-03-02 13:09:17.319832] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py", line 933, in get_spot_values
    value = reader.get_value(
AttributeError: 'NoneType' object has no attribute 'get_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/phillippecourt/enigmacatalyst/test.py", line 25, in <module>
    end=pd.to_datetime('2017-10-31', utc=True),
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 549, in run_algorithm
    stats_output=stats_output
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 331, in _run
    overwrite_sim_params=False,
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 352, in run
    data, overwrite_sim_params
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 309, in run
    data, overwrite_sim_params
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 330, in handle_data
    super(ExchangeTradingAlgorithmBacktest, self).handle_data(data)
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/algorithm.py", line 473, in handle_data
    self._handle_data(self, data)
  File "/Users/phillippecourt/enigmacatalyst/test.py", line 12, in handle_data
    record(btc=data.current(context.asset, 'price'))
  File "catalyst/_protocol.pyx", line 120, in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call
  File "catalyst/_protocol.pyx", line 331, in catalyst._protocol.BarData.current
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 160, in get_spot_value
    args=(assets, field, dt, data_frequency))
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/redo/__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 112, in _get_spot_value
    assets.exchange, [assets], field, dt, data_frequency)
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 371, in get_exchange_spot_value
    return bundle.get_spot_values(assets, field, dt, data_frequency)
  File "/Users/phillippecourt/enigmacatalyst/venv/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py", line 952, in get_spot_values
    end_dt=dt
catalyst.exchange.exchange_errors.PricingDataNotLoadedError: Missing data for poloniex ['btc_usdt'] in date range [2017-10-30 00:00:00+00:00 - 2017-10-30 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x poloniex -f daily -i btc_usdt`. See catalyst documentation for details.

Process finished with exit code 1

Here is how you can reproduce this issue on your machine:
Follow the above How to tutorial

# Anything else?
I am a noob with Pycharm, Catalyst, and Python. Probably way out of my depth but enjoy experimenting. 
...

Sincerely,
`$ Phil

**Comment by AvishaiW** [comment]
Hi @philcourt, have you tried ingesting the data with the following command: `catalyst ingest-exchange -x poloniex -f daily -i btc_usdt` in your terminal before running the test?

**Comment by philcourt** [comment]
Hi @AvishaiW, no I missed missed that fundamental step. I did that and it worked ran perfectly. I've got a lot to learn. Thanks very much for your help.
