### ISSUE TITLE
Problems ingesting poloniex minute data

### ISSUE THREAD

**Issue by sam31415** [enigmampc/catalyst#267]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 7
* Python Version: 2.7.13
* Python Bitness: Error, EOL while scanning string literal (after import)
* How did you install Catalyst: pip if I remember well
* Python packages: 
alabaster==0.7.10
alembic==0.9.7
astroid==1.5.3
attrdict==2.0.0
Babel==2.5.0
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bcolz==0.12.1
bleach==2.1.2
boto3==1.5.25
botocore==1.8.39
Bottleneck==1.2.1
ccxt==1.10.1056
certifi==2018.1.18
chardet==3.0.4
click==6.7
colorama==0.3.9
configparser==3.5.0
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0
decorator==4.2.1
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.2
entrypoints==0.2.3
enum34==1.1.6
eth-abi==1.0.0b0
eth-account==0.1.0a2
eth-keyfile==0.5.0
eth-keys==0.2.0b1
eth-rlp==0.1.0a2
eth-utils==1.0.0b1
functools32==3.2.3.post2
futures==3.2.0
hexbytes==0.1.0b0
html5lib==1.0.1
idna==2.6
imagesize==0.7.1
intervaltree==2.1.0
ipykernel==4.7.0
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.0
isort==4.2.15
jedi==0.10.2
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.0
jupyter-console==5.2.0
jupyter-core==4.4.0
lazy-object-proxy==1.3.1
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
mistune==0.8.3
multipledispatch==0.4.9
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
notebook==5.2.2
numexpr==2.6.4
numpy==1.14.0
numpydoc==0.7.0
pandas==0.19.2
pandas-datareader==0.6.0
pandocfilters==1.4.2
path.py==10.3.1
pathlib2==2.3.0
patsy==0.5.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
psutil==5.2.2
pycodestyle==2.3.1
pycryptodome==3.4.11
pyflakes==1.6.0
pyfolio==0.8.0
Pygments==2.2.0
pylint==1.7.2
pyparsing==2.2.0
pysha3==1.0.2
python-bittrex==0.3.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
pyzmq==16.0.3
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
rope==0.9.4
s3transfer==0.1.12
scandir==1.6
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcontainers==1.5.9
sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.3
SQLAlchemy==1.2.2
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.16
tables==3.4.2
tabulate==0.8.2
testpath==0.3.1
toolz==0.9.0
tornado==4.5.2
traitlets==4.3.2
typing==3.6.2
urllib3==1.22
wcwidth==0.1.7
web3==4.0.0b9
webencodings==0.5.1
widgetsnbextension==3.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.10.11

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?

I expect to be able to ingest poloniex data without error message. I expect that once it has run once, it won't ingest new data if the command is rerun immediately after. I expect to be able to backtest with the ingested data without getting error messages claiming the data has not been ingested.

* What happened instead?

As described here: https://catalyst.enigma.co/t/problem-ingesting-poloniex-data/50

When I ingest data from poloniex, I randomly get errors looking like the one attached below. It seems to complain about a temporary folder not being emply. I can empty this folder manually and reingest. Then I may or may not get again a random error like this one. Even if I ingest the full data successfully, I still get errors in Catalyst when backtesting. At the price of excluding XRP-BTC, I have been able to backtest BTC pairs from Jan 2016 to end of Nov 2017. I can also backtest from Dec 3 to Dec 29. In other periods I get repeated error messages claiming the data hasn’t been ingested. Using the catalyst clean-ingest

Ingesting exchange bundle poloniex…
[================== ] Ingesting minute price data on poloniex: 51% 0d 00:03:05[2018-02-27 19:47
:13.468000] WARNING: exchange_bundle: skipping ctable for grc_btc from 2018-02-01 00:00:00+00:00 to 2018-02-14 23:59:00+
00:00: [Errno 2] No such file or directory: u’C:\Users\Sam\.catalyst\data\exchanges\poloniex\temp_bundles\poloni
ex-minute-grc_btc-2018-02\67\95\679521.bcolz\open\meta\sizes’
[========================= ] Ingesting minute price data on poloniex: 69% 0d 00:01:53
Traceback (most recent call last):
File “c:\users\sam\anaconda2\envs\catalyst\lib\runpy.py”, line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File “c:\users\sam\anaconda2\envs\catalyst\lib\runpy.py”, line 72, in run_code
exec code in run_globals
File "C:\Users\Sam\Anaconda2\envs\catalyst\Scripts\catalyst.exe_main.py", line 9, in 
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\click\core.py”, line 722, in call
return self.main(*args, **kwargs)
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\click\core.py”, line 697, in main
rv = self.invoke(ctx)
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\click\core.py”, line 1066, in invoke
return process_result(sub_ctx.command.invoke(sub_ctx))
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\click\core.py”, line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\click\core.py”, line 535, in invoke
return callback(*args, **kwargs)
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\click\decorators.py”, line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\catalyst_main.py", line 594, in ingest_exchange
csv=csv
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py”, line 823, in inges
t
show_report=show_report
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py”, line 642, in inges
t_assets
cleanup=True
File “c:\users\sam\anaconda2\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py”, line 420, in inges
t_ctable
shutil.rmtree(reader._rootdir)
File “c:\users\sam\anaconda2\envs\catalyst\lib\shutil.py”, line 247, in rmtree
rmtree(fullname, ignore_errors, onerror)
File “c:\users\sam\anaconda2\envs\catalyst\lib\shutil.py”, line 247, in rmtree
rmtree(fullname, ignore_errors, onerror)
File “c:\users\sam\anaconda2\envs\catalyst\lib\shutil.py”, line 256, in rmtree
onerror(os.rmdir, path, sys.exc_info())
File “c:\users\sam\anaconda2\envs\catalyst\lib\shutil.py”, line 254, in rmtree
os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: u’C:\Users\Sam\.catalyst\data\exchanges\poloniex\temp_bundl
es\poloniex-minute-pasc_btc-2018-02\11\18’

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Clear .catalyst folder under user profile.
2. Re-ingest exchange data.
3. Run a backtest using xrp_btc using poloniex minute data in 2017. Try to backtest using all the _btc pairs starting on dec 1st with poloniex minute data. Try to backtest using all the _btc pairs in 2018 with poloniex minute data
...

## What steps have you taken to resolve this already?

Repeatedly ingested the data. Ran catalyst clean-exchange and reingested multiple times, getting errors like the one above along the way, until the data was fully ingested.

Thanks, 

Samuel

**Comment by AvishaiW** [comment]
answered on the forum. Try upgrading enigma-catalyst and notify us if the errors still occur. Thanks!

**Comment by sam31415** [comment]
Thanks for the suggestion. From the release notes of 0.5.3, it didn't look like updating could help my problem. 

I tried to update, but it fails when trying to install hexbytes. As far as I know hexbytes is not compatible with Python 2.7, see
https://pypi.python.org/pypi/hexbytes
Does it mean that future updates of catalyst are incompatible with Python 2.7?

Here is the error message I get when trying to update:

Collecting hexbytes<1.0.0,>=0.1.0b1 (from web3>=4.0.0b7->enigma-catalyst)
  Using cached hexbytes-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable
'Py_DEBUG' is unset, Python ABI tag may be incorrect
      warn=(impl == 'cp')):
    C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable
'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
      warn=(impl == 'cp')):
    C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\setuptools\pep425tags.py:99: RuntimeWarning: Config variable
'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
      sys.version_info < (3, 3))) \
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------

    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__


    !!! pandoc not found, long_description is bad, don't upload this to PyPI !!!



    Installed c:\users\sam\appdata\local\temp\pip-build-svu85q\hexbytes\.eggs\pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sam\appdata\local\temp\pip-build-svu85q\hexbytes\setup.py", line 67, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\setuptools\dist.py", line 333, in __init__
        _Distribution.__init__(self, attrs)
      File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\setuptools\dist.py", line 476, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\sam\appdata\local\temp\pip-build-svu85q\hexbytes\.eggs\setuptools_markdown-0.2-py2.7.egg\setuptools
_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "c:\users\sam\appdata\local\temp\pip-build-svu85q\hexbytes\.eggs\pypandoc-1.4-py2.7.egg\pypandoc\__init__.py"
, line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sam\appdata\local\temp\pip-build-svu85q\hexbytes
\

**Comment by AvishaiW** [comment]
this will be fixed in the next release (which will hopefully be in the next coming days) but for now, you can download [this file](https://github.com/enigmampc/catalyst/blob/develop/etc/requirements.txt) and run the command `pip install -r path_to_file/requirements.txt`

**Comment by sam31415** [comment]
Oops, exception, see below. I have two algos paper and live trading. Is that why? Anyway I can wait for the next release.

Exception:
Traceback (most recent call last):
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\req\req_set.py", line 795, in install
    requirement.commit_uninstall()
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\req\req_install.py", line 767, in commit_uninstall
    self.uninstalled.commit()
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\req\req_uninstall.py", line 142, in commit
    rmtree(self.save_dir)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
WindowsError: [Error 5] Access is denied: 'c:\\users\\sam\\appdata\\local\\temp\\pip-bvrpru-uninstall\\users\\sam\\anaco
nda2\\envs\\catalyst\\lib\\site-packages\\logbook\\_speedups.pyd'

**Comment by AvishaiW** [comment]
it seems like you are trying to install pip, are you sure you have pip? if not, try installing it and then run the command..

**Comment by sam31415** [comment]
I just run the command you advised: `pip install -r path_to_file/requirements.txt`.

I can run pip freeze and see the packages installed, so I think I do have pip installed.

**Comment by AvishaiW** [comment]
I'm still not sure what the problem is but maybe this will work: 
`python -m pip install -r path_to_file/requirements.txt`.

**Comment by sam31415** [comment]
Thanks, but I still get an error:

`
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command C:\Users\Sam\Anaconda2\envs\catalyst\python.exe -u -c "import setuptools, tokenize;__file
__='c:\\users\\sam\\appdata\\local\\temp\\pip-build-5lrxi8\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__)
;code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\sam\appdat
a\local\temp\tmpuwz1o6pip-wheel- --python-tag cp27:
  lapack_opt_info:
  lapack_mkl_info:
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\Sam\\Anaconda2\\envs\\catalyst\\lib', 'C:\\', 'C:\\Users\\Sam\\Anaconda2\
\envs\\catalyst\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
  customize MSVCCompiler
  customize MSVCCompiler
    libraries openblas not found in ['C:\\Users\\Sam\\Anaconda2\\envs\\catalyst\\lib', 'C:\\', 'C:\\Users\\Sam\\Anaconda
2\\envs\\catalyst\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem',
'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE

  openblas_clapack_info:
  customize MSVCCompiler
  customize MSVCCompiler
    libraries openblas,lapack not found in ['C:\\Users\\Sam\\Anaconda2\\envs\\catalyst\\lib', 'C:\\', 'C:\\Users\\Sam\\A
naconda2\\envs\\catalyst\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\lib
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Sam\Anaconda2\envs\catalyst\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
  customize MSVCCompiler
    libraries lapack not found in ['C:\\Users\\Sam\\Anaconda2\\envs\\catalyst\\lib', 'C:\\', 'C:\\Users\\Sam\\Anaconda2\
\envs\\catalyst\\libs']
    NOT AVAILABLE

  C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\sam\appdata\local\temp\pip-build-5lrxi8\scipy\setup.py", line 265, in <module>
      setup_package()
    File "c:\users\sam\appdata\local\temp\pip-build-5lrxi8\scipy\setup.py", line 262, in setup_package
      setup(**metadata)
    File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "c:\users\sam\appdata\local\temp\pip-build-5lrxi8\scipy\setup.py", line 182, in configuration
      config.add_subpackage('scipy')
    File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpac
kage
      caller_level = 2)
    File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpack
age
      caller_level = caller_level + 1)
    File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_config
uration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpac
kage
      caller_level = 2)
    File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpack
age
      caller_level = caller_level + 1)
    File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_config
uration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
Failed to build scipy
Installing collected packages: pytz, numpy, requests, six, requests-file, scipy, pandas-datareader, patsy, statsmodels,
python-dateutil, Cython, cyordereddict, bottleneck, contextlib2, decorator, networkx, numexpr, click, toolz, multipledis
patch, MarkupSafe, Mako, sqlalchemy, alembic, sortedcontainers, lru-dict, tables, ccxt, boto3
  Found existing installation: pytz 2017.3
    Uninstalling pytz-2017.3:
      Successfully uninstalled pytz-2017.3
  Found existing installation: numpy 1.14.0
    Uninstalling numpy-1.14.0:
      Successfully uninstalled numpy-1.14.0
Exception:
Traceback (most recent call last):
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\req\req_set.py", line 795, in install
    requirement.commit_uninstall()
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\req\req_install.py", line 767, in commit_uninstall
    self.uninstalled.commit()
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\req\req_uninstall.py", line 142, in commit
    rmtree(self.save_dir)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Users\Sam\Anaconda2\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
WindowsError: [Error 5] Access is denied: 'c:\\users\\sam\\appdata\\local\\temp\\pip-uhfvqx-uninstall\\users\\sam\\anaco
nda2\\envs\\catalyst\\lib\\site-packages\\numpy\\.libs\\libopenblas.bnvrk7633hsx7yvo2tadgr4a5kekxjaw.gfortran-win_amd64.
dll'
`
Do you think the access denied could be due to the fact I have an algo running? I'd rather not shut it down now, but if necessary I will.

**Comment by AvishaiW** [comment]
It is quite possible. maybe, instead of stopping them, create a new virtual environment (maybe in python 3.6, that way you will have a supported env for the Marketplace)

**Comment by sam31415** [comment]
Ok I managed to install catalyst 0.5.3. At first, exactly the same problem occured. I had to restart the ingestion once because a "directory is not empty" error like above. Then the ingestion completed, but data for the pairs are missing. (Actually more pairs than before.) Yet I managed to go through the backtest by adding one by one the pairs that were missing. A bit fastidious, but now it seems to be working. Thanks for your help!

Is catalyst supposed to fetch the data for all the pairs when a pair is not specified? Because it was certainly not the case for me, I had to add most of them manually (although not all of them, the highest by market cap were there).

**Comment by sam31415** [comment]
Yes, that's what I'd have expected. 

So to recap. I never managed to ingest the data without getting the "directory not empty" error mentioned in the first post above. By restarting the ingestion sufficiently many times, I manage to make it complete. But then most pairs except for the highest market cap ones are still not ingested. I have to ingest them one by one. Once this is done, everything works fine as expected.

Concerning upgrading to 5.3, the problem was with scipy. I just installed scipy manually (with conda if I remember well). Then the installation of catalyst went through.

**Comment by AvishaiW** [comment]
catalyst 0.5.4 was released. please update if you are still experiencing these issues.

**Comment by LarryEitel** [comment]
I am running: `catalyst ingest-exchange -x bitfinex -i btc_usd -f minute`

And it is returning: 'Trying to ingest exchange bundle bitfinex...'

No problem when running daily:
```
(catalyst) C:\_py>catalyst ingest-exchange -x bitfinex -i btc_usd
Trying to ingest exchange bundle bitfinex...
    [====================================]  Ingesting daily price data on bitfinex:  100%
```

**Comment by lenak25** [comment]
@LarryEitel , not sure I understand the issue.. 
The minute data is much bigger than the daily data so the ingestion procedure takes some time to complete.

**Comment by LarryEitel** [comment]
@lenak25 Thank you for your reply.
"`Trying` to ingest exchange bundle bitfinex..." left me wondering when / IF it would succeed in 'trying'. :)

I also learned that if I run a backtest using a date range that extends beyond current date it would result in a no data exception error. 

It's all good now. :)

**Comment by sam31415** [comment]
@lenak25 I haven't.... As my dataset seems complete now, I prefer not to touch it too much.
