### ISSUE TITLE
Seems python versions are mixed up

### ISSUE THREAD

**Issue by songproducer** [enigmampc/catalyst#28]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Mac 10.12
* Python Version: Python 2.7.13
* Python Bitness: `$ 64
* How did you install Catalyst: pip
* Python packages: alembic==0.9.5
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.26
decorator==4.1.2
empyrical==0.2.1
enigma-catalyst==0.1.dev8
idna==2.6
intervaltree==2.1.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.0.2
multipledispatch==0.4.9
networkx==1.11
numexpr==2.6.2
numpy==1.13.1
pandas==0.19.2
pandas-datareader==0.5.0
patsy==0.4.1
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.2
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.1
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.13
statsmodels==0.8.0
tables==3.4.2
toolz==0.8.2
urllib3==1.22

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? See a plot
* What happened instead? I got this error:
```
Traceback (most recent call last):
  File "/Users/leotreasure/catalyst-venv/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/catalyst/__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/catalyst/__main__.py", line 240, in run
    environ=os.environ,
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 229, in _run
    'script': algotext,
  File "/Users/leotreasure/catalyst-venv/lib/python3.6/site-packages/catalyst/algorithm.py", line 377, in __init__
    code = compile(self.algoscript, filename, 'exec')
  File "buy_and_hodl.py", line 45
    print 'i:', context.i
             ^
SyntaxError: Missing parentheses in call to 'print'
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

Run:
catalyst run -f buy_and_hodl.py --start 2015-3-1 --end 2017-6-28 --capital-base 100000 -o bah.pickle

**Comment by songproducer** [comment]
Got it working by using this buy and hodl:
https://www.enigma.co/catalyst/#/getstarted/build

instead of the one in the examples:
https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/buy_and_hodl.py

**Comment by lacabra** [comment]
Thanks @songproducer for reporting this. I have made the change in the source code in commit 24fd0fa6f8ac0d2e08eb81c35cb0b96db39d4812 on branch develop, and will be merged into master in the next release. Thanks again.
