### ISSUE TITLE
H5py won't work with Catalyst

### ISSUE THREAD

**Issue by shishaboy** [enigmampc/catalyst#280]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

•	Operating System: Windows-10-10.0.16299
•	Python Version: Python 2.7.13
•	Python Bitness: 64
•	How did you install Catalyst: conda
* How did you install Catalyst: conda
* Python packages: `$ pip freeze` or `$ conda list`
# Name                    Version                   Build  Channel
alembic                   0.9.7                     <pip>
asn1crypto                0.24.0                    <pip>
attrdict                  2.0.0                     <pip>
backports-abc             0.5                       <pip>
backports.functools-lru-cache 1.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
bcolz                     0.12.1                    <pip>
bleach                    2.1.2                     <pip>
boto3                     1.5.25                    <pip>
botocore                  1.8.39                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h94faf87_0
ccxt                      1.11.117                  <pip>
certifi                   2018.1.18                 <pip>
certifi                   2018.1.18                py27_0
cffi                      1.11.4                    <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
cntk                      2.4                       <pip>
colorama                  0.3.9                     <pip>
configparser              3.5.0                     <pip>
contextlib2               0.5.5                     <pip>
cryptography              2.1.4                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.28                      <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.4                     <pip>
entrypoints               0.2.3                     <pip>
enum34                    1.1.6                     <pip>
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.0                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
functools32               3.2.3.post2               <pip>
futures                   3.2.0                     <pip>
h5py                      2.7.1            py27h2dd4c20_0
hdf5                      1.10.1               h79de857_2
hexbytes                  0.1.0b0                   <pip>
html5lib                  1.0.1                     <pip>
icc_rt                    2017.0.4             h97af966_0
idna                      2.6                       <pip>
inflection                0.3.1                     <pip>
intervaltree              2.1.0                     <pip>
ipaddress                 1.0.19                    <pip>
ipykernel                 4.7.0                     <pip>
ipython                   5.5.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.1.0                     <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.1                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
Keras                     2.1.5                     <pip>
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mistune                   0.8.3                     <pip>
mkl                       2017.0.3                      0
more-itertools            4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
ndg-httpsclient           0.4.3                     <pip>
networkx                  2.1                       <pip>
notebook                  5.2.2                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0
numpy                     1.14.2                    <pip>
openssl                   1.0.2n               hc64555f_0
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandocfilters             1.4.2                     <pip>
pathlib2                  2.3.0                     <pip>
patsy                     0.5.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py27_1
prompt-toolkit            1.0.15                    <pip>
pyasn1                    0.4.2                     <pip>
pycparser                 2.18                      <pip>
pycryptodome              3.4.11                    <pip>
Pygments                  2.2.0                     <pip>
pyOpenSSL                 17.5.0                    <pip>
pyparsing                 2.2.0                     <pip>
pysha3                    1.0.2                     <pip>
python                    2.7.13              h1b6d89f_16
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.3                    <pip>
PyYAML                    3.12                      <pip>
pyzmq                     16.0.3                    <pip>
qtconsole                 4.3.1                     <pip>
Quandl                    3.3.0                     <pip>
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scandir                   1.6                       <pip>
scikit-learn              0.19.1                    <pip>
scipy                     0.19.1              np113py27_0
scipy                     1.0.0                     <pip>
setuptools                36.4.0                   py27_1
setuptools                38.5.1                    <pip>
simplegeneric             0.8.1                     <pip>
singledispatch            3.4.0.3                   <pip>
six                       1.11.0           py27ha5e1701_1
sklearn                   0.0                       <pip>
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.13.0                    vc9_1  [vc9]
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
TA-Lib                    0.4.15                    <pip>
tables                    3.4.2                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.9.0                     <pip>
tornado                   4.5.3                     <pip>
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wcwidth                   0.1.7                     <pip>
web3                      4.0.0b9                   <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py27_0
widgetsnbextension        3.1.0                     <pip>
win-unicode-console       0.5                       <pip>
wincertstore              0.2              py27hf04cefb_0
wrapt                     1.10.11                   <pip>
zlib                      1.2.11               hbc2faf4_2
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Catalyst won't work with h5py.  If i import h5py before or after catalyst there is an error.  If i don't use h5py I cant load or save models with keras.
* What did you expect to happen?
To run smoothly. 
* What happened instead?

-------Importing h5py before catalyst

(catalyst) C:\Users\kravetsj\Downloads>python -c "import h5py, catalyst"
C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\catalyst\__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 14, in <module>
    from catalyst.data.bundles import load
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\catalyst\data\bundles\__init__.py", line 2, in <module>
    from . import quandl  # noqa
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\catalyst\data\bundles\quandl.py", line 21, in <module>
    from catalyst.data.bundles.core import register_bundle
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\catalyst\data\bundles\core.py", line 20, in <module>
    from ..minute_bars import (
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\catalyst\data\minute_bars.py", line 29, in <module>
    import tables
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\tables\__init__.py", line 90, in <module>
    from .utilsextension import (
ImportError: DLL load failed: The specified procedure could not be found.

----importing h5py after catalyst

(catalyst) C:\Users\kravetsj\Downloads>python -c "import  catalyst, h5py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\_objects.pxd", line 12, in init h5py.h5r
  File "h5py\_objects.pyx", line 1, in init h5py._objects
ImportError: DLL load failed: The specified procedure could not be found.

------ running backtest with h5py

(catalyst) C:\Users\kravetsj\Downloads>catalyst run -f commandml.py -x poloniex --start 2016-5-1 --end 2017-9-30 -c usdt --capital-base 100000 -o buy_btc_simple_out.pickle
Running in backtesting mode.
[2018-03-18 21:03:32.438000] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-03-18 21:03:32.439000] INFO: run_algo: Catalyst version 0.5.4
[2018-03-18 21:03:35.439000] INFO: run_algo: running algo in backtest mode
Using CNTK backend
Selected CPU as the process wide default device.
c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\keras\backend\cntk_backend.py:21: UserWarning: CNTK backend warning: GPU is not detected. CNTK's CPU version is not fully optimized,please run with GPU to get better performance.
  'CNTK backend warning: GPU is not detected. '
[2018-03-18 21:03:50.039000] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
<string>:257: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(input_shape=(30, 2), padding="same", filters=16, kernel_size=4)`
<string>:264: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(padding="same", kernel_size=4, filters=8)`
Traceback (most recent call last):
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\kravetsj\AppData\Local\conda\conda\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 9, in <module>
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 104, in _
    return f(*args, **kwargs)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 291, in run
    stats_output=None,
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 342, in _run
    overwrite_sim_params=False,
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 373, in run
    data, overwrite_sim_params
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 330, in run
    data, overwrite_sim_params
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\utils\events.py", line 216, in handle_data
    dt,
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\utils\events.py", line 235, in handle_data
    self.callback(context, data)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 351, in handle_data
    super(ExchangeTradingAlgorithmBacktest, self).handle_data(data)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 473, in handle_data
    self._handle_data(self, data)
  File "commandml.py", line 353, in handle_data
    ninebtc, tenbtc)
  File "commandml.py", line 307, in get_wieght
    model.load_weights(one)
  File "c:\users\kravetsj\appdata\local\conda\conda\envs\catalyst\lib\site-packages\keras\models.py", line 723, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py.

**Comment by lenak25** [comment]
Thanks @shishaboy for reporting. We will look at this.
