### ISSUE TITLE
Example imports fail

### ISSUE THREAD

**Issue by bkc39** [enigmampc/catalyst#3]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: 
```bash
(catalyst-venv) bash-3.2$ uname -a
Darwin Bens-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```
* Python Version: 
```bash
(catalyst-venv) bash-3.2$ python --version
python --version
Python 3.6.1
```
* Python Bitness: 
```bash
(catalyst-venv) bash-3.2$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'
64
```
* How did you install Zipline: Installed from source using `README.rst`.

* Python packages: 
```bash
(catalyst-venv) bash-3.2$ pip freeze
alembic==0.9.3
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.4.17
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.25.2
decorator==4.0.11
empyrical==0.2.1
enigma-catalyst==0.1.dev5
idna==2.5
intervaltree==2.1.0
Logbook==1.0.0
lru-dict==1.1.6
Mako==1.0.6
MarkupSafe==1.0
matplotlib==2.0.2
multipledispatch==0.4.9
networkx==1.11
numexpr==2.6.2
numpy==1.13.1
pandas==0.19.2
pandas-datareader==0.4.0
patsy==0.4.1
pyparsing==2.2.0
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2017.2
requests==2.18.1
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.1
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.11
statsmodels==0.8.0
tables==3.4.2
toolz==0.8.2
urllib3==1.21.1
```
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Example

* What did you expect to happen?
Expected library to import with no errors.

* What happened instead?

Got an error about an invalid literal. Looks like a typo

Here is how you can reproduce this issue on your machine:

## Reproduction Steps
```bash
(catalyst-venv) Bens-MacBook-Pro:catalyst bkc$ git branch
* master
(catalyst-venv) Bens-MacBook-Pro:catalyst bkc$ git pull
Already up-to-date.
(catalyst-venv) Bens-MacBook-Pro:catalyst bkc$ python
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from catalyst.api import (cancel_order, symbol, record, order_target_value, get_open_orders)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/__init__.py", line 20, in <module>
    from . import data
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/data/__init__.py", line 1, in <module>
    from . import loader
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/data/loader.py", line 36, in <module>
    from catalyst.curate.poloniex import PoloniexCurator
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/curate/poloniex.py", line 9
    DT_START        = time.mktime(datetime(2010, 01, 01, 0, 0).timetuple())
                                                  ^
SyntaxError: invalid token
```
## What steps have you taken to resolve this already?

Should be a simple fix. Just logging here

# Anything else?

Nope

Sincerely,
Ben

**Comment by bkc39** [comment]
Looks like this also affects `catalyst ingest`:
```bash
(catalyst-venv) bash-3.2$ catalyst ingest
catalyst ingest
Traceback (most recent call last):
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst-venv/bin/catalyst", line 7, in <module>
    from catalyst.__main__ import main
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/__init__.py", line 20, in <module>
    from . import data
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/data/__init__.py", line 1, in <module>
    from . import loader
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/data/loader.py", line 36, in <module>
    from catalyst.curate.poloniex import PoloniexCurator
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/curate/poloniex.py", line 9
    DT_START        = time.mktime(datetime(2010, 01, 01, 0, 0).timetuple())
```

The fix is straightforward, but then this module starts complaining about mixing tabs and spaces. When that is done I get:

```bash
(catalyst-venv) Bens-MacBook-Pro:catalyst bkc$ python
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from catalyst.api import cancel_order
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/__init__.py", line 20, in <module>
    from . import data
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/data/__init__.py", line 1, in <module>
    from . import loader
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/data/loader.py", line 37, in <module>
    from catalyst.utils.calendars import get_calendar
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/utils/calendars/__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "/Users/bkc/Documents/code/projects/catalyst/catalyst/utils/calendars/trading_calendar.py", line 30, in <module>
    from catalyst.utils.calendars._calendar_helpers import (
ModuleNotFoundError: No module named 'catalyst.utils.calendars._calendar_helpers'
```
Are we sure that the `catalyst` source directory is added to `PYTHONPATH` when the virtualenv is fired up?

If not, I can add the `.pth` to `catalyst-venv` site packages.

**Comment by cfromknecht** [comment]
The formatting and indentation problems were solved by this pull request: https://github.com/enigmampc/catalyst/pull/4

For others who encounter the latter bug, this seems to have been caused by running the python interpreter from the repository's working directory, as this causes it to import the source files directly, instead of the importing the files installed in the virtualenv or in the user's site-packages.  The above error is failing to find one of the compiled classes, _calendar_helpers, that does not get built in the source directory.  It's probably best to avoid importing catalyst from any file repo's working directory to avoid confusion.

Thanks @bkc39 for your help on this issue!
