### ISSUE TITLE
No BTC data after May 24?!

### ISSUE THREAD

**Issue by STOpandthink** [enigmampc/catalyst#349]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Darwin Alexeis-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: anaconda
* Python packages:
```
# packages in environment at /anaconda3/envs/catalyst:
#
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
appnope                   0.1.0                     <pip>
astroid                   1.6.4                     <pip>
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
backcall                  0.1.0                     <pip>
backports                 1.0              py36ha3c1827_1  
backports.functools_lru_cache 1.5                      py36_0    conda-forge
bcolz                     0.12.1                    <pip>
bleach                    2.1.3                     <pip>
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
cchardet                  2.1.1                     <pip>
ccxt                      1.14.52                   <pip>
certifi                   2018.1.18                py36_0  
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0           py36hfc81398_0  
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.11                    <pip>
entrypoints               0.2.3                     <pip>
eth-abi                   1.1.1                     <pip>
eth-account               0.2.2                     <pip>
eth-hash                  0.1.3                     <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b3                   <pip>
eth-rlp                   0.1.2                     <pip>
eth-utils                 1.0.3                     <pip>
freetype                  2.8                  h12048fb_1    anaconda
hexbytes                  0.1.0                     <pip>
html5lib                  1.0.1                     <pip>
idna                      2.6                       <pip>
idna-ssl                  1.0.0                     <pip>
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                     <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.4.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.2.1                     <pip>
isort                     4.3.4                     <pip>
jedi                      0.12.0                    <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
kiwisolver                1.0.1                    py36_1    conda-forge
lazy-object-proxy         1.3.1                     <pip>
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.34               he12f830_0  
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2            py36ha7267d0_0  
mccabe                    0.6.1                     <pip>
mistune                   0.8.3                     <pip>
mkl                       2018.0.1             hfbd8650_4  
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
ncurses                   6.1                  h0a44026_0  
networkx                  2.1                       <pip>
notebook                  5.5.0                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0           py36ha726252_2  
openssl                   1.0.2n               hdbc3d79_0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandocfilters             1.4.2                     <pip>
parsimonious              0.8.0                     <pip>
parso                     0.2.0                     <pip>
patsy                     0.5.0                     <pip>
pexpect                   4.5.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       10.0.1                    <pip>
pip                       9.0.1                    py36_5  
prompt-toolkit            1.0.15                    <pip>
ptyprocess                0.5.2                     <pip>
pycares                   2.3.0                     <pip>
pycryptodome              3.6.1                     <pip>
Pygments                  2.2.0                     <pip>
pylint                    1.9.1                     <pip>
pyparsing                 2.2.0            py36hb281f35_0  
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc167b69_3  
python-dateutil           2.7.3                    py36_0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2018.4                   py36_0  
pytz                      2018.3                    <pip>
pyzmq                     17.0.0                    <pip>
qtconsole                 4.3.1                     <pip>
readline                  7.0                  hc1231fa_4  
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.0            py36h1de22e9_0  
Send2Trash                1.5.0                     <pip>
setuptools                38.4.0                   py36_0  
setuptools                39.2.0                    <pip>
simplegeneric             0.8.1                     <pip>
six                       1.11.0           py36h0e22d5e_1  
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0               h3efe00b_0  
statsmodels               0.8.0                     <pip>
TA-Lib                    0.4.17                    <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                     <pip>
tornado                   5.0.2                    py36_0  
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                     <pip>
web3                      4.2.1                     <pip>
webencodings              0.5.1                     <pip>
websockets                5.0                       <pip>
wheel                     0.30.0           py36h5eb2c71_1  
widgetsnbextension        3.2.1                     <pip>
wrapt                     1.10.11                   <pip>
xz                        5.2.3                h727817e_4  
yarl                      1.1.0                     <pip>
zlib                      1.2.11               hf3cbc9b_2
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Placing an order_target_percent fails starting on May 24th.

```
Traceback (most recent call last):
  File "/anaconda3/envs/catalyst/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/__main__.py", line 104, in _
    return f(*args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/__main__.py", line 291, in run
    stats_output=None,
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 363, in _run
    overwrite_sim_params=False,
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 401, in run
    data, overwrite_sim_params
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 358, in run
    data, overwrite_sim_params
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 379, in handle_data
    super(ExchangeTradingAlgorithmBacktest, self).handle_data(data)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 473, in handle_data
    self._handle_data(self, data)
  File "buy_btc_simple.py", line 8, in handle_data
    order_target_percent(context.asset, 1)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/api_support.py", line 57, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/api_support.py", line 126, in wrapped_method
    return method(self, *args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 2014, in order_target_percent
    amount = self._calculate_order_target_percent_amount(asset, target)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 2021, in _calculate_order_target_percent_amount
    target_amount = self._calculate_order_percent_amount(asset, target)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 1848, in _calculate_order_percent_amount
    return self._calculate_order_value_amount(asset, value)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 1366, in _calculate_order_value_amount
    self.datetime)
catalyst.errors.CannotOrderDelistedAsset: Cannot order btc_usd on 2018-05-24 00:00:00+00:00 as there is no last price for the security.
```

## Reproduction Steps

1. Use buy_btc_simple.py 
2. Modify `order` to be `order_target_percent`
3. catalyst run -f buy_btc_simple.py -x bitfinex --start 2018-5-23 --end 2018-5-26 -c usd --capital-base 100000 --data-frequency minute

...

## What steps have you taken to resolve this already?

```
catalyst clean-exchange -x bitfinex
catalyst ingest-exchange -x bitfinex -i btc_usd -f minute
```

# Anything else?

I wonder why 24th. I think it has something to do with my environment. I was working on my algorithm and tried running it live in paper-trading mode for the first time on 24th. Then I took a vacation, came back, and now it doesn't work.

Sincerely,
Alexei

**Comment by STOpandthink** [comment]
Also just upgrade Catalyst to version 0.5.12 and still same issue. Furthermore, I got this to reproduce on a clean install.

**Comment by STOpandthink** [comment]
I printed out the price `print(data.current(context.asset, 'price'))` and it shows NaN on 24th and later. (Same on Poloniex, by the way.)

**Comment by STOpandthink** [comment]
Additional piece of data: when I run the algorithm in live paper trading mode, it works and has access to accurate historical data.

**Comment by SOGorman35** [comment]
Per https://enigma.co/catalyst/status/, the pricing data for all three exchanges has not been updated since May 23rd.

**Comment by lenak25** [comment]
Thanks for reporting @STOpandthink .
There is currently a known issue with the historical data, like @SOGorman35 mentioned, we are working to fix this.

**Comment by lacabra** [comment]
This issue has been resolved. Apologies for the delay. Thanks @STOpandthink for reporting.

This issue has nothing to do with the Catalyst client (and thus is independent of whatever version you are running), but relates to the server-side infrastructure that we run to support Catalyst. This issue has been fixed, and https://enigma.co/catalyst/status/ is now up to date showing that data is current as of yesterday (which is what should be: always up to date up to the day before).

Because of stale data, you will probably need to clear your cache of historical data with:
```
catalyst clean-exchange -x bitfinex
```
and then re-ingest whatever data you need.

Here's a snapshot of May pricing data (close) from 20 randomly chosen coins from Bitfinex that validates this issue is resolved.
![figure_1](https://user-images.githubusercontent.com/6098973/40934030-af365316-67f0-11e8-8432-e5522f61fe73.png)
