### ISSUE TITLE
exception on poloniex buy order

### ISSUE THREAD

**Issue by ytkang** [enigmampc/catalyst#350]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: ubuntu
* Python Version: python 3.5.2
* Python Bitness: 664
* How did you install Catalyst: pip
* Python packages: 
alembic==0.9.9
APScheduler==3.5.1
attrdict==2.0.0
bcolz==0.12.1
boto3==1.7.25
botocore==1.10.25
Bottleneck==1.2.1
ccxt==1.14.46
certifi==2018.4.16
chardet==3.0.4
click==6.7
colorama==0.3.9
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.28.2
cytoolz==0.9.0.1
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.12
eth-abi==1.1.1
eth-account==0.2.2
eth-hash==0.1.3
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
Flask==1.0.2
gevent==1.3.1
greenlet==0.4.13
grequests==0.3.0
hexbytes==0.1.0
httplib2==0.11.3
idna==2.6
intervaltree==2.1.0
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kiwisolver==1.0.1
Logbook==1.4.0
lru-dict==1.1.6
lxml==4.2.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.2
multipledispatch==0.5.0
networkx==1.11
numexpr==2.6.5
numpy==1.14.3
pandas==0.19.2
pandas-datareader==0.5.0
parsimonious==0.8.0
patsy==0.5.0
pkg-resources==0.0.0
pycryptodome==3.6.1
pycurl==7.43.0.1
pymongo==3.6.1
pyparsing==2.2.0
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2018.4
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.1
s3transfer==0.1.13
schedule==0.5.0
scipy==1.1.0
simplejson==3.15.0
six==1.11.0
sortedcontainers==2.0.2
SQLAlchemy==1.2.7
statsmodels==0.9.0
TA-Lib==0.4.17
tables==3.4.3
toolz==0.9.0
tzlocal==1.5.1
urllib3==1.22
web3==4.2.1
websockets==5.0
Werkzeug==0.14.1
wrapt==1.10.11
xlrd==1.1.0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
polonix buy order crashed

## Reproduction Steps

1. buy xrp_btc symbol using order function
price: 8.034975e-05, 
order amount: 5.911991014284426
2. after exception, when I checked my poloniex balance, the order was completed.

exception:
Traceback (most recent call last):
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='poloniex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 358, in fetch
    proxies=self.proxies
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='poloniex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 899, in create_order
    price=price
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/poloniex.py", line 615, in create_order
    }, params))
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 307, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 304, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 368, in fetch
    self.raise_error(RequestTimeout, method, url, e)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 289, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: poloniex POST https://poloniex.com/tradingApi HTTPSConnectionPool(host='poloniex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trading_coin_spread_btc.py", line 465, in <module>
    stats_output=None,
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/utils/run_algo.py", line 601, in run_algorithm
    stats_output=stats_output
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/utils/run_algo.py", line 363, in _run
    overwrite_sim_params=False,
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/exchange_algorithm.py", line 1050, in run
    data, overwrite_sim_params
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/exchange_algorithm.py", line 358, in run
    data, overwrite_sim_params
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/utils/events.py", line 235, in handle_data
   self.callback(context, data)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/exchange_algorithm.py", line 904, in handle_data
    self._handle_data(self, data)
  File "trading_coin_spread_btc.py", line 432, in handle_data
    limit_price=limit_price
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/utils/api_support.py", line 57, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/utils/api_support.py", line 126, in wrapped_method
    return method(self, *args, **kwargs)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/algorithm.py", line 1463, in order
    return self.blotter.order(asset, amount, style)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/exchange_blotter.py", line 169, in order
    if amount == 0:
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/exchange_blotter.py", line 185, in order
    args=(asset, amount, style),
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/redo/__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/exchange_blotter.py", line 163, in exchange_order
    asset, amount, style
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/exchange.py", line 877, in order
    return self.create_order(asset, amount, is_buy, style)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 913, in create_order
    before_order_dt, asset, amount, is_buy, style, adj_amount
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 841, in _handle_request_timeout
    dt_before=dt_before, symbol=asset.asset_name)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 802, in _fetch_missing_order
    recent_trades = [x for x in self.api.fetch_my_trades(symbol=symbol)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/poloniex.py", line 442, in fetch_my_trades
    market = self.market(symbol)
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 1226, in market
    self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
  File "/home/ubuntu/p3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 289, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: poloniex No market symbol XRP / BTC

**Comment by lenak25** [comment]
Thanks @ytkang for reporting. 
We will try to reproduce it.
Looks like it might be a result of some connectivity issue. Please let us know if it is repeated.

Thanks,
Lena

**Comment by AvishaiW** [comment]
Fixed the error, will be added to the next release.

**Comment by AvishaiW** [comment]
added to release 0.5.14
