### ISSUE TITLE
Cannot install development requirements

### ISSUE THREAD

**Issue by hnipps** [enigmampc/catalyst#351]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: macOS High Sierra 10.13.4
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: 
```
# Name                    Version                   Build  Channel
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.7.7                     <pip>
argh                      0.26.2                    <pip>
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.3                     <pip>
async-timeout             2.0.1                     <pip>
attrs                     17.4.0                    <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.4.8                     <pip>
botocore                  1.8.50                    <pip>
Bottleneck                1.0.0                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
cchardet                  2.1.1                     <pip>
ccxt                      1.12.131                  <pip>
certifi                   2018.1.18                py36_0  
cffi                      1.11.4           py36h342bebf_0  
chardet                   3.0.4            py36h96c241c_1  
click                     4.0                       <pip>
colorama                  0.3.9                     <pip>
conda                     4.4.10                   py36_0  
conda-env                 2.6.0                h36134e3_0  
contextlib2               0.4.0                     <pip>
cryptography              2.1.4            py36h842514c_0  
cyordereddict             0.2.2                     <pip>
Cython                    0.25.2                    <pip>
decorator                 4.0.0                     <pip>
docopt                    0.6.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
geographiclib             1.49                      <pip>
idna                      2.6              py36h8628d0a_1  
idna-ssl                  1.0.1                     <pip>
intervaltree              2.1.0                     <pip>
iso-639                   0.4.5                     <pip>
iso3166                   0.8                       <pip>
isort                     4.3.4                     <pip>
jmespath                  0.9.3                     <pip>
lazy-object-proxy         1.3.1                     <pip>
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
Logbook                   0.12.5                    <pip>
lru-dict                  1.1.4                     <pip>
Mako                      1.0.1                     <pip>
MarkupSafe                0.23                      <pip>
mccabe                    0.6.1                     <pip>
more-itertools            4.1.0                     <pip>
multidict                 4.3.1                     <pip>
multipledispatch          0.4.8                     <pip>
ncurses                   6.0                  hd04f020_2  
networkx                  1.9.1                     <pip>
numexpr                   2.6.1                     <pip>
numpy                     1.13.1                    <pip>
nvector                   0.5.2                     <pip>
openssl                   1.0.2n               hdbc3d79_0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.2.1                     <pip>
pathtools                 0.1.2                     <pip>
patsy                     0.4.0                     <pip>
pip                       10.0.1                    <pip>
pip                       9.0.1            py36h1555ced_4  
pluggy                    0.6.0                     <pip>
py                        1.5.3                     <pip>
pycares                   2.3.0                     <pip>
pycosat                   0.6.3            py36hee92d8f_0  
pycparser                 2.18             py36h724b2fc_1  
pycryptodome              3.6.0                     <pip>
pylint                    1.8.4                     <pip>
pyopenssl                 17.5.0           py36h51e4350_0  
pysocks                   1.6.7            py36hfa33cec_1  
pytest                    3.5.0                     <pip>
pytest-watch              4.1.0                     <pip>
python                    3.6.4                hc167b69_1  
python-dateutil           2.4.2                     <pip>
python.app                2                py36h54569d5_7  
pytz                      2016.4                    <pip>
PyYAML                    3.12                      <pip>
readline                  7.0                  hc1231fa_4  
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests                  2.18.4           py36h4516966_1  
requests-file             1.4.1                     <pip>
rope                      0.10.7                    <pip>
ruamel_yaml               0.15.35          py36h1de35cc_1  
s3transfer                0.1.13                    <pip>
scipy                     0.17.1                    <pip>
setuptools                38.4.0                   py36_0  
setuptools                38.5.1                    <pip>
six                       1.11.0           py36h0e22d5e_1  
six                       1.10.0                    <pip>
sortedcontainers          1.4.4                     <pip>
SQLAlchemy                1.0.8                     <pip>
sqlite                    3.22.0               h3efe00b_0  
statsmodels               0.6.1                     <pip>
streamlink                0.11.0                    <pip>
tables                    3.3.0                     <pip>
tk                        8.6.7                h35a86e2_3  
toolz                     0.8.2                     <pip>
urllib3                   1.22             py36h68b9469_0  
watchdog                  0.8.3                     <pip>
websocket-client          0.47.0                    <pip>
wheel                     0.30.0           py36h5eb2c71_1  
wrapt                     1.10.11                   <pip>
xz                        5.2.3                h0278029_2  
yaml                      0.1.7                hc338f04_2  
yarl                      1.1.0                     <pip>
zlib                      1.2.11               hf3cbc9b_2  
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I expected that I'd be able to install the development requirements using the instructions provided [here](https://enigma.co/catalyst/development-guidelines.html).
* What happened instead?
An error was thrown:
```
Invalid requirement: '>'                                                                                    
Traceback (most recent call last):                                                                          
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", 
line 93, in __init__                                                                                        
    req = REQUIREMENT.parseString(requirement_string)                                                       
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in
 parseString                                                                                                
    raise exc                                                                                               
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in
 parseString                                                                                                
    loc, tokens = self._parse( instring, 0 )                                                                
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in
 _parseNoCache                                                                                              
    loc,tokens = self.parseImpl( instring, preloc, doActions )                                              
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in
 parseImpl                                                                                                  
    loc, exprtokens = e._parse( instring, loc, doActions )                                                  
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in
 _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3717, in
 parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in
 _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3378, in
 parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in
 _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 2689, in
 parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 
252, in from_line
    req = Requirement(req)
  File "/Users/harrynicholls/miniconda3/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", 
line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'>'"
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Follow the steps in the ["Creating a Development Environment" guide](https://enigma.co/catalyst/development-guidelines.html#creating-a-development-environment) 
2. The error will be thrown on this command - `$ ./etc/ordered_pip.sh ./etc/requirements.txt`
...

## What steps have you taken to resolve this already?
I've tried to rollback to a different version of setuptools, as that package has caused [problems in the past](https://stackoverflow.com/questions/35625488/invalidrequirement-invalid-requirement-parse-error-error-after-updating-a-py). But it seems to get updated again when I run the command listed above. 

I removed the offending line `python_version > '3.4'` from `requirements.txt`, which allowed the command to complete, but I have no idea if I have the correct requirements now.
...

# Anything else?

...

Sincerely,
Harry

**Comment by hnipps** [comment]
This is what I get when I run `$ catalyst --version`:
`catalyst, version 0.5.12+0.ga062e182.dirty`

**Comment by lenak25** [comment]
Thanks for the information and for reporting! It is indeed an issue and we will address it.
In the meantime, in order to try to suggest a workaround, could you please specify all the steps you have followed when installing catalyst?
Thanks,
Lena

**Comment by lacabra** [comment]
@hnipps thanks for reporting this. I have updated the `etc/ordered_pip.sh` so that accounts for those type of lines in `etc/requirements.txt` and it seems to work fine now. 

This has been added in commit 45f564b on branch develop. It's staged to be included in our next release.

In the time being you can install the dev environment by:
1. `git clone git@github.com:enigmampc/catalyst.git`
2. `git checkout develop`
3. `git checkout -b some-short-descriptive-name`

And continue to follow the instructions that you mention from ["Creating a Development Environment" guide](https://enigma.co/catalyst/development-guidelines.html#creating-a-development-environment).

Let us know if you have any further questions on this issue.

**Comment by hnipps** [comment]
@lacabra that's brilliant, thanks! I'll try it out when I get a chance. And @lenak25 sorry for not getting back to you quicker.

**Comment by lenak25** [comment]
Was added to release 0.5.14
