### ISSUE TITLE
"catalyst marketplace subscribe" fails

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#352]
-> catalyst marketplace subscribe
.....
Choose the dataset you want to subscribe to [0..22]: 0
Using ** for this transaction.
Traceback (most recent call last):
  File "**/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "**/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "**/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "**/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "**/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "**/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "**/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "**/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "**/lib/python3.6/site-packages/catalyst/__main__.py", line 807, in subscribe
    marketplace.subscribe(dataset)
  File "**/lib/python3.6/site-packages/catalyst/marketplace/marketplace.py", line 252, in subscribe
    Web3.toHex(dataset)
  File "**/lib/python3.6/site-packages/eth_utils/decorators.py", line 73, in wrapper
    return to_wrap(*args, **kwargs)
  File "**/lib/python3.6/site-packages/eth_utils/conversions.py", line 43, in to_hex
    "Unsupported type: The primitive argument must be one of: bytes,"
TypeError: Unsupported type: The primitive argument must be one of: bytes,bytearray, int or bool and not str

Using Mac with Catalyst installed in a Anaconda ENV Python 3.6.4 (Using catalyst env file)

**Comment by avolution** [comment]
same for 

catalyst marketplace subscribe --dataset=enigma_marketcap

**Comment by apalepu23** [comment]
Hey @avolution , 

This is an issue with the latest web3 (and associated dependencies). We've updated the env file and also the necessary client-side changes to handle the new environment. These updates will be pushed out in our next release, which will be next week! Thanks!

**Comment by avolution** [comment]
It is still not working

I have created a new env with the new env file
My catalyst Version now is  0.5.13

**Comment by avolution** [comment]
Same Error 

TypeError: Unsupported type: The primitive argument must be one of: bytes,bytearray, int or bool and not str

**Comment by apalepu23** [comment]
Can you link me to the environment file you are using to create this new
environment?

Thanks!

**Comment by avolution** [comment]
It's woking now Thanks :)

Was a Problem while conda env installation on my machine

**Comment by lenak25** [comment]
Resolved at release 0.5.13.
