### ISSUE TITLE
DistutilsError: Could not find suitable distribution for Requirement.parse('Cython>=0.25.2')

### ISSUE THREAD

**Issue by ankit-maverick** [enigmampc/catalyst#36]
### Environment

* Operating System: `Mac OSX`
* Python Version: `Python 3.6.1`
* Python Bitness: `64 bit`
* How did you install Catalyst: `pip`
* Python packages: `pip (9.0.1) setuptools (36.5.0) wheel (0.30.0)`

```
catalyst-venv)  ankit@Ankits-MacBook-Pro  ~/crypto  pip install enigma-catalyst
Collecting enigma-catalyst
  Downloading enigma-catalyst-0.2.dev5.tar.gz (691kB)
    100% |████████████████████████████████| 696kB 74kB/s
v    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/Cython/: [Errno 65] No route to host -- Some packages may not be found!
    Couldn't find index page for 'Cython' (maybe misspelled?)
    No local packages or working download links found for Cython>=0.25.2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/85/tdct6g4s3fq5zdwkctczl6ym0000gn/T/pip-build-2yj9d9ar/enigma-catalyst/setup.py", line 322, in <module>
        **conditional_arguments
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/ankit/crypto/catalyst-venv/lib/python3.6/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/ankit/crypto/catalyst-venv/lib/python3.6/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/ankit/crypto/catalyst-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/ankit/crypto/catalyst-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/Users/ankit/crypto/catalyst-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/Users/ankit/crypto/catalyst-venv/lib/python3.6/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/ankit/crypto/catalyst-venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('Cython>=0.25.2')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/85/tdct6g4s3fq5zdwkctczl6ym0000gn/T/pip-build-2yj9d9ar/enigma-catalyst/
```

**Comment by lacabra** [comment]
Hi @ankit-maverick, and apologies for the slow response, somehow I missed your submission. It looks like a connectivity issue to me. Could it be possible that when you tried to install, your Internet connection was down? The actual error is `No route to host -- Some packages may not be found!`, but the address that is trying to go to `https://pypi.python.org/simple/cython/` is perfectly valid (you may want to manually follow the link above and check that you can access it).

The latest release of Cython is `0.27.1`, which satisfies the installation requirement for ` Cython>=0.25.2` so I don't see anything wrong in the issue above.

Can you please try again, and let me know if you still experience this issue?

**Comment by LeapGamer** [comment]
I had this same issue on win10 after setting up the conda environment manually according to the tutorial. It turned out that I didn't install the Microsoft Visual C++ Compiler for Python 2.7 (one of the very first instructions!). Just leaving this here in case someone else googles their way to it after making the same mistake.
