### ISSUE TITLE
How can I load my own csv data?

### ISSUE THREAD

**Issue by zxweed** [enigmampc/catalyst#38]
Dear Catalyst Maintainers,

Is there a way to load my own csv quotes into catalyst database? I have found the sample to do this on zipline - http://www.prokopyshen.com/create-custom-zipline-data-bundle, but it is not worked on catalyst...

```$ catalyst ingest -b csv
entering viacsv.  tuSymbols= ('BTC1', 'BTC2')
about to return ingest function
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/anaconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.5/site-packages/catalyst/__main__.py", line 374, in ingest
    compile_locally,
  File "/home/user/anaconda3/lib/python3.5/site-packages/catalyst/data/bundles/core.py", line 556, in ingest
    pth.data_path([name, timestr], environ=environ),
TypeError: ingest() takes from 9 to 11 positional arguments but 13 were given
```

**Comment by fredfortier** [comment]
See issue #65 for details.
