### ISSUE TITLE
can't ingest binance minute data

### ISSUE THREAD

**Issue by demontamer** [enigmampc/catalyst#387]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: ubuntu 16.4
* Python Version: `$ python --2.7`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: pip
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
tried to ingest binance minute data via catalyst ingest-exchange -x binance -f minute
* What did you expect to happen?
data ingesting
* What happened instead?
Type error

![image](https://user-images.githubusercontent.com/8560755/42357548-5fa80512-80d0-11e8-8a91-0bb8c0cf8b74.png)

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. try ingesting binance minute data
...

## What steps have you taken to resolve this already?
none.
...

# Anything else?

...

Sincerely,
demontamer

**Comment by lenak25** [comment]
Hi @demontamer ,

How did you upgrade to the new version? Using the following:
"""
pip uninstall enigma-catalyst
pip install enigma-catalyst
"""
If not, could you please try this and try to ingest again?

Thanks,

Lena

**Comment by demontamer** [comment]
Hi used `pip install -U enigma-catalyst`

**Comment by brandsimon** [comment]
I have a similar issue with catalyst 0.5.15 and python 3.6.6
```
Trying to ingest exchange bundle binance...
Traceback (most recent call last):
  File ".venv/bin/catalyst", line 11, in <module>
    load_entry_point('enigma-catalyst==0.5.15', 'console_scripts', 'catalyst')()
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/catalyst/__main__.py", line 609, in ingest_exchange
    csv=csv
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py", line 824, in ingest
    show_report=show_report
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py", line 593, in ingest_assets
    end_dt=end_dt
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py", line 506, in prepare_chunks
    start_dt, end_dt, [asset], data_frequency
  File "/home/work/berserker-lib/.venv/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py", line 444, in get_adj_dates
    if asset.start_date >= self.calendar.first_session:
  File "pandas/tslib.pyx", line 1103, in pandas.tslib._Timestamp.__richcmp__ (pandas/tslib.c:20491)
TypeError: Cannot compare type 'Timestamp' with type 'str'
```

This happens with daily and minute

**Comment by lenak25** [comment]
Thanks everyone for your inputs!

There was indeed a problem in the config file describing the supported trading pairs on Binance.
The problem was resolved.
Right now, there might be a stale config file in your local system, which you can remove and clean by running `catalyst clean-exchange -x binance`. 

Thanks again!

**Comment by brandsimon** [comment]
@lenak25 Thank you very much. It works perfect now :)
