### ISSUE TITLE
Live trading dies when CCXT request times out

### ISSUE THREAD

**Issue by sawyercade** [enigmampc/catalyst#435]
# Description of Issue

When live trading, a request to bittrex for the most recent data timed out, and killed my strategy.

I would expect a configurable number of retries, and maybe even configurable behavior on repeated failure. Stacktrace:

```Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
File "/usr/local/lib/python3.6/ssl.py", line 1009, in recv_into
return self.read(nbytes, buffer)
File "/usr/local/lib/python3.6/ssl.py", line 871, in read
return self._sslobj.read(len, buffer)
File "/usr/local/lib/python3.6/ssl.py", line 631, in read
v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
timeout=timeout
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 356, in fetch
proxies=self.proxies
File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/reactor/src/reactor/trading_algos/macd_signal.py", line 170, in <module>
stats_output='s3://reactor-dev')
File "/usr/local/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 596, in run_algorithm
stats_output=stats_output
File "/usr/local/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 358, in _run
overwrite_sim_params=False,
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 1051, in run
data, overwrite_sim_params
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 359, in run
data, overwrite_sim_params
File "/usr/local/lib/python3.6/site-packages/catalyst/algorithm.py", line 725, in run
for perf in self.get_generator():
File "/usr/local/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
for capital_change_packet in every_bar(dt):
File "/usr/local/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
handle_data(algo, current_data, dt_to_use)
File "/usr/local/lib/python3.6/site-packages/catalyst/utils/events.py", line 216, in handle_data
dt,
File "/usr/local/lib/python3.6/site-packages/catalyst/utils/events.py", line 235, in handle_data
self.callback(context, data)
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 905, in handle_data
self._handle_data(self, data)
File "/reactor/src/reactor/trading_algos/macd_signal.py", line 39, in handle_data
frequency=context.frequency,
File "catalyst/_protocol.pyx", line 120, in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call
File "catalyst/_protocol.pyx", line 633, in catalyst._protocol.BarData.history
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 97, in get_history_window
ffill))
File "/usr/local/lib/python3.6/site-packages/redo/__init__.py", line 162, in retry
return action(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 71, in _get_history_window
ffill)
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 220, in get_exchange_history_window
False)
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/exchange.py", line 524, in get_history_window
end_dt=end_dt if not is_current else None,
File "/usr/local/lib/python3.6/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 462, in get_candles
params=
{}

File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 422, in fetch_ohlcv
response = self.v2GetMarketGetTicks(self.extend(request, params))
File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 684, in request
response = self.fetch2(path, api, method, params, headers, body)
File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 302, in fetch2
return self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 366, in fetch
self.raise_error(RequestTimeout, method, url, e)
File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 287, in raise_error
raise exception_type(output)
ccxt.base.errors.RequestTimeout: bittrex GET https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=oneMin&marketName=USDT-ETH HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)```

## Reproduction Steps

1. Live trade an algorithm
2. Turn off your network connection

**Comment by lenak25** [comment]
Hi @sawyercade ,

Thanks for reporting.
I believe this is duplication of #420 , which was fixed on develop branch and will be included in our next release.
I am closing this but feel free to reopen if you feel otherwise.

Thanks,

Lena
