### ISSUE TITLE
TypeError: set_slippage() got an unexpected keyword argument 'slippage'

### ISSUE THREAD

**Issue by yhmickey** [enigmampc/catalyst#455]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (MAC)
* Python Version: `$ python --3`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`conda``)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
when running the examples: mean_reversion_simple.py. 

catalyst run -f mean_reversion_simple.py -x poloniex -s 2018-2-1 -e 2018-3-1 -c usdt --capital-base 10000 --data-frequency minute -n mean-reversion

Traceback (most recent call last):
  File "/anaconda3/envs/catalyst/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/__main__.py", line 105, in _
    return f(*args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/__main__.py", line 292, in run
    stats_output=None,
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 363, in _run
    overwrite_sim_params=False,
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 402, in run
    data, overwrite_sim_params
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 359, in run
    data, overwrite_sim_params
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 623, in get_generator
    return self._create_generator(self.sim_params)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 594, in _create_generator
    self.initialize(*self.initialize_args, **self.initialize_kwargs)
  File "/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 458, in initialize
    self._initialize(self, *args, **kwargs)
  File "mean_reversion_simple.py", line 47, in initialize
    context.set_slippage(slippage=0.001)
TypeError: set_slippage() got an unexpected keyword argument 'slippage'

* What did you expect to happen?
 context.set_slippage(slippage=0.001) is ok

* What happened instead?
set_slippage() got an unexpected keyword argument 'slippage'

Here is how you can reproduce this issue on your machine:

Sincerely,
`$ Jerry

**Comment by lenak25** [comment]
Hi @yhmickey ,

What version of catalyst are you using?
In [this commit](https://github.com/enigmampc/catalyst/commit/fe741a609c677d2b5a672b684fbbf1d9bd8307ed)  the parameter of the `set_slippage` function was updated from `spread` to `slippage` and the example was updated accordingly.
I am guessing you are using a newer version of the example with an older version of catalyst.
I suggest you upgrade to the latest catalyst version.

Lena

**Comment by yhmickey** [comment]
Thank you .  It's solved. I used an older version of catalyst.
