### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'retrieve_asset'

### ISSUE THREAD

**Issue by mutkan** [enigmampc/catalyst#46]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Mac OSX Sierra Darwin Kernel Version 16.7.0
* Python Version: Python 2.7.13 :: Continuum Analytics, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages:

alembic                   0.9.6                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
Bottleneck                1.2.1                     <pip>
certifi                   2017.7.27.1               <pip>
certifi                   2016.2.28                py27_0  
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.3.1                     <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
libgfortran               3.0.0                         1  
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2017.0.3                      0  
multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0  
openssl                   1.0.2l                        0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1  
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.2                    <pip>
readline                  6.2                           2  
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
scipy                     0.19.1              np113py27_0  
setuptools                36.4.0                   py27_1  
six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0  
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
wheel                     0.29.0                   py27_0  
zlib                      1.2.11                        0 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Run buy_and_hold.py example:
catalyst run -f buy_and_hodl.py -x bitfinex --start 2016-1-1 --end 2017-9-30 -o buy_and_hodle_out.pickle

* What did you expect to happen?
I expect to it should work the example

* What happened instead?

I get this error:

[2017-10-26 20:27:18.844831] INFO: run_algo: running algo in backtest mode
[2017-10-26 20:27:19.814061] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "/Users/gnc/miniconda2/envs/catalyst/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/__main__.py", line 101, in _
    return f(*args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/__main__.py", line 275, in run
    live_graph=False
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 336, in _run
    overwrite_sim_params=False,
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 474, in handle_data
    self._handle_data(self, data)
  File "buy_and_hodl.py", line 59, in handle_data
    price = data[context.asset].price
  File "catalyst/_protocol.pyx", line 817, in catalyst._protocol.BarData.__getitem__
  File "catalyst/_protocol.pyx", line 211, in catalyst._protocol.BarData._get_equity_price_view
AttributeError: 'NoneType' object has no attribute 'retrieve_asset'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lacabra** [comment]
The example you are trying to run uses an asset `btc_usdt` that is not available on exchange `bitfinex` that you specify on the command line. Either change your invocation of Catalyst as follows:
`catalyst run -f buy_and_hodl.py -x poloniex --start 2016-1-1 --end 2017-9-30 -o buy_and_hodle_out.pickle`
or change the asset on line 27 to `context.ASSET_NAME = 'BTC_USD` if you want to run it with the exchange `poloniex`

Also, you are running catalyst 0.3.1, please upgrade to 0.3.3, and you'll get a better error that will help you troubleshoot this problem more easily: `pip install enigma-catalyst --upgrade`

**Comment by mutkan** [comment]
I upgraded to catalyst 0.3.3 and did what you say.

And it gives me this error: 
```
INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Error traceback: /Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange.py (line 177)
SymbolNotFoundOnExchange:  Symbol BTC_USD not found on exchange Poloniex. 
```

When i change the symbol to btc_usdt and run on poloniex it gives me this error.

```
(catalyst) gnc:catalyst gnc$ catalyst run -f buy_and_hodl.py -x poloniex --start 2016-1-1 --end 2017-9-30 -o buy_and_hodle_out.pickle
[2017-10-27 07:21:07.952339] INFO: run_algo: running algo in backtest mode
[2017-10-27 07:21:08.710800] INFO: exchange_bundle: pricing data for [u'btc_usdt'] not found in range 2015-03-01 00:00:00+00:00 to 2017-09-28 00:00:00+00:00, updating the bundles.
    [============                        ]  Fetching poloniex daily candles: :   33%[2017-10-27 07:21:08.763595] WARNING: exchange_bundle: skipping ctable for btc_usdt from 2015-03-01 00:00:00+00:00 to 2015-12-31 00:00:00+00:00: [Errno 2] No such file or directory: '/Users/gnc/.catalyst/data/exchanges/poloniex/temp_bundles/poloniex-daily-btc_usdt-2015/37/44/374465.bcolz/open/meta/sizes'
    [========================            ]  Fetching poloniex daily candles: :   66%[2017-10-27 07:21:08.765894] WARNING: exchange_bundle: skipping ctable for btc_usdt from 2016-01-01 00:00:00+00:00 to 2016-12-31 00:00:00+00:00: [Errno 2] No such file or directory: '/Users/gnc/.catalyst/data/exchanges/poloniex/temp_bundles/poloniex-daily-btc_usdt-2016/37/44/374465.bcolz/open/meta/sizes'
    [====================================]  Fetching poloniex daily candles: :  100%[2017-10-27 07:21:08.768093] WARNING: exchange_bundle: skipping ctable for btc_usdt from 2017-01-01 00:00:00+00:00 to 2017-10-22 00:00:00+00:00: [Errno 2] No such file or directory: '/Users/gnc/.catalyst/data/exchanges/poloniex/temp_bundles/poloniex-daily-btc_usdt-2017/37/44/374465.bcolz/open/meta/sizes'

[2017-10-27 07:21:09.651668] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "/Users/gnc/miniconda2/envs/catalyst/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/__main__.py", line 101, in _
    return f(*args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/__main__.py", line 275, in run
    live_graph=False
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 336, in _run
    overwrite_sim_params=False,
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/Users/gnc/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/algorithm.py", line 474, in handle_data
    self._handle_data(self, data)
  File "buy_and_hodl.py", line 59, in handle_data
    price = data[context.asset].price
  File "catalyst/_protocol.pyx", line 817, in catalyst._protocol.BarData.__getitem__
  File "catalyst/_protocol.pyx", line 211, in catalyst._protocol.BarData._get_equity_price_view
AttributeError: 'NoneType' object has no attribute 'retrieve_asset'
```

I dont understand, because i entered these dates, --start 2016-1-1 --end 2017-9-30 and it says
[2017-10-27 07:21:08.710800] INFO: exchange_bundle: pricing data for [u'btc_usdt'] not found in range 2015-03-01 00:00:00+00:00 to 2017-09-28 00:00:00+00:00, updating the bundles. and then give an AttributeError: 'NoneType' object has no attribute 'retrieve_asset'.

**Comment by mutkan** [comment]
Could you open the issue again? @lacabra

**Comment by lacabra** [comment]
As you mention `SymbolNotFoundOnExchange:  Symbol BTC_USD not found on exchange Poloniex.` that's a legit error because Poloniex uses `USDT` instead of `USD`, so if you change that, it should work fine.

The second error is in the code, you are running an older version of this script. Please see the updated source: https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/buy_and_hodl.py

specifically, change this line in your code (L59):
`price = data[context.asset].price`
to the new version:
`price = data.current(context.asset, 'price')`

and you'll have to make a similar change on L73, or just download the most recent version from the link provided.
