### ISSUE TITLE
catalyst installation error: TypeError: 'ellipsis' object is not iterable

### ISSUE THREAD

**Issue by anandi1989** [enigmampc/catalyst#461]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System:  `Linux ubuntu 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 3.5.2`
* Python Bitness: `('64bit', 'ELF')`
* How did you install Catalyst: (`$ pip install enigma-catalyst matplotlib `)
* Python packages: 
```
alembic==0.9.7
attrdict==2.0.0
bcolz==1.2.1
boto3==1.5.27
botocore==1.8.50
Bottleneck==1.2.1
ccxt==1.17.94
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0.1
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.19
eth-abi==1.2.0
eth-account==0.2.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.1
hexbytes==0.1.0
idna==2.6
intervaltree==2.1.0
jmespath==0.9.3
kiwisolver==1.0.1
Logbook==0.12.5
lru-dict==1.1.6
lxml==4.2.5
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.3
multipledispatch==0.4.9
networkx==2.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
parsimonious==0.8.0
patsy==0.5.0
pycryptodome==3.6.6
pyparsing==2.2.0
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2016.4
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.2
s3transfer==0.1.13
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
urllib3==1.22
web3==4.4.1
websockets==5.0.1
wrapt==1.10.11
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* After successful installation of `enigma-catalyst` I typed `catalyst --version` in my `virtualenv`  and I got below error:
```
(catalyst-venv) root@ubuntu:/home/amitn/Documents/Personal/myProject# catalyst --version
Traceback (most recent call last):
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/bin/catalyst", line 7, in <module>
    from catalyst.__main__ import main
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/catalyst/__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/catalyst/utils/run_algo.py", line 16, in <module>
    from catalyst.exchange.exchange_pricing_loader import ExchangePricingLoader, \
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/catalyst/exchange/exchange_pricing_loader.py", line 17, in <module>
    from catalyst.exchange.utils.factory import get_exchange
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/catalyst/exchange/utils/factory.py", line 4, in <module>
    from catalyst.exchange.ccxt.ccxt_exchange import CCXT
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 7, in <module>
    import ccxt
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/ccxt/base/exchange.py", line 78, in <module>
    from web3 import Web3, HTTPProvider
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_keys/__init__.py", line 15, in <module>
    from .main import (  # noqa: F401
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_keys/main.py", line 3, in <module>
    from eth_keys.datatypes import (
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_keys/datatypes.py", line 8, in <module>
    from eth_utils import (
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_utils/__init__.py", line 24, in <module>
    from .applicators import (  # noqa: F401
  File "/home/amitn/Documents/Personal/myProject/catalyst-venv/lib/python3.5/site-packages/eth_utils/applicators.py", line 43, in <module>
    def combine_argument_formatters(*formatters: List[Callable[..., Any]]) -> Formatters:
  File "/usr/lib/python3.5/typing.py", line 1025, in __getitem__
    tvars = _type_vars(params)
  File "/usr/lib/python3.5/typing.py", line 284, in _type_vars
    _get_type_vars(types, tvars)
  File "/usr/lib/python3.5/typing.py", line 279, in _get_type_vars
    t._get_type_vars(tvars)
  File "/usr/lib/python3.5/typing.py", line 786, in _get_type_vars
    _get_type_vars(self.__args__, tvars)
  File "/usr/lib/python3.5/typing.py", line 277, in _get_type_vars
    for t in types:
TypeError: 'ellipsis' object is not iterable
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

I followed all the steps that mentioned [here](https://enigma.co/catalyst/install.html) and [here](https://enigma.co/catalyst/install.html#linux)

## What steps have you taken to resolve this already?

I googled it and as per my understanding this error is related to `matplotlib`

# Anything else?

Any help will be highly appreciated. 

Sincerely,
`anandi1989`

**Comment by lenak25** [comment]
Hi @anandi1989 ,

It seems it is related to your [Python version](https://github.com/ethereum/web3.py/issues/1012).

We encourage users to use Python3 to be able to use the [marketplace](https://enigma.co/marketplace/) functionality. If you plan to use it, I would suggest to upgrade your Python version, otherwise you can try using Python2.7.

Lena

**Comment by anandi1989** [comment]
I am able to run it sucessfully with `pipenv` for `python 2.7` however I am facing same issue as I mentioned above for `python 3.5` even with `pipenv`

**Comment by lenak25** [comment]
It seems that this issue is specific to Python 3.5.2 (look at the link in the previous message).
If you want to use Python 3, consider upgrading to `3.5.3`+ or using 3.5.1

**Comment by Namburger** [comment]
I believe this is a python version error, not catalyst. It lays with in /usr/lib/python3.5/typing.py
Consider upgrading python3
