### ISSUE TITLE
0.5.19 not supporting python 2.7?

### ISSUE THREAD

**Issue by demontamer** [enigmampc/catalyst#465]
Dear Catalyst Maintainers,
is catalyst no longer supporting python 2.7?
(catalyst-venv) mike01@ubuntu-512mb-lon1-01:/var/www/FlaskApp/demonApp$ catalyst run -f rocket_2.py --start 2017-8-18 --end 2018-6-30 -x binance --data-frequency minute  -c btc   --capital-base 0.1
Traceback (most recent call last):
  File "/var/www/FlaskApp/demonApp/catalyst-venv/bin/catalyst", line 7, in <module>
    from catalyst.__main__ import main
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 16, in <module>
    from catalyst.exchange.exchange_pricing_loader import ExchangePricingLoader, \
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/exchange/exchange_pricing_loader.py", line 17, in <module>
    from catalyst.exchange.utils.factory import get_exchange
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/exchange/utils/factory.py", line 4, in <module>
    from catalyst.exchange.ccxt.ccxt_exchange import CCXT
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 7, in <module>
    import ccxt
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/ccxt/base/exchange.py", line 78, in <module>
    from web3 import Web3, HTTPProvider
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/web3/__init__.py", line 5, in <module>
    raise EnvironmentError("Python 3.5 or above is required")
EnvironmentError: Python 3.5 or above is required

Sincerely,
`$demontamer`

**Comment by lenak25** [comment]
Hi @demontamer ,

Catalyst do support Python 2.7.
When you install catalyst in Python 2.7 the web3 library should not be installed as it requires Python 3, but it seems you have it installed for some reason.
I advise you to clean install catalyst using a new virtual environment and then try running your algorithm again.

Lena

**Comment by demontamer** [comment]
Hi, it works for 0.5.18 and I never had this problem. Happy to clean install but this is specific to the current version, so maybe look into that too.

**Comment by lenak25** [comment]
I believe that the reason it didn't happen in prior catalyst releases is that in 0.5.19 release we have upgraded to a later CCXT version (ccxt==1.17.94) which started to use web3. 
Another option perhaps would be to downgrade to the previous CCXT version (ccxt==1.12.131) but it might have implications.

**Comment by lenak25** [comment]
I am closing this. @demontamer feel free to reopen if you continue experiencing an issue with Python 2.7.
