### ISSUE TITLE
Conda env create problem 

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#484]
I encountered this exception when i try to  create a fresh env with the latest environment file.
I have testet this on mac and ubuntu.

The jupyter_nbextensions_configurator requirement(for the cell magic in nb?)  occurs the problem. Without this requirement the installation is working.

```
Requirement already satisfied: testpath in ./anaconda3/envs/catalyst_0_5_20/lib/python3.6/site-packages (from nbconvert->notebook>=4.0->jupyter_nbextensions_configurator==0.4.0->-r condaenv.cajbfptk.requirements.txt (line 34))
Exception:
Traceback (most recent call last):
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2797, in _dep_map
    return self.__dep_map
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2608, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2874, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; extra '"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/req/req_set.py", line 699, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2757, in extras
    return [dep for dep in self._dep_map if dep]
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2799, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2809, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2867, in parse_requirements
    yield Requirement(line)
  File "envs/catalyst_0_5_20/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2876, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"

CondaValueError: pip returned an error


```

**Comment by EmbarAlmog** [comment]
Hi @avolution, I wasn't able to reproduce your issue on MAC. Do you already have an environment called `catalyst` while trying to create a new one? If so, please make sure that the environment does not exist before following these steps: https://enigma.co/catalyst/install.html# (another solution is to change the name of the environment in the YML file by updating the name specified in the first line). Please update me if the problem was resolved.

**Comment by avolution** [comment]
Tested again and it works now.

Maybe a temporary problem with the package manager service.
