### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by gitn00b1337** [enigmampc/catalyst#488]
Hi,

I am unable to run the following command:

   ` catalyst ingest-exchange -x binance -f minute`

I get the error:

> Trying to ingest exchange bundle binance...
>     [                                    ]  Ingesting minute price data on binance:    0%  0d 00:22:43
> Traceback (most recent call last):
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 9, in <module>
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 867, in ingest_exchange
>     csv=csv
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py", line 824, in ingest
>     show_report=show_report
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py", line 643, in ingest_assets
>     cleanup=True
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py", line 365, in ingest_ctable
>     period=period
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\utils\bundle_utils.py", line 47, in get_bcolz_chunk
>     bytes = download_without_progress(url)
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\data\bundles\core.py", line 190, in download_without_progress
>     resp.raise_for_status()
>   File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\requests\models.py", line 935, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-trx_bnb-2018-06.tar.gz

I upgraded via pip as per the documentation and retried but it seems to still be an issue. I am also running cmd as administrator: Windows 10.

Any help would be hugely appreciated, Thanks

**Comment by lenak25** [comment]
Hi @gitn00b1337 ,

Thanks for reporting this! 
The issue was resolved.

Right now, there might be a stale config file in your local system, which you can remove and clean by running `catalyst clean-exchange -x binance`.
Please note that all downloaded Binance historical data will be deleted using the clean-exchange command. Alternatively, you can manually remove the problematic file by deleting ~/.catalyst/data/exchanges/binance/symbols.json file, or wait up to 24h, when it will be re-downloaded automatically.

Thanks again for reporting.

Lena

**Comment by gitn00b1337** [comment]
Hi, I tried this and it seemed to work until I hit 86% done, then I get:

(catalyst) C:\WINDOWS\system32>catalyst ingest-exchange -x binance -f minute
Trying to ingest exchange bundle binance...
    [===============================     ]  Ingesting minute price data on binance:   86%  0d 00:20:09
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 867, in ingest_exchange
    csv=csv
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py", line 824, in ingest
    show_report=show_report
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py", line 643, in ingest_assets
    cleanup=True
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_bundle.py", line 365, in ingest_ctable
    period=period
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\exchange\utils\bundle_utils.py", line 47, in get_bcolz_chunk
    bytes = download_without_progress(url)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\catalyst\data\bundles\core.py", line 190, in download_without_progress
    resp.raise_for_status()
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\catalyst\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-pax_bnb-2018-09.tar.gz

**Comment by lenak25** [comment]
Thanks for reporting back, I am reopening this.

**Comment by lenak25** [comment]
The issue was resolved.

As previously stated, there might be a stale config file in your local system, which you can remove and clean by running `catalyst clean-exchange -x binance`.
Alternatively, you can manually remove the problematic file by deleting ~/.catalyst/data/exchanges/binance/symbols.json file, or wait up to 24h, when it will be re-downloaded automatically.

Thanks again for reporting! 
Please let us know is you still encounter any problems.
