### ISSUE TITLE
Installation ON Windows7 ERROR

### ISSUE THREAD

**Issue by ynzheng** [enigmampc/catalyst#505]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Windows 7 64bit

* Python Version: `$ python --version`
conda update conda
conda install python=3.6
python -m pip install --upgrade pip
$ python --version
Python 3.6.6 :: Anaconda, Inc.

$ which python
/e/Server/ScoopGlobalApps/apps/anaconda3/current/python

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal

* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
Anaconda3 with conda
and python3.6.6
yarn global add windows-build-tools --vs2015
npm install --global --production windows-build-tools --vs2015
yarn --version
1.10.1
npm --version
6.4.1
* Python packages: `$ pip freeze` or `$ conda list`
$ conda list
# packages in environment at E:\Server\ScoopGlobalApps\apps\anaconda3\current:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0
aiodns                    1.1.1                     <pip>
aiohttp                   3.4.4                     <pip>
alabaster                 0.7.12                   py36_0
anaconda-client           1.7.2                    py36_0
anaconda-navigator        1.9.2                    py36_0
anaconda-project          0.8.2                    py36_0
appdirs                   1.4.3            py36h28b3542_0
arrow                     0.12.1                    <pip>
asn1crypto                0.24.0                   py36_0
astroid                   2.0.4                    py36_0
astropy                   3.0.5            py36he774522_0
async-timeout             3.0.0                     <pip>
atomicwrites              1.2.1                    py36_0
attrdict                  2.0.0                     <pip>
attrs                     18.2.0           py36h28b3542_0
automat                   0.7.0                    py36_0
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
backports                 1.0                      py36_1
backports.os              0.1.1                    py36_0
backports.shutil_get_terminal_size 1.0.0                    py36_2
beautifulsoup4            4.6.3                    py36_0
bitarray                  0.8.3            py36hfa6e2cd_0
bkcharts                  0.2              py36h7e685f7_0
blas                      1.0                         mkl
blaze                     0.11.3                   py36_0
bleach                    3.0.2                    py36_0
blosc                     1.14.4               he51fdeb_0
bokeh                     0.13.0                   py36_0
boto                      2.49.0                   py36_0
bottleneck                1.2.1            py36h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
cachetools                2.1.0                     <pip>
ccxt                      1.17.375                  <pip>
certifi                   2018.10.15               py36_0
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
click                     7.0                      py36_0
cloudpickle               0.6.1                    py36_0
clyent                    1.2.2                    py36_1
coinmarketcap             5.0.3                     <pip>
colorama                  0.4.0                    py36_0
comtypes                  1.1.7                    py36_0
conda                     4.5.11                   py36_0
conda-build               3.16.1                   py36_0
conda-env                 2.6.0                h36134e3_1
config                    0.4.0                     <pip>
console_shortcut          0.1.1                         3
constantly                15.1.0           py36h28b3542_0
contextlib2               0.5.5            py36he5d52c0_0
coverage                  4.5.1                     <pip>
cryptography              2.3.1            py36h74b6da3_0
curl                      7.61.0               h7602738_0
cycler                    0.10.0           py36h009560c_0
cython                    0.29             py36ha925a31_0
cytoolz                   0.9.0.1          py36hfa6e2cd_1
dask                      0.19.4                   py36_0
dask-core                 0.19.4                   py36_0
datashape                 0.5.4                    py36_1
decorator                 4.3.0                    py36_0
defusedxml                0.5.0                    py36_1
distributed               1.23.3                   py36_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3                    py36_2
et_xmlfile                1.0.1            py36h3d2d736_0
eth-abi                   1.2.0                     <pip>
eth-account               0.3.0                     <pip>
eth-hash                  0.2.0                     <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b3                   <pip>
eth-rlp                   0.1.2                     <pip>
eth-typing                1.3.0                     <pip>
eth-utils                 1.2.2                     <pip>
fastcache                 1.0.2            py36hfa6e2cd_2
filelock                  3.0.9                    py36_0
flask                     1.0.2                    py36_1
flask-cors                3.0.6                    py36_0
freetype                  2.9.1                ha9979f8_1
freqtrade                 0.17.3                    <pip>
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.7            py36he774522_0
glob2                     0.6                      py36_1
greenlet                  0.4.15           py36hfa6e2cd_0
h5py                      2.8.0            py36h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py36_2
hexbytes                  0.1.0                     <pip>
html5lib                  1.0.1                    py36_0
hyperlink                 18.0.0                   py36_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_0
idna-ssl                  1.1.0                     <pip>
imageio                   2.4.1                    py36_0
imagesize                 1.1.0                    py36_0
importlib_metadata        0.6                      py36_0
incremental               17.5.0                   py36_0
intel-openmp              2019.0                      118
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.0.1            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.2                    py36_0
isort                     4.3.4                    py36_0
itsdangerous              0.24                     py36_1
jdcal                     1.4                      py36_0
jedi                      0.13.1                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.3                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.4.0                    py36_0
jupyterlab                0.35.1                   py36_0
jupyterlab_launcher       0.13.1                   py36_0
jupyterlab_server         0.2.0                    py36_0
keyring                   15.1.0                   py36_0
kiwisolver                1.0.1            py36h6538335_0
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libarchive                3.3.3                h798a506_1
libcurl                   7.61.0               h7602738_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                hd619d38_4
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.25.0                   py36_0
locket                    0.2.0            py36hfed976d_1
lru-dict                  1.1.6                     <pip>
lxml                      4.2.5            py36hef2cd61_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py36hfa6e2cd_1
matplotlib                3.0.0            py36hd159220_0
mccabe                    0.6.1                    py36_1
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.8.4            py36he774522_0
mkl                       2019.0                      118
mkl-service               1.1.2            py36hb217b18_5
mkl_fft                   1.0.6            py36hdbbee80_0
mkl_random                1.0.1            py36h77b88f5_1
more-itertools            4.3.0                    py36_0
mpmath                    1.0.0                    py36_2
msgpack-python            0.5.6            py36he980bc4_1
msys2-conda-epoch         20160418                      1
multidict                 4.4.2                     <pip>
multipledispatch          0.6.0                    py36_0
navigator-updater         0.2.1                    py36_0
nbconvert                 5.4.0                    py36_1
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.2                      py36_1
nltk                      3.3.0                    py36_0
nose                      1.3.7                    py36_2
notebook                  5.7.0                    py36_0
numba                     0.40.0           py36hf9181ef_0
numexpr                   2.6.8            py36h9ef55f4_0
numpy                     1.15.2                    <pip>
numpy                     1.15.2           py36ha559c80_0
numpy-base                1.15.2           py36h8128ebf_0
numpydoc                  0.8.0                    py36_0
odo                       0.5.1            py36h7560279_0
olefile                   0.46                     py36_0
openpyxl                  2.5.8                    py36_0
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                     py36_0
pandas                    0.23.4                    <pip>
pandas                    0.23.4           py36h830ac7b_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                    py36_1
parsimonious              0.8.0                     <pip>
parso                     0.3.1                    py36_0
partd                     0.3.9                    py36_0
path.py                   11.5.0                   py36_0
pathlib2                  2.3.2                    py36_0
patsy                     0.5.0                    py36_0
pep8                      1.7.1                    py36_0
pickleshare               0.7.5                    py36_0
pillow                    5.3.0            py36hdc69c19_0
pip                       18.1                      <pip>
pip                       10.0.1                   py36_0
pkginfo                   1.4.2                    py36_1
pluggy                    0.7.1            py36h28b3542_0
ply                       3.11                     py36_0
prometheus_client         0.4.2                    py36_0
prompt_toolkit            2.0.6                    py36_0
psutil                    5.4.7            py36hfa6e2cd_0
py                        1.7.0                    py36_0
pyasn1                    0.4.4            py36h28b3542_0
pyasn1-modules            0.2.2                    py36_0
pycares                   2.3.0                     <pip>
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.19                     py36_0
pycrypto                  2.6.1            py36hfa6e2cd_9
pycryptodome              3.6.6                     <pip>
pycurl                    7.43.0.2         py36h74b6da3_0
pyflakes                  2.0.0                    py36_0
pygments                  2.2.0            py36hb010967_0
pyhamcrest                1.9.0                    py36_2
pylint                    2.1.1                    py36_0
pyodbc                    4.0.24           py36h6538335_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.2                    py36_0
pypiwin32                 223                       <pip>
pyqt                      5.9.2            py36h6538335_2
PyQt4                     4.11.4                    <pip>
pysocks                   1.6.8                    py36_0
pytables                  3.4.4            py36he6f6034_0
pytest                    3.8.2                    py36_0
pytest                    3.8.2                     <pip>
pytest-arraydiff          0.2              py36h39e3cac_0
pytest-astropy            0.4.0                    py36_0
pytest-asyncio            0.9.0                     <pip>
pytest-cov                2.6.0                     <pip>
pytest-doctestplus        0.1.3                    py36_0
pytest-mock               1.10.0                    <pip>
pytest-openfiles          0.3.0                    py36_0
pytest-remotedata         0.3.0                    py36_0
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.3                    py36_0
python-libarchive-c       2.8                      py36_6
python-telegram-bot       11.1.0                    <pip>
pyti                      0.2.2                     <pip>
pytz                      2018.5                   py36_0
pywavelets                1.0.1            py36h8c2d366_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.4                    py36_0
pyyaml                    3.13             py36hfa6e2cd_0
pyzmq                     17.1.2           py36hfa6e2cd_0
qt                        5.9.6            vc14h1e9a669_2  [vc14]
qtawesome                 0.5.1                    py36_1
qtconsole                 4.4.2                    py36_0
qtpy                      1.5.1                    py36_0
requests                  2.19.1                   py36_0
requests-cache            0.4.13                    <pip>
retrying                  1.3.3                     <pip>
rlp                       1.0.3                     <pip>
rope                      0.11.0                   py36_0
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-image              0.14.0           py36h6538335_1
scikit-learn              0.20.0                    <pip>
scikit-learn              0.20.0           py36heebcf9a_1
scikit-optimize           0.5.2                     <pip>
scipy                     1.1.0                     <pip>
scipy                     1.1.0            py36h4f6bf74_1
seaborn                   0.9.0                    py36_0
send2trash                1.5.0                    py36_0
service_identity          17.0.0           py36h28b3542_0
setuptools                40.4.3                   py36_0
simplegeneric             0.8.1                    py36_2
simplejson                3.16.0                    <pip>
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.19.8           py36h6538335_0
six                       1.11.0                   py36_1
sklearn                   0.0                       <pip>
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         1.0.1                    py36_0
sortedcontainers          2.0.5                    py36_0
sphinx                    1.8.1                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder                    3.3.1                    py36_1
spyder-kernels            0.2.6                    py36_0
sqlalchemy                1.2.12           py36he774522_0
sqlite                    3.24.0               h7602738_0
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.3                      py36_0
TA-Lib                    0.4.17                    <pip>
tabulate                  0.8.2                     <pip>
tblib                     1.3.2            py36h30f5020_0
technical                 1.0.2                     <pip>
terminado                 0.8.1                    py36_1
testpath                  0.4.2                    py36_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py36_0
tornado                   5.1.1            py36hfa6e2cd_0
tqdm                      4.26.0           py36h28b3542_0
traitlets                 4.3.2            py36h096827d_0
twisted                   18.9.0           py36he774522_0
typed-ast                 1.1.0            py36hfa6e2cd_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.23                      <pip>
urllib3                   1.23                     py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7            py36h3d5aa90_0
web3                      4.6.0                     <pip>
webencodings              0.5.1                    py36_1
websockets                6.0                       <pip>
werkzeug                  0.14.1                   py36_0
wheel                     0.32.1                   py36_0
widgetsnbextension        3.4.2                    py36_0
win_inet_pton             1.0.1                    py36_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py36hfa6e2cd_2
xlrd                      1.1.0                    py36_1
xlsxwriter                1.1.1                    py36_0
xlwings                   0.12.1                   py36_0
xlwt                      1.3.0            py36h1a4751e_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yarl                      1.1.0                     <pip>
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                    py36_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py36_1
zope.interface            4.5.0            py36hfa6e2cd_0
zstd                      1.3.3                hfe6a214_0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
**Installation failed** 

**LOGS**

Building wheels for collected packages: alembic, bcolz, bottleneck, cyordereddict, cytoolz, empyrical, enigma-catalyst, idna-ssl, intervaltree, lru-dict, mako, networkx, python-editor, redo, requests-ftp, rlp, sqlalchemy, statsmodels, toolz, wrapt, MarkupSafe
  Running setup.py bdist_wheel for alembic ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\0f\20\7b\f3b84b4dd67018759f34eeeabc4d8e2b3f196e76ded9707650
  Running setup.py bdist_wheel for bcolz ... error
  **Failed building wheel for bcolz**
  Running setup.py clean for bcolz
  Running setup.py bdist_wheel for bottleneck ... error
  Failed building wheel for bottleneck
  Running setup.py clean for bottleneck
  Running setup.py bdist_wheel for cyordereddict ... error
  Failed building wheel for cyordereddict
  Running setup.py clean for cyordereddict
  Failed cleaning build dir for cyordereddict
  Running setup.py bdist_wheel for cytoolz ... error
  Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
  Failed cleaning build dir for cytoolz
  Running setup.py bdist_wheel for empyrical ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\c5\80\7d\d1aa107947d9ffa50ba601c5f2fabc238dad567cbf5c4291ce
  Running setup.py bdist_wheel for enigma-catalyst ... error
  Failed building wheel for enigma-catalyst
  Running setup.py clean for enigma-catalyst
  Failed cleaning build dir for enigma-catalyst
  Running setup.py bdist_wheel for idna-ssl ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\af\8d\34\de932e859862fb26852cbc1eb160ed23e9d9371e3dc1ffb69c
  Running setup.py bdist_wheel for intervaltree ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\6b\cf\b0\f7ef2d0f504d26f3e9e70c2369e5725591ccfaf67d528fcbc5
  Running setup.py bdist_wheel for lru-dict ... error
  Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
  Running setup.py bdist_wheel for mako ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\15\35\25\dbcb848832ccb1a4b4ad23f529badfd3bce9bf88017f7ca510
  Running setup.py bdist_wheel for networkx ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\44\c0\34\6f98693a554301bdb405f8d65d95bbcd3e50180cbfdd98a94e
  Running setup.py bdist_wheel for python-editor ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\36\e0\98\ba386b125a00ea9dd52e2c16aa2ec0adbbd639b84bfe2e001d
  Running setup.py bdist_wheel for redo ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\56\ba\a6\53a8ef0222ed874ef40c9d191acf3d6a239f379121059dde8b
  Running setup.py bdist_wheel for requests-ftp ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\2a\98\32\37195e45a3392a73d9f65c488cbea30fe5bad76aaef4d6b020
  Running setup.py bdist_wheel for rlp ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\19\ef\a7\5ff173b7e5fadb921642a73fae9df86128fe26a35818cd9c85
  Running setup.py bdist_wheel for sqlalchemy ... error
  Failed building wheel for sqlalchemy
  Running setup.py clean for sqlalchemy
  Running setup.py bdist_wheel for statsmodels ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\d9\58\cf\87cbd88032d70c0a3d5f3ab657d32961186bb61ed6d9587621
  Running setup.py bdist_wheel for toolz ... done
  Stored in directory: C:\Users\zyn\AppData\Local\pip\Cache\wheels\f4\0c\f6\ce6b2d1aa459ee97cc3c0f82236302bd62d89c86c700219463
  Running setup.py bdist_wheel for wrapt ... error
  Failed building wheel for wrapt
  Running setup.py clean for wrapt
  Failed cleaning build dir for wrapt
  Running setup.py bdist_wheel for MarkupSafe ... error
  Failed building wheel for MarkupSafe
  Running setup.py clean for MarkupSafe
Successfully built alembic empyrical idna-ssl intervaltree mako networkx python-editor redo requests-ftp rlp statsmodels toolz
Failed to build bcolz bottleneck cyordereddict cytoolz enigma-catalyst lru-dict sqlalchemy wrapt MarkupSafe
Installing collected packages: pycares, aiodns, idna, idna-ssl, attrs, async-timeout, chardet, multidict, yarl, aiohttp, sqlalchemy, MarkupSafe, mako, python-editor, alembic, attrdict, bcolz, docutils, jmespath, botocore, s3transfer, boto3, bottleneck, cchardet, urllib3, requests, toolz, cytoolz, eth-hash, eth-utils, hexbytes, parsimonious, eth-abi, websockets, lru-dict, pycryptodome, eth-keys, eth-keyfile, rlp, eth-rlp, eth-account, pywin32, pypiwin32, web3, setuptools, ccxt, click, contextlib2, cyordereddict, cython, pytz, pandas, empyrical, logbook, requests-file, lxml, requests-ftp, wrapt, pandas-datareader, patsy, statsmodels, decorator, networkx, numexpr, multipledispatch, sortedcontainers, intervaltree, tables, redo, requests-toolbelt, enigma-catalyst, pysha3, virtualenv
  Running setup.py install for sqlalchemy ... error
Exception:
Traceback (most recent call last):
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 2: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 2: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\zyn\\AppData\\Local\\Temp\\pip-build-zh1juah7\\bcolz\\.eggs\\Cython-0.29-py3.6-win-amd64.egg\\Cython\\Compiler\\Scanning.cp36-win_amd64.pyd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more times]
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "E:\Server\ScoopGlobalApps\apps\anaconda3\current\envs\catalyst\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\zyn\\AppData\\Local\\Temp\\pip-build-zh1juah7\\bcolz\\.eggs\\Cython-0.29-py3.6-win-amd64.egg\\Cython\\Compiler\\Scanning.cp36-win_amd64.pyd'

CondaValueError: pip returned an error

**Comment by AvishaiW** [comment]
Hi, 
Sorry on the late response..
Can you please share the command you ran leading to these errors?
Thanks!
