### ISSUE TITLE
cannot install in python3.6 

### ISSUE THREAD

**Issue by studyquant** [enigmampc/catalyst#515]
Dear Catalyst Maintainers,
      I have tried to install catalyst several times, it always fail.  Really need help. Python 3.6 version.  please
Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ 3.6 python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
install sucessfully
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.    conda create python36 
2.    pip install enigma-catalyst matplotlib
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by studyquant** [comment]
I have installed the catalyst.  While, when i import it.   it shows runfile('C:/Anaconda3-4.2/lib/site-packages/catalyst/utils/run_algo.py', wdir='C:/Anaconda3-4.2/lib/site-packages/catalyst/utils')
Traceback (most recent call last):

  File "<ipython-input-5-f14068f4e4f2>", line 1, in <module>
    runfile('C:/Anaconda3-4.2/lib/site-packages/catalyst/utils/run_algo.py', wdir='C:/Anaconda3-4.2/lib/site-packages/catalyst/utils')

  File "C:\Anaconda3-4.2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3-4.2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Anaconda3-4.2/lib/site-packages/catalyst/utils/run_algo.py", line 13, in <module>
    import catalyst

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\utils\run_algo.py", line 16, in <module>
    from catalyst.exchange.exchange_pricing_loader import ExchangePricingLoader, \

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\exchange\exchange_pricing_loader.py", line 17, in <module>
    from catalyst.exchange.utils.factory import get_exchange

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\exchange\utils\factory.py", line 4, in <module>
    from catalyst.exchange.ccxt.ccxt_exchange import CCXT

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\exchange\ccxt\ccxt_exchange.py", line 7, in <module>
    import ccxt

  File "C:\Anaconda3-4.2\lib\site-packages\ccxt\__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401

  File "C:\Anaconda3-4.2\lib\site-packages\ccxt\base\__init__.py", line 24, in <module>
    from ccxt.base import exchange

  File "C:\Anaconda3-4.2\lib\site-packages\ccxt\base\exchange.py", line 78, in <module>
    from web3 import Web3, HTTPProvider

  File "C:\Anaconda3-4.2\lib\site-packages\web3\__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402

  File "C:\Anaconda3-4.2\lib\site-packages\eth_account\__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401

  File "C:\Anaconda3-4.2\lib\site-packages\eth_account\account.py", line 10, in <module>
    from eth_keyfile import (

  File "C:\Anaconda3-4.2\lib\site-packages\eth_keyfile\__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401

  File "C:\Anaconda3-4.2\lib\site-packages\eth_keyfile\keyfile.py", line 10, in <module>
    from eth_keys import keys

  File "C:\Anaconda3-4.2\lib\site-packages\eth_keys\__init__.py", line 15, in <module>
    from .main import (  # noqa: F401

  File "C:\Anaconda3-4.2\lib\site-packages\eth_keys\main.py", line 3, in <module>
    from eth_keys.datatypes import (

  File "C:\Anaconda3-4.2\lib\site-packages\eth_keys\datatypes.py", line 8, in <module>
    from eth_utils import (

  File "C:\Anaconda3-4.2\lib\site-packages\eth_utils\__init__.py", line 24, in <module>
    from .applicators import (  # noqa: F401

  File "C:\Anaconda3-4.2\lib\site-packages\eth_utils\applicators.py", line 29, in <module>
    def combine_argument_formatters(*formatters: List[Callable[..., Any]]) -> Formatters:

  File "C:\Anaconda3-4.2\lib\typing.py", line 1025, in __getitem__
    tvars = _type_vars(params)

  File "C:\Anaconda3-4.2\lib\typing.py", line 284, in _type_vars
    _get_type_vars(types, tvars)

  File "C:\Anaconda3-4.2\lib\typing.py", line 279, in _get_type_vars
    t._get_type_vars(tvars)

  File "C:\Anaconda3-4.2\lib\typing.py", line 786, in _get_type_vars
    _get_type_vars(self.__args__, tvars)

  File "C:\Anaconda3-4.2\lib\typing.py", line 277, in _get_type_vars
    for t in types:

TypeError: 'ellipsis' object is not iterable

**Comment by lenak25** [comment]
Hi @studyquant , 

The error you received seems to be the same discussed at #461, which resulted from a problematic Python version.
If after upgrading to Python `3.5.3+` or using `3.5.1` you still experience this issue, please share the following information:
1. Your operating system 
2. Python version
3. Catalyst version

Lena

**Comment by studyquant** [comment]
Thanks, I have sucessfully instelled the catalyst
