### ISSUE TITLE
ExchangeRequestError: Request failed: {error} failed to run backtest strategy

### ISSUE THREAD

**Issue by studyquant** [enigmampc/catalyst#516]
Dear Catalyst Maintainers,

I am installed the Catalyst version 0.5.21. and ingested the data daily and minutes data.  

I am trying to run example strategies. 

For example,
buy _ btc_ symple.py 

from catalyst import run_algorithm
from catalyst.api import order, record, symbol
import pandas as pd

def initialize(context):
    context.asset = symbol('btc_usdt')

def handle_data(context, data):
    order(context.asset, 1)
    record(btc=data.current(context.asset, 'price'))

if __name__ == '__main__':
    run_algorithm(
        capital_base=10000,
        data_frequency='daily',
        initialize=initialize,
        handle_data=handle_data,
        exchange_name='poloniex',
        algo_namespace='buy_btc_simple',
        quote_currency='usdt',
        start=pd.to_datetime('2017-03-01', utc=True),
        end=pd.to_datetime('2017-10-31', utc=True),
    )

The error shows it cannot connect to ccxt. While, I do not understand, for backtesting, why it needs to connect to ccxt.. However, How can i solve this issue.   By adding my exchange api key and secret?  where should i add to?

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
[2018-11-18 16:36:42.851385] INFO: run_algo: Catalyst version 0.5.21
[2018-11-18 16:36:42.853380] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-11-18 16:36:45.857004] INFO: run_algo: running algo in backtest mode
[2018-11-18 16:36:46.752684] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
[2018-11-18 16:36:56.764575] WARNING: CCXT: unable to fetch markets poloniex: poloniex https://poloniex.com/public?command=returnTicker GET HTTPSConnectionPool(host='poloniex.com', port=443): Max retries exceeded with url: /public?command=returnTicker (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Traceback (most recent call last):

  File "<ipython-input-1-d83a168a0003>", line 1, in <module>
    runfile('C:/浑度/catalyst/catalyst-master/catalyst/examples/buy_btc_simple.py', wdir='C:/浑度/catalyst/catalyst-master/catalyst/examples')

  File "C:\Anaconda3-4.2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3-4.2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/浑度/catalyst/catalyst-master/catalyst/examples/buy_btc_simple.py", line 48, in <module>
    end=pd.to_datetime('2017-10-31', utc=True),

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\utils\run_algo.py", line 643, in run_algorithm
    stats_output=stats_output

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\utils\run_algo.py", line 361, in _run
    overwrite_sim_params=False,

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 403, in run
    data, overwrite_sim_params

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 360, in run
    data, overwrite_sim_params

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\algorithm.py", line 648, in run
    self.trading_environment.asset_finder.sids

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\exchange\exchange_asset_finder.py", line 25, in sids
    exchange.init()

  File "C:\Anaconda3-4.2\lib\site-packages\catalyst\exchange\ccxt\ccxt_exchange.py", line 136, in init
    raise ExchangeRequestError(error=e)

ExchangeRequestError: Request failed: {error}

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
Hi @studyquant ,

As part of catalyst initialization process - both in live and in backetest - the exchange's markets are being loaded, using `CCXT`.
It seems you have an issue with connecting to Poloniex - no need for the api key (it is only required for live). Have you been able to follow [the link ](https://poloniex.com/public?command=returnTicker) on your browser?
I would suggest trying another exchange.

Lena

**Comment by studyquant** [comment]
I changed the exchange, it is fine now.  While, I have backtest the local data successfully, While, I have questions that , whether catalyst backtest supports futures backtest.  It will automatically understand the short and open ?
