### ISSUE TITLE
Binance Paper trading not working with ValueError

### ISSUE THREAD

**Issue by sgwanlee** [enigmampc/catalyst#522]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Mac 10.14
* Python Version:  Python 3.6.5
* Python Bitness: 64
* How did you install Catalyst: pip
* Python packages: `$ pip freeze` or `$ conda list`
`aiodns==1.1.1
aiohttp==3.4.4
alembic==0.9.7
appnope==0.1.0
async-timeout==3.0.1
attrdict==2.0.0
attrs==18.2.0
backcall==0.1.0
bcolz==1.2.1
bleach==3.0.2
boto3==1.5.27
botocore==1.8.50
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.17.94
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0.1
decorator==4.3.0
defusedxml==0.5.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.21
entrypoints==0.2.3
eth-abi==1.2.2
eth-account==0.2.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.3.0
hexbytes==0.1.0
idna==2.7
idna-ssl==1.1.0
intervaltree==2.1.0
ipykernel==5.1.0
ipython==7.1.1
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.1
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==6.0.0
jupyter-core==4.4.0
kiwisolver==1.0.1
Logbook==0.12.5
lru-dict==1.1.6
lxml==4.2.5
Mako==1.0.7
MarkupSafe==1.0
matplotlib==3.0.2
mistune==0.8.4
multidict==4.5.0
multipledispatch==0.4.9
nbconvert==5.4.0
nbformat==4.4.0
networkx==2.1
notebook==5.7.2
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.3.1
patsy==0.5.0
pexpect==4.6.0
pickleshare==0.7.5
prometheus-client==0.4.2
prompt-toolkit==2.0.7
ptyprocess==0.6.0
pycares==2.3.0
pycryptodome==3.7.0
Pygments==2.3.0
pyparsing==2.3.0
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2016.4
pyzmq==17.1.2
qtconsole==4.4.3
redo==2.0.1
requests==2.20.1
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.3
s3transfer==0.1.13
scipy==1.0.0
Send2Trash==1.5.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
TA-Lib==0.4.17
tables==3.4.2
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==5.1.1
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
web3==4.4.1
webencodings==0.5.1
websockets==5.0.1
widgetsnbextension==3.4.2
wrapt==1.10.11
yarl==1.1.0
`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
paper-mode trading on binance
* What happened instead?
got error like below

`Traceback (most recent call last):
  File "example/momentum.py", line 253, in <module>
    capital_base=1000
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 643, in run_algorithm
    stats_output=stats_output
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 361, in _run
    overwrite_sim_params=False,
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 1052, in run
    data, overwrite_sim_params
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 360, in run
    data, overwrite_sim_params
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 658, in get_generator
    self._init_trading_client()
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 651, in _init_trading_client
    benchmark_source=self._create_benchmark_source(),
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/algorithm.py", line 574, in _create_benchmark_source
    benchmark_returns=benchmark_returns,
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/sources/benchmark_source.py", line 49, in __init__
    self.data_portal
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/sources/benchmark_source.py", line 161, in _initialize_precalculated_series
    ffill=True
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 97, in get_history_window
    ffill))
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/redo/__init__.py", line 165, in retry
    return action(*args, **kwargs)
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 71, in _get_history_window
    ffill)
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 220, in get_exchange_history_window
    False)
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/exchange.py", line 543, in get_history_window
    end_dt=forward_fill_till_dt)
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/catalyst/exchange/utils/exchange_utils.py", line 793, in get_candles_df
    rounded_end_dt = end_dt.floor(freq)
  File "pandas/tslib.pyx", line 460, in pandas.tslib.Timestamp.floor (pandas/tslib.c:11368)
  File "pandas/tslib.pyx", line 424, in pandas.tslib.Timestamp._round (pandas/tslib.c:10794)
  File "/Users/seonggwanlee/git/catalyst/catalyst-venv/lib/python3.6/site-packages/pandas/tseries/offsets.py", line 512, in nanos
    raise ValueError("{0} is a non-fixed frequency".format(self))
ValueError: <MonthEnd> is a non-fixed frequency`

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

`$ python strategy.py`

`   

def initialize(context):
    # Portfolio assets list
    context.asset = symbol('btc_usdt')  # Bitcoin on Poloniex
....

if __name__ == '__main__':

 # Paper trading
    run_algorithm(
        analyze=analyze,
        initialize=initialize,
        handle_data=handle_data,
        exchange_name='binance',
        algo_namespace=NAMESPACE,
        quote_currency='usdt',
        live=True,
        simulate_orders=True,
        capital_base=1000
    )`

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by sgwanlee** [comment]
I got the answer. I've been using the same code as backtest.
I removed the following codes from initialize function and it works.

`
set_benchmark(context.asset)
set_commission(0.001, 0.001)
`

I'm gonna close this issue.
