### ISSUE TITLE
RuntimeWarning: invalid value encountered in greater

### ISSUE THREAD

**Issue by Industrial** [enigmampc/catalyst#532]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux Zippy 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: Conda
* Python packages:
```
# packages in environment at /home/tom/anaconda3/envs/catalyst:
#
# Name                    Version                   Build  Channel
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcolz                     1.2.1                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h1d4fec5_0
cchardet                  2.1.1                     <pip>
ccxt                      1.17.94                   <pip>
certifi                   2018.1.18                py36_0    conda-forge
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                     py_1    conda-forge
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.21                    <pip>
entrypoints               0.3                   py36_1000    conda-forge
eth-abi                   1.1.1                     <pip>
eth-account               0.2.2                     <pip>
eth-hash                  0.1.3                     <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b3                   <pip>
eth-rlp                   0.1.2                     <pip>
eth-utils                 1.0.3                     <pip>
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
glib                      2.53.6               h5d9569c_2
gmp                       6.1.2             hf484d3e_1000    conda-forge
gst-plugins-base          1.12.4               h33fb286_0
gstreamer                 1.12.4               hb53b477_0
hexbytes                  0.1.0                     <pip>
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.6                       <pip>
idna-ssl                  1.0.0                     <pip>
intel-openmp              2018.0.0                      8
intervaltree              2.1.0                     <pip>
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                     <pip>
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter-contrib-core      0.3.3                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           5.2.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
markupsafe                1.1.0           py36h14c3975_1000    conda-forge
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2                    py36_1    conda-forge
mistune                   0.8.4           py36h14c3975_1000    conda-forge
mkl                       2018.0.1             h19d6760_4
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.1                       <pip>
notebook                  5.7.4                 py36_1000    conda-forge
numexpr                   2.6.4                     <pip>
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2n                        0    conda-forge
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandoc                    2.5                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parsimonious              0.8.0                     <pip>
parso                     0.3.1                      py_0    conda-forge
patsy                     0.5.0                     <pip>
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       9.0.1                    py36_1    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pycares                   2.3.0                     <pip>
pycryptodome              3.6.1                     <pip>
pygments                  2.3.1                      py_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
pyrsistent                0.14.9          py36h14c3975_1000    conda-forge
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc3d631a_3
python-dateutil           2.7.5                      py_0    conda-forge
python-editor             1.0.3                     <pip>
pytz                      2016.4                    <pip>
pytz                      2018.9                     py_0    conda-forge
PyYAML                    3.13                      <pip>
pyzmq                     17.1.2          py36h6afc9c9_1001    conda-forge
qt                        5.6.2               hd25b39d_14
qtconsole                 4.4.3                      py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
redo                      2.0.1                     <pip>
requests                  2.20.1                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                    <pip>
setuptools                38.4.0                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0               h1bed415_0
statsmodels               0.8.0                     <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                     <pip>
tornado                   5.1.1           py36h14c3975_1000    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
urllib3                   1.22                      <pip>
virtualenv                15.2.0                    <pip>
wcwidth                   0.1.7                      py_1    conda-forge
web3                      4.4.1                     <pip>
webencodings              0.5.1                      py_1    conda-forge
websockets                5.0                       <pip>
wheel                     0.30.0                   py36_2    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11                   <pip>
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xz                        5.2.3                         0    conda-forge
yarl                      1.1.0                     <pip>
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Following the [Beginner Tutorial](https://enigma.co/catalyst/beginner-tutorial.html) but filling in `binance` instead of `bitfinex` and `usdt` instead of `usd`, I get this error: `RuntimeWarning: invalid value encountered in greater`.

* What did you expect to happen? The backtest to run.
* What happened instead? The error thrown.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. `$ catalyst ingest-exchange -x binance -i btc_usdt`
2. `$ catalyst run -f ./first_algorithm.py -x binance --start 2018-1-24 --end 2019-1-24 -c usdt --capital-base 100000 -o first_algorithm_out.pickle`

```
Running in backtesting mode.
[2019-01-24 15:43:26.976977] INFO: run_algo: Catalyst version 0.5.21
[2019-01-24 15:43:26.977089] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2019-01-24 15:43:29.980398] INFO: run_algo: running algo in backtest mode
[2019-01-24 15:43:30.295787] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
[2019-01-24 15:43:31.174019] INFO: Performance: Simulated 366 trading days out of 366.
[2019-01-24 15:43:31.174137] INFO: Performance: first open: 2018-01-24 00:00:00+00:00
[2019-01-24 15:43:31.174233] INFO: Performance: last close: 2019-01-24 23:59:00+00:00
Traceback (most recent call last):
  File "/home/tom/anaconda3/envs/catalyst/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/__main__.py", line 107, in _
    return f(*args, **kwargs)
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/__main__.py", line 294, in run
    stats_output=None,
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 361, in _run
    overwrite_sim_params=False,
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 403, in run
    data, overwrite_sim_params
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 360, in run
    data, overwrite_sim_params
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 247, in transform
    risk_message = algo.perf_tracker.handle_simulation_end()
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/finance/performance/tracker.py", line 470, in handle_simulation_end
    treasury_curves=self.treasury_curves,
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/finance/risk/report.py", line 98, in __init__
    1, start_session, end_session
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/finance/risk/report.py", line 157, in periods_in_range
    algorithm_leverages=self.algorithm_leverages,
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/finance/risk/period.py", line 81, in __init__
    self.calculate_metrics()
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/finance/risk/period.py", line 138, in calculate_metrics
    self.algorithm_returns.values
  File "/home/tom/anaconda3/envs/catalyst/lib/python3.6/site-packages/empyrical/stats.py", line 661, in downside_risk
    mask = downside_diff > 0
RuntimeWarning: invalid value encountered in greater
```

## What steps have you taken to resolve this already?

I don't know where to look / go from here.

Sincerely,

Tom

**Comment by Industrial** [comment]
Never mind, it appears that error is thrown if you misconfigure the start/end dates.
