### ISSUE TITLE
throw error `IndexError: index 1822 is out of bounds for axis 0 with size 1822` on live mode or  paper trading	mode

### ISSUE THREAD

**Issue by chairy11** [enigmampc/catalyst#541]
Dear Catalyst Maintainers,

let me tell you about the issue I am having:

It is ok to run the strategy on backtest mode, but when on live mode, it throw errors as following:
```
$ python my_strategy.py 

[2019-02-24 12:37:22.375168] INFO: run_algo: Catalyst version 0.5.21
[2019-02-24 12:37:22.375404] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2019-02-24 12:37:25.378683] INFO: run_algo: running algo in live-trading mode
Traceback (most recent call last):
  File "my_strategy.py", line 287, in <module>
    end=end_time
  File "/root/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 643, in run_algorithm
    stats_output=stats_output
  File "/root/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 256, in _run
    data_frequency='minute'
  File "/root/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/factory.py", line 70, in create_simulation_parameters
    trading_calendar=trading_calendar,
  File "/root/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/finance/trading.py", line 194, in __init__
    self._end_session, direction="previous"
  File "/root/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/calendars/trading_calendar.py", line 741, in minute_to_session_label
    Given a minute, get the label of its containing session.
  File "/root/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/calendars/trading_calendar.py", line 770, in minute_to_session_label
    current_or_next_session = self.schedule.index[idx]
  File "/root/anaconda3/envs/catalyst/lib/python3.6/site-packages/pandas/tseries/base.py", line 251, in __getitem__
    val = getitem(key)
IndexError: index 1822 is out of bounds for axis 0 with size 1822
```

My strategy `data_frequency = 'minute'`,  and `3H`. I have tried 
1. set frequency to "180T" instead of "3H",  but still not work.  
2. try `catalyst clean-algo -n my_strategy`,  but still not work.  

Can you help me?

My environment:

# Environment

* Operating System: Ubuntu 14.04.5 LTS  Server
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* catalyst version: version 0.5.21 or 0.5.20
* Python packages: 
```
  #
# Name                    Version                   Build  Channel
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     18.2.0                     py_0    conda-forge
attrs                     17.4.0                    <pip>
backcall                  0.1.0                      py_0    conda-forge
bcolz                     1.2.1                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h1d4fec5_0  
cchardet                  2.1.1                     <pip>
ccxt                      1.17.94                   <pip>
certifi                   2018.1.18                py36_0    conda-forge
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                     py_1    conda-forge
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.3.2                      py_0    conda-forge
decorator                 4.3.0                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.21                    <pip>
entrypoints               0.3                   py36_1000    conda-forge
eth-abi                   1.1.1                     <pip>
eth-account               0.2.2                     <pip>
eth-hash                  0.1.3                     <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b3                   <pip>
eth-rlp                   0.1.2                     <pip>
eth-utils                 1.0.3                     <pip>
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
glib                      2.53.6               h5d9569c_2  
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
hexbytes                  0.1.0                     <pip>
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.6                       <pip>
idna-ssl                  1.0.0                     <pip>
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                     <pip>
ipykernel                 5.1.0           py36h24bf2e0_1002    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                     <pip>
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter-contrib-core      0.3.3                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           5.2.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
markupsafe                1.1.0           py36h14c3975_1000    conda-forge
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2                    py36_1    conda-forge
mistune                   0.8.4           py36h14c3975_1000    conda-forge
mkl                       2018.0.1             h19d6760_4  
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.1                       <pip>
notebook                  5.7.4                 py36_1000    conda-forge
numexpr                   2.6.4                     <pip>
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2n                        0    conda-forge
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parsimonious              0.8.0                     <pip>
parso                     0.3.4                      py_0    conda-forge
patsy                     0.5.0                     <pip>
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       19.0.3                    <pip>
pip                       9.0.1                    py36_1    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pycares                   2.3.0                     <pip>
pycryptodome              3.6.1                     <pip>
pygments                  2.3.1                      py_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
pyrsistent                0.14.11          py36h14c3975_0    conda-forge
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc3d631a_3  
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.3                     <pip>
pytz                      2016.4                    <pip>
pytz                      2018.9                     py_0    conda-forge
PyYAML                    3.13                      <pip>
pyzmq                     18.0.0           py36h6afc9c9_0    conda-forge
qt                        5.6.2               hd25b39d_14  
qtconsole                 4.4.3                      py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
redo                      2.0.1                     <pip>
requests                  2.20.1                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                    <pip>
setuptools                38.4.0                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0               h1bed415_0  
statsmodels               0.8.0                     <pip>
TA-Lib                    0.4.17                    <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                     <pip>
tornado                   5.1.1           py36h14c3975_1000    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
urllib3                   1.22                      <pip>
virtualenv                15.2.0                    <pip>
wcwidth                   0.1.7                      py_1    conda-forge
web3                      4.4.1                     <pip>
webencodings              0.5.1                      py_1    conda-forge
websockets                5.0                       <pip>
wheel                     0.30.0                   py36_2    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11                   <pip>
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xz                        5.2.3                         0    conda-forge
yarl                      1.1.0                     <pip>
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

Sincerely,
chairy11

**Comment by chairy11** [comment]
Sorry, I don't know why,  but the strategy runs all right now. So I close this issue. 

Thank you!

**Comment by chairy11** [comment]
Now, I found the this problem was cause by strategy end_time setting.  Just make the end_date earlier will solve this problem.
