### ISSUE TITLE
Ingesting Error on Binance FET_USDT

### ISSUE THREAD

**Issue by lxc-xx** [enigmampc/catalyst#544]
The command I typed in is
`catalyst ingest-exchange -x binance -f minute -i fet_usdt`

The error message is
`
Trying to ingest exchange bundle binance...
    [==================                  ]  Ingesting minute price data on binance:   50%
Traceback (most recent call last):
  File "/home/trade/anaconda2/envs/catalyst/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/__main__.py", line 857, in ingest_exchange
    csv=csv
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_bundle.py", line 824, in ingest
    show_report=show_report
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_bundle.py", line 643, in ingest_assets
    cleanup=True
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_bundle.py", line 365, in ingest_ctable
    period=period
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/utils/bundle_utils.py", line 47, in get_bcolz_chunk
    bytes = download_without_progress(url)
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/data/bundles/core.py", line 190, in download_without_progress
    resp.raise_for_status()
  File "/home/trade/anaconda2/envs/catalyst/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-fet_usdt-2019-02.tar.gz`

Anyone has the same issue?

**Comment by sam31415** [comment]
Same issue.

**Comment by KeisukeAkita** [comment]
I have same issue.

**Comment by zanoo** [comment]
Same issue, again.

**Comment by lenak25** [comment]
Thanks for reporting and sorry for the late response.
The issue in the S3 bucket was fixed.

There might be a stale config file in your local system, which you can remove by running `catalyst clean-exchange -x binance`.
This command will delete all downloaded Binance data, so alternatively, you can manually remove only the problematic file by deleting ~/.catalyst/data/exchanges/binance/symbols.json (or wait up to 24h, when it will be re-downloaded automatically).

**Comment by adisojeda** [comment]
@lenak25 my catalyst has been failing on the  _https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-atom_bnb-2019-04.tar.gz_ file today

**Comment by adisojeda** [comment]
Hello, now _ https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-atom_bnb-2019-04.tar.gz_ is failing with the same error
