### ISSUE TITLE
Cannot Install on Mac with pip

### ISSUE THREAD

**Issue by xavierlu** [enigmampc/catalyst#574]
# Environment

* Operating System: MacOS Catalina
* Python Version: Python 3.7.4
* Python Bitness: 64
* How did you install Catalyst: `pip`
* Python packages: 
```
gcc7==0.0.9
Logbook==1.5.3
MarkupSafe==1.1.1
numpy==1.18.2
```

# Description of Issue

I followed the installation docs (Installing with `pip`) and when i got to `$ pip install enigma-catalyst matplotlib`. The following happens:
```
(catalyst-venv) ➜  Desktop pip install enigma-catalyst
Collecting enigma-catalyst
  Using cached enigma-catalyst-0.5.21.tar.gz (767 kB)
Requirement already satisfied: pip>=7.1.0 in ./catalyst-venv/lib/python3.7/site-packages (from enigma-catalyst) (20.0.2)
Collecting setuptools==38.5.1
  Using cached setuptools-38.5.1-py2.py3-none-any.whl (489 kB)
Collecting Logbook==0.12.5
  Using cached Logbook-0.12.5.tar.gz (166 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/xavierlu/Desktop/catalyst-venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fn/nl9t5pd168l0d8wpqtvynwn40000gn/T/pip-install-1byvnzwp/Logbook/setup.py'"'"'; __file__='"'"'/private/var/folders/fn/nl9t5pd168l0d8wpqtvynwn40000gn/T/pip-install-1byvnzwp/Logbook/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fn/nl9t5pd168l0d8wpqtvynwn40000gn/T/pip-install-1byvnzwp/Logbook/pip-egg-info
         cwd: /private/var/folders/fn/nl9t5pd168l0d8wpqtvynwn40000gn/T/pip-install-1byvnzwp/Logbook/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fn/nl9t5pd168l0d8wpqtvynwn40000gn/T/pip-install-1byvnzwp/Logbook/setup.py", line 57, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/Users/xavierlu/Desktop/catalyst-venv/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## What steps have you taken to resolve this already?
- Upgrading `setuptools`
- Installing `Logbook` with pip
- Tried `$ pip install -r requirements.txt` but the same issue comes up
...

Sincerely,
Xavier

**Comment by MohanVashist1** [comment]
run `pip3 install setuptools==45`

**Comment by LazaroNacif** [comment]
I tried to run `pip3 install setuptools==45` but didn't work, I got the sama problem.
Keeps returning,
`Processing ./Library/Caches/pip/wheels/7d/d6/73/5666f4b95c9cf4b926a00b6ab66229f0f2334d5b8fe38b0352/enigma_catalyst-0.5.21-cp36-cp36m-macosx_10_7_x86_64.whl
Collecting matplotlib
  Using cached matplotlib-3.2.1-cp36-cp36m-macosx_10_9_x86_64.whl (12.4 MB)
Processing ./Library/Caches/pip/wheels/f4/0c/f6/ce6b2d1aa459ee97cc3c0f82236302bd62d89c86c700219463/toolz-0.9.0-cp36-none-any.whl
Collecting certifi==2018.1.18
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151 kB)
     |████████████████████████████████| 151 kB 1.5 MB/s 
Processing ./Library/Caches/pip/wheels/c5/80/7d/d1aa107947d9ffa50ba601c5f2fabc238dad567cbf5c4291ce/empyrical-0.2.1-cp36-none-any.whl
Collecting Logbook==0.12.5
  Using cached Logbook-0.12.5.tar.gz (166 kB)
    ERROR: Command errored out with exit status 1:
     command: /Applications/anaconda3/envs/catalyst/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sl/32v410n91c17wcz2psj42pmm0000gn/T/pip-install-mv041uo9/Logbook/setup.py'"'"'; __file__='"'"'/private/var/folders/sl/32v410n91c17wcz2psj42pmm0000gn/T/pip-install-mv041uo9/Logbook/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/sl/32v410n91c17wcz2psj42pmm0000gn/T/pip-install-mv041uo9/Logbook/pip-egg-info
         cwd: /private/var/folders/sl/32v410n91c17wcz2psj42pmm0000gn/T/pip-install-mv041uo9/Logbook/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sl/32v410n91c17wcz2psj42pmm0000gn/T/pip-install-mv041uo9/Logbook/setup.py", line 57, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Thank you,
Lázaro

**Comment by ShayanJa** [comment]
Try running on python 3.5.9

**Comment by LazaroNacif** [comment]
Thank you for the answer!
