### ISSUE TITLE
unable to install catalyst 

### ISSUE THREAD

**Issue by ququant** [enigmampc/catalyst#577]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: `$ python --3.6.4`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Unable to install using pip install enigma-catalyst matplotlib
```
(catalyst) C:\Users\pursu>pip install enigma-catalyst matplotlib
Collecting enigma-catalyst
  Using cached enigma-catalyst-0.5.21.tar.gz (767 kB)
Collecting matplotlib
  Downloading matplotlib-3.2.1-cp36-cp36m-win_amd64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 3.2 MB/s
Requirement already satisfied: pip>=7.1.0 in c:\users\pursu\anaconda3\envs\catalyst\lib\site-packages (from enigma-catalyst) (20.0.2)
Collecting setuptools==38.5.1
  Using cached setuptools-38.5.1-py2.py3-none-any.whl (489 kB)
Collecting Logbook==0.12.5
  Using cached Logbook-0.12.5.tar.gz (166 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\pursu\Anaconda3\envs\catalyst\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pursu\\AppData\\Local\\Temp\\pip-install-af2ih57u\\Logbook\\setup.py'"'"'; __file__='"'"'C:\\Users\\pursu\\AppData\\Local\\Temp\\pip-install-af2ih57u\\Logbook\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\pursu\AppData\Local\Temp\pip-install-af2ih57u\Logbook\pip-egg-info'
         cwd: C:\Users\pursu\AppData\Local\Temp\pip-install-af2ih57u\Logbook\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pursu\AppData\Local\Temp\pip-install-af2ih57u\Logbook\setup.py", line 57, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Jmcjake** [comment]
I am having the same issue on mac.

**Comment by cankisagun** [comment]
@Jmcjake @ququant 

Catalyst is not actively maintained
