### ISSUE TITLE
File "catalyst/gens/sim_engine.pyx", line 109, in __iter__ GeneratorExit

### ISSUE THREAD

**Issue by shanhai3000** [enigmampc/catalyst#578]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Mac OS 10.15.5)
* Python Version: Python 3.6.10 :: Anaconda, Inc.
* Python Bitness: `64`
* How did you install Catalyst: (`pip` and `conda`)
* Python packages: 

```
# Name                    Version                   Build  Channel
aiodns                    1.1.1                    pypi_0    pypi
aiohttp                   3.6.2                    pypi_0    pypi
alembic                   0.9.7                    pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrdict                  2.0.1                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
bcolz                     1.2.1           py36h4f17bb1_1001    conda-forge
blosc                     1.19.0               hab81aa3_0
bokeh                     2.1.1            py36h9f0ad1d_0    conda-forge
boto3                     1.5.27                   pypi_0    pypi
botocore                  1.8.50                   pypi_0    pypi
bottleneck                1.2.1                    pypi_0    pypi
bzip2                     1.0.8                haf1e3a3_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cchardet                  2.1.1                    pypi_0    pypi
ccxt                      1.17.94                  pypi_0    pypi
certifi                   2018.1.18                pypi_0    pypi
cffi                      1.14.1                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     6.7                      pypi_0    pypi
cloudpickle               1.5.0                      py_0    conda-forge
contextlib2               0.5.5                    pypi_0    pypi
contextvars               2.4                        py_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cyordereddict             1.0.0                    pypi_0    pypi
cython                    0.27.3                   pypi_0    pypi
cytoolz                   0.10.1                   pypi_0    pypi
dask                      2.23.0                     py_0    conda-forge
dask-core                 2.23.0                     py_0    conda-forge
decorator                 4.3.0                    pypi_0    pypi
distributed               2.23.0           py36h9f0ad1d_0    conda-forge
docutils                  0.16                     pypi_0    pypi
empyrical                 0.2.1                    pypi_0    pypi
enigma-catalyst           0.5.21                   pypi_0    pypi
eth-abi                   1.3.0                    pypi_0    pypi
eth-account               0.2.3                    pypi_0    pypi
eth-hash                  0.2.0                    pypi_0    pypi
eth-keyfile               0.5.1                    pypi_0    pypi
eth-keys                  0.2.4                    pypi_0    pypi
eth-rlp                   0.1.2                    pypi_0    pypi
eth-typing                2.2.1                    pypi_0    pypi
eth-utils                 1.9.3                    pypi_0    pypi
freetype                  2.10.2               h8da9a1a_0    conda-forge
fsspec                    0.8.0                      py_0    conda-forge
hdf5                      1.10.6          nompi_h3e39495_100    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hexbytes                  0.2.1                    pypi_0    pypi
idna                      2.7                      pypi_0    pypi
idna-ssl                  1.1.0                    pypi_0    pypi
immutables                0.14             py36h37b9a7d_0    conda-forge
intervaltree              2.1.0                    pypi_0    pypi
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9d                   h0b31af3_0    conda-forge
kiwisolver                1.2.0                    pypi_0    pypi
lcms2                     2.11                 h174193d_0    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcxx                    10.0.0                        1
libedit                   3.1.20191231         h1de35cc_1
libffi                    3.3                  hb1e8313_2
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
libpng                    1.6.37               hb0a8c7a_2    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
logbook                   0.12.5                   pypi_0    pypi
lru-dict                  1.1.6                    pypi_0    pypi
lxml                      4.5.2                    pypi_0    pypi
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
mako                      1.0.7                    pypi_0    pypi
markupsafe                1.0                      pypi_0    pypi
matplotlib                2.2.2                    pypi_0    pypi
mock                      4.0.2            py36h9f0ad1d_0    conda-forge
msgpack-python            1.0.0            py36h863e41a_1    conda-forge
multidict                 4.7.6                    pypi_0    pypi
multipledispatch          0.4.9                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1
networkx                  2.1                      pypi_0    pypi
numexpr                   2.6.4                    pypi_0    pypi
numpy                     1.14.0                   pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               haf1e3a3_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    0.19.2                   pypi_0    pypi
pandas-datareader         0.6.0                    pypi_0    pypi
parsimonious              0.8.1                    pypi_0    pypi
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.0                    pypi_0    pypi
pillow                    7.2.0            py36h2ae5dfa_1    conda-forge
pip                       20.2.2                   py36_0
psutil                    5.7.2            py36h9de38fb_0    conda-forge
pycares                   3.1.1                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pycryptodome              3.9.8                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.6.10               hf48f09d_2
python-dateutil           2.7.3                    pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2016.4                   pypi_0    pypi
pyyaml                    5.3.1            py36h37b9a7d_0    conda-forge
readline                  8.0                  h1de35cc_0
redo                      2.0.1                    pypi_0    pypi
requests                  2.20.1                   pypi_0    pypi
requests-file             1.4.3                    pypi_0    pypi
requests-ftp              0.3.1                    pypi_0    pypi
requests-toolbelt         0.8.0                    pypi_0    pypi
rlp                       1.2.0                    pypi_0    pypi
s3transfer                0.1.13                   pypi_0    pypi
scipy                     1.0.0                    pypi_0    pypi
setuptools                38.5.1                   pypi_0    pypi
six                       1.11.0                   pypi_0    pypi
snappy                    1.1.8                h4a8c4bd_3    conda-forge
sortedcontainers          1.5.9                    pypi_0    pypi
sqlalchemy                1.2.2                    pypi_0    pypi
sqlite                    3.32.3               hffcf06c_0
statsmodels               0.8.0                    pypi_0    pypi
tables                    3.4.2                    pypi_0    pypi
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hb0a8c7a_0
toolz                     0.9.0                    pypi_0    pypi
tornado                   6.0.4            py36h37b9a7d_1    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
urllib3                   1.24.3                   pypi_0    pypi
web3                      4.4.1                    pypi_0    pypi
websockets                5.0.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h1de35cc_0
yaml                      0.2.5                h0b31af3_0    conda-forge
yarl                      1.1.0                    pypi_0    pypi
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11               h1de35cc_3
zstd                      1.4.5                h0384e3a_1    conda-forge
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

```
[2020-08-15 12:05:51.314732] INFO: run_algo: running algo in backtest mode
[2020-08-15 12:05:51.647742] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Fatal Python error: Acquisition count is -1 (line 22931)
Traceback (most recent call last):
  File "catalyst/gens/sim_engine.pyx", line 109, in __iter__
GeneratorExit
```

**Comment by fire3420** [comment]
Before running your algorithms inside the Jupyter Notebook, remember to ingest the data from the command line interface (CLI). 
```
catalyst ingest-exchange -x bitfinex -i btc_usd
```
