### ISSUE TITLE
[partially solved] Catalyst pyfolio error

### ISSUE THREAD

**Issue by vonpupp** [enigmampc/catalyst#73]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `Linux <hostname removed> 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux`)
* Python Version: `2.7.14`
* Python Bitness: `64`
* How did you install Catalyst: pip
* Python packages: `$ pip freeze` or `$ conda list`:
```
alembic==0.9.6
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
bleach==2.1.1
Bottleneck==1.2.1
certifi==2017.11.5
chardet==3.0.4
click==6.7
configparser==3.5.0
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.1.2
empyrical==0.3.3
enigma-catalyst==0.3.8
entrypoints==0.2.3
enum34==1.1.6
functools32==3.2.3.post2
html5lib==1.0b10
idna==2.6
intervaltree==2.1.0
ipdb==0.10.3
ipykernel==4.6.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.0.5
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
mistune==0.8.1
multipledispatch==0.4.9
names==0.3.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
notebook==5.2.1
numexpr==2.6.4
numpy==1.13.3
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
pathlib2==2.3.0
patsy==0.4.1
petname==2.2
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyfolio==0.8.0
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scandir==1.6
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.15
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.10
tables==3.4.2
terminado==0.7
testpath==0.3.1
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.0.8
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I am not able to use pyfolio with catalyst.

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
```
pip install enigma-catalyst
pip install pyfolio
```
2. When I try to use pyfolio from the results of catalyst

Here is the output
```
(.envc) > $ python strategies/c_true_koala.py
Traceback (most recent call last):
  File "strategies/c_true_koala.py", line 56, in <module>
    from catalyst.api import order, record, symbol, order_target, order_target_value
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 32, in <module>
    from catalyst.exchange.exchange_algorithm import ExchangeTradingAlgorithmLive, \
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 27, in <module>
    from catalyst.algorithm import TradingAlgorithm
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/algorithm.py", line 79, in <module>
    from catalyst.finance.performance import PerformanceTracker
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/finance/performance/__init__.py", line 16, in <module>
    from . tracker import PerformanceTracker
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/finance/performance/tracker.py", line 69, in <module>
    import catalyst.finance.risk as risk
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/finance/risk/__init__.py", line 16, in <module>
    from . report import RiskReport
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/finance/risk/report.py", line 64, in <module>
    from . period import RiskMetricsPeriod
  File "/home/av/repos/customers/mdbasset/.envc-unstable/lib/python2.7/site-packages/catalyst/finance/risk/period.py", line 28, in <module>
    from empyrical import (
ImportError: cannot import name information_ratio ImportError: cannot import name information_ratio
```
## What steps have you taken to resolve this already?

I have researched a bit and it seems to be related to [issue-1855]. So I downgraded empyrical as `pip install empyrical==0.2.2`, and it seems to work.

I just wanted to make a note of [pr-1854] which might need to get merged also at some point.

[pr-1854]: https://github.com/quantopian/zipline/pull/1854
[issue-1855]: https://github.com/quantopian/zipline/issues/1855

# Anything else?

...

Sincerely,

**Comment by fredfortier** [comment]
I've dowgraded empyrical in my environment: `pip install empyrical==0.2.2`. I will test for a while to make sure that it does not break something else. If it seems good, we'll update `requirements.txt`.

**Comment by vonpupp** [comment]
Cool thx Fred.

**Comment by fredfortier** [comment]
Assuming that this is working. Please reopen if it's not.
