### ISSUE TITLE
Is set_benchmark working properly?

### ISSUE THREAD

**Issue by vonpupp** [enigmampc/catalyst#86]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `Linux <hostname removed> 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux`)
* Python Version: `2.7.14`
* Python Bitness: `64`
* How did you install Catalyst: pip
* Python packages: `$ pip freeze`
```
agate==1.6.0
agate-dbf==0.2.0
agate-excel==0.2.1
agate-sql==0.5.2
alabaster==0.7.10
alembic==0.9.6
Babel==2.5.1
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
bleach==2.1.1
Bottleneck==1.2.1
certifi==2017.11.5
chardet==3.0.4
click==6.7
configparser==3.5.0
contextlib2==0.5.5
csvkit==1.0.2
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
dbfread==2.0.7
decorator==4.1.2
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.3.10+5.g7abd992d
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
functools32==3.2.3.post2
future==0.16.0
haikunator==2.1.0
html5lib==1.0b10
idna==2.6
imagesize==0.7.1
intervaltree==2.1.0
ipdb==0.10.3
ipykernel==4.6.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.0.5
isodate==0.6.0
jdcal==1.3
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
leather==0.3.3
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
mistune==0.8.1
multipledispatch==0.4.9
names==0.3.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
notebook==5.2.1
numexpr==2.6.4
numpy==1.13.3
openpyxl==2.4.9
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
parsedatetime==2.4
pathlib2==2.3.0
patsy==0.4.1
petname==2.2
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyfolio==0.8.0
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
python-slugify==1.2.4
pytimeparse==1.1.7
pytz==2017.3
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scandir==1.6
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcontainers==1.5.7
Sphinx==1.6.5
sphinxcontrib-websupport==1.0.1
SQLAlchemy==1.1.15
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.10
tables==3.4.2
terminado==0.7
testpath==0.3.1
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
transitions==0.6.2
typing==3.6.2
Unidecode==0.4.21
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.0.8
xlrd==1.1.0
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I would like to use a simple buy and hold benchmark comparison using the `set_benchmark` function.

* What did you expect to happen?

To go though and be able to se a PnL subplot of the buy and hold strategy.

* What happened instead?

I got the following error:
```
[2017-12-05 00:37:45.257985] INFO: run_algo: running algo in backtest mode
[2017-12-05 00:37:45.941456] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
[2017-12-05 00:37:45.942983] INFO: benchmarktest: 
STARTING SIMULATION.
Candles sample rate: 60
Candles frequency: 60T
Candles buffer size: 48
             
Traceback (most recent call last):
  File "strategies/benchmarktest.py", line 275, in <module>
    live_graph=False
  File "/home/av/repos/test/.envc-unstable/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 594, in run_algorithm
    live_graph=live_graph
  File "/home/av/repos/test/.envc-unstable/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 389, in _run
    overwrite_sim_params=False,
  File "/home/av/repos/test/.envc-unstable/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 280, in run
    data, overwrite_sim_params
  File "/home/av/repos/test/.envc-unstable/lib/python2.7/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/home/av/repos/test/.envc-unstable/lib/python2.7/site-packages/catalyst/algorithm.py", line 623, in get_generator
    return self._create_generator(self.sim_params)
  File "/home/av/repos/test/.envc-unstable/lib/python2.7/site-packages/catalyst/algorithm.py", line 602, in _create_generator
    self._create_benchmark_source(),
  File "/home/av/repos/test/.envc-unstable/lib/python2.7/site-packages/catalyst/algorithm.py", line 560, in _create_benchmark_source
    benchmark_asset = self.asset_finder.retrieve_asset(
AttributeError: 'AssetFinderExchange' object has no attribute 'retrieve_asset'
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Create a default skeleton
2. Add `set_benchmark(symbol(<coin pair>))`

## What steps have you taken to resolve this already?

None, no clue.

Sincerely,
Vonpupp.

**Comment by fredfortier** [comment]
Currently, the benchmark only. I understand what you are trying to do. We can address this before the next release.

**Comment by jspillers** [comment]
Just wanted to share that I also ran into this exact same issue

**Comment by vonpupp** [comment]
Thank you @fredfortier.
