### ISSUE TITLE
get_open_orders() not working in live mode

### ISSUE THREAD

**Issue by demontamer** [enigmampc/catalyst#91]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: ubuntu 16.04
* Python Version: `$ python --2.7`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
This piece of code ` for stock, orders in  get_open_orders().iteritems():` works during back test. But in live mode I get a type error. See traceback below
`Traceback (most recent call last):
  File "weekly_bittrex_btc_live.py", line 972, in <module>
    live_graph=False
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 594, in run_algorithm
    live_graph=live_graph
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 389, in _run
    overwrite_sim_params=False,
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "weekly_bittrex_btc_live.py", line 308, in buy_orders
    context.exposure.update(context,data)
  File "weekly_bittrex_btc_live.py", line 156, in update
    for stock, orders in  get_open_orders().iteritems():
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/utils/api_support.py", line 57, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/utils/input_validation.py", line 831, in assert_keywords_and_call
    return func(*args, **kwargs)
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 792, in get_open_orders
    return self._get_open_orders(asset)
  File "/var/www/FlaskApp/demonApp/catalyst-venv/local/lib/python2.7/site-packages/catalyst/exchange/exchange_algorithm.py", line 754, in _get_open_orders
    exchange_orders = exchange.get_open_orders()
TypeError: get_open_orders() takes exactly 2 arguments (1 given)
`
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. try getting all open orders in live mode.
2. should see catalyst trying to get open orders for a specific asset instead of all
3.
...

## What steps have you taken to resolve this already?
this.
...

# Anything else?

...

Sincerely,
`$ @demontamer

**Comment by fredfortier** [comment]
Unfortunately, this seems to be working by design. A lot of the exchanges don't have a get_order request which spans across all holding, they require to specify a market. For consistency, our method requires a market as well.

Note to that `get_open_orders()` method goes to the exchange to check open orders. It will return orders even if they were not initialized by the algo. This is useful to if we want to avoid placing orders when the orderbook is crowded.

For the open orders of the current algorithm, use `context.portfolio.open_orders`.

**Comment by fredfortier** [comment]
Answered. Unfortunately, `get_open_orders()` do require a parameter. Most the time, `context.portfolio.open_orders` is the correct way to access open orders since it's limited to the scope of the algorithm.
